export interface KPIDefinition {
  id: string
  name: string
  abbreviation: string
  description: string
  formula: string
  unit: string
  domain: KpiDomain
  subdomain: string
  interpretation: string
  thresholds: {
    excellent?: number
    good?: number
    moderate?: number
    critical?: number
    direction: "higher_is_better" | "lower_is_better" | "range"
    rangeMin?: number
    rangeMax?: number
  }
  frequency: "daily" | "weekly" | "monthly" | "quarterly" | "yearly"
  applicableIndustries: string[]
  relatedKpis: string[]
  relatedRisks: string[]
  recommendedActions: string[]
  benchmarkSource?: string
  ifrsConcepts?: string[]
}

export type KpiDomain =
  | "financial" | "liquidity" | "solvency" | "profitability" | "efficiency"
  | "growth" | "operational" | "commercial" | "marketing" | "sales"
  | "production" | "quality" | "logistics" | "inventory"
  | "hr" | "legal" | "compliance" | "tax"
  | "digital" | "technology" | "cybersecurity"
  | "esg" | "sustainability" | "innovation"
  | "customer" | "project" | "risk"

export const kpiCatalog: KPIDefinition[] = [
  // ═══════════════════════════════════════════════════════════════
  // FINANCIAL — LIQUIDITY
  // ═══════════════════════════════════════════════════════════════
  {
    id: "kpi-fin-001", name: "Liquidez Corriente", abbreviation: "LIQ_CORR",
    description: "Capacidad de la empresa para cubrir obligaciones a corto plazo con activos corrientes",
    formula: "Activo Corriente / Pasivo Corriente", unit: "veces",
    domain: "liquidity", subdomain: "liquidez",
    interpretation: ">2: Excelente. 1.5-2: Buena. 1-1.5: Aceptable. <1: Riesgo de liquidez",
    thresholds: { excellent: 2, good: 1.5, moderate: 1, critical: 0.5, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-fin-002", "kpi-fin-003", "kpi-fin-005"],
    relatedRisks: ["riesgo-liquidez"],
    recommendedActions: ["Si < 1.5: Renegociar deuda corto plazo", "Si < 1: Acelerar cobranzas y reducir inventarios"],
    ifrsConcepts: ["ifrs-full:CurrentAssets", "ifrs-full:CurrentLiabilities"],
  },
  {
    id: "kpi-fin-002", name: "Prueba Ácida", abbreviation: "PR_ACIDA",
    description: "Capacidad de pago inmediato excluyendo inventarios (más conservador que liquidez corriente)",
    formula: "(Activo Corriente - Inventarios) / Pasivo Corriente", unit: "veces",
    domain: "liquidity", subdomain: "liquidez",
    interpretation: ">1.5: Excelente. 1-1.5: Buena. 0.5-1: Alerta. <0.5: Crítico",
    thresholds: { excellent: 1.5, good: 1.0, moderate: 0.5, critical: 0.3, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-fin-001", "kpi-fin-003"],
    relatedRisks: ["riesgo-liquidez"],
    recommendedActions: ["Si < 0.8: Implementar plan de mejora de liquidez urgente"],
    ifrsConcepts: ["ifrs-full:CurrentAssets", "ifrs-full:CurrentInventories", "ifrs-full:CurrentLiabilities"],
  },
  {
    id: "kpi-fin-003", name: "Capital de Trabajo", abbreviation: "CAP_TRAB",
    description: "Excedente de activos corrientes sobre pasivos corrientes (colchón financiero)",
    formula: "Activo Corriente - Pasivo Corriente", unit: "USD",
    domain: "liquidity", subdomain: "capital_trabajo",
    interpretation: "Positivo: colchón financiero. Negativo: riesgo de insolvencia técnica",
    thresholds: { good: 100000, moderate: 50000, critical: 0, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-fin-001", "kpi-fin-004"],
    relatedRisks: ["riesgo-liquidez", "riesgo-insolvencia"],
    recommendedActions: ["Si negativo: Reestructurar deuda y optimizar ciclo de efectivo"],
    ifrsConcepts: ["ifrs-full:CurrentAssets", "ifrs-full:CurrentLiabilities"],
  },
  {
    id: "kpi-fin-004", name: "Ciclo de Conversión de Efectivo", abbreviation: "CCC",
    description: "Tiempo que tarda el efectivo en volver a la empresa después de invertirse en inventarios y cuentas por cobrar",
    formula: "DSO + Días Inventario - Días Pago Proveedores", unit: "días",
    domain: "liquidity", subdomain: "capital_trabajo",
    interpretation: "<30: Excelente. 30-60: Bueno. 60-90: Regular. >90: Riesgo de liquidez",
    thresholds: { excellent: 30, good: 60, moderate: 90, critical: 120, direction: "lower_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-fin-005", "kpi-eff-006", "kpi-eff-005"],
    relatedRisks: ["riesgo-liquidez", "riesgo-operativo"],
    recommendedActions: ["Reducir DSO: implementar descuento por pronto pago", "Optimizar inventarios ABC"],
  },
  {
    id: "kpi-fin-005", name: "Días de Cobro (DSO)", abbreviation: "DSO",
    description: "Número promedio de días que la empresa tarda en cobrar sus cuentas por cobrar",
    formula: "(Cuentas por Cobrar / Ingresos) × 365", unit: "días",
    domain: "efficiency", subdomain: "cobranzas",
    interpretation: "<30: Excelente. 30-60: Bueno. 60-90: Regular. >90: Riesgo",
    thresholds: { excellent: 30, good: 60, moderate: 90, critical: 120, direction: "lower_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-fin-004", "kpi-eff-006"],
    relatedRisks: ["riesgo-liquidez", "riesgo-credito"],
    recommendedActions: ["Implementar scoring de clientes", "Descuento 2/10 neto 60", "Automatizar recordatorios de pago"],
    ifrsConcepts: ["ifrs-full:TradeAndOtherCurrentReceivables", "ifrs-full:Revenue"],
  },
  {
    id: "kpi-fin-006", name: "Días de Pago (DPO)", abbreviation: "DPO",
    description: "Número promedio de días que la empresa tarda en pagar a sus proveedores",
    formula: "(Cuentas por Pagar / Costo de Ventas) × 365", unit: "días",
    domain: "efficiency", subdomain: "proveedores",
    interpretation: ">60: Bueno (financiamiento gratuito). 30-60: Normal. <30: Riesgo (presión de proveedores)",
    thresholds: { excellent: 60, good: 45, moderate: 30, critical: 15, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-fin-004"],
    relatedRisks: ["riesgo-proveedores"],
    recommendedActions: ["Negociar plazos con proveedores clave", "Centralizar compras para mayor poder de negociación"],
    ifrsConcepts: ["ifrs-full:TradeAndOtherCurrentPayables", "ifrs-full:CostOfSales"],
  },

  // ═══════════════════════════════════════════════════════════════
  // SOLVENCY
  // ═══════════════════════════════════════════════════════════════
  {
    id: "kpi-fin-010", name: "Endeudamiento Patrimonial", abbreviation: "D_E",
    description: "Proporción de deuda frente al patrimonio neto. Mide el apalancamiento financiero",
    formula: "Pasivo Total / Patrimonio Neto", unit: "veces",
    domain: "solvency", subdomain: "endeudamiento",
    interpretation: "<0.5: Bajo apalancamiento. 0.5-1: Saludable. 1-2: Moderado. >2: Alto riesgo",
    thresholds: { excellent: 0.5, good: 1.0, moderate: 2.0, critical: 3.0, direction: "lower_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-fin-011", "kpi-fin-012", "kpi-fin-013"],
    relatedRisks: ["riesgo-solvencia", "riesgo-endeudamiento"],
    recommendedActions: ["Si > 2: Plan de desapalancamiento", "Refinanciar deuda de alto costo", "Evaluar capitalización"],
    ifrsConcepts: ["ifrs-full:Liabilities", "ifrs-full:Equity"],
  },
  {
    id: "kpi-fin-011", name: "Endeudamiento de Activos", abbreviation: "D_A",
    description: "Porcentaje de activos financiados con deuda",
    formula: "Pasivo Total / Activo Total", unit: "%",
    domain: "solvency", subdomain: "endeudamiento",
    interpretation: "<30%: Bajo. 30-50%: Moderado. 50-70%: Alto. >70%: Riesgo crítico",
    thresholds: { excellent: 0.3, good: 0.5, moderate: 0.7, critical: 0.85, direction: "lower_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-fin-010", "kpi-fin-012"],
    relatedRisks: ["riesgo-solvencia"],
    recommendedActions: ["Reducir dependencia de deuda externa", "Capitalizar utilidades"],
    ifrsConcepts: ["ifrs-full:Liabilities", "ifrs-full:Assets"],
  },
  {
    id: "kpi-fin-012", name: "Cobertura de Intereses", abbreviation: "COB_INT",
    description: "Capacidad de la empresa para pagar intereses con su utilidad operativa",
    formula: "EBIT / Gastos Financieros", unit: "veces",
    domain: "solvency", subdomain: "cobertura",
    interpretation: ">5: Excelente. 3-5: Buena. 1.5-3: Aceptable. <1.5: Riesgo. <1: Crítico",
    thresholds: { excellent: 5, good: 3, moderate: 1.5, critical: 1, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-fin-010", "kpi-fin-013", "kpi-fin-030"],
    relatedRisks: ["riesgo-solvencia", "riesgo-bancarrota"],
    recommendedActions: ["Si < 2: Reestructurar deuda urgente", "Buscar períodos de gracia"],
    ifrsConcepts: ["ifrs-full:OperatingProfitLoss", "ifrs-full:FinanceCosts"],
  },
  {
    id: "kpi-fin-013", name: "Cobertura de Deuda (DSCR)", abbreviation: "DSCR",
    description: "Capacidad de generar efectivo suficiente para pagar el servicio de deuda",
    formula: "Flujo de Caja Operativo / Servicio de Deuda (capital + intereses)", unit: "veces",
    domain: "solvency", subdomain: "cobertura",
    interpretation: ">1.5: Saludable. 1.2-1.5: Aceptable. 1-1.2: Riesgo. <1: Incumplimiento",
    thresholds: { excellent: 1.5, good: 1.2, moderate: 1, critical: 0.8, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-fin-012", "kpi-fin-031"],
    relatedRisks: ["riesgo-solvencia", "riesgo-bancarrota"],
    recommendedActions: ["Si < 1.2: Renegociar plazos", "Si < 1: Buscar capitalización urgente"],
    ifrsConcepts: ["ifrs-full:NetCashFlowsFromOperatingActivities"],
  },
  {
    id: "kpi-fin-014", name: "Apalancamiento Financiero", abbreviation: "APAL",
    description: "Multiplicador del patrimonio usado para financiar activos. A mayor apalancamiento, mayor riesgo",
    formula: "Activo Total / Patrimonio", unit: "veces",
    domain: "solvency", subdomain: "apalancamiento",
    interpretation: "1-2: Bajo. 2-3: Moderado. 3-4: Alto. >4: Muy riesgoso",
    thresholds: { excellent: 1.5, good: 2.5, moderate: 3.5, critical: 4.5, direction: "lower_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-fin-010", "kpi-fin-011"],
    relatedRisks: ["riesgo-solvencia"],
    recommendedActions: ["Reducir apalancamiento vía capitalización o venta de activos"],
    ifrsConcepts: ["ifrs-full:Assets", "ifrs-full:Equity"],
  },

  // ═══════════════════════════════════════════════════════════════
  // PROFITABILITY
  // ═══════════════════════════════════════════════════════════════
  {
    id: "kpi-fin-020", name: "Margen Bruto", abbreviation: "MARG_BRUT",
    description: "Porcentaje de ingresos que queda después de cubrir costos directos de producción",
    formula: "(Ingresos - Costo de Ventas) / Ingresos", unit: "%",
    domain: "profitability", subdomain: "margenes",
    interpretation: ">50%: Excelente. 35-50%: Bueno. 20-35%: Regular. <20%: Riesgo (según industria)",
    thresholds: { excellent: 0.5, good: 0.35, moderate: 0.2, critical: 0.1, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-fin-021", "kpi-fin-022", "kpi-fin-024"],
    relatedRisks: ["riesgo-rentabilidad"],
    recommendedActions: ["Revisar estructura de costos directos", "Negociar mejores precios con proveedores"],
    ifrsConcepts: ["ifrs-full:Revenue", "ifrs-full:CostOfSales"],
  },
  {
    id: "kpi-fin-021", name: "Margen Operativo", abbreviation: "MARG_OPER",
    description: "Rentabilidad de las operaciones principales antes de gastos financieros e impuestos",
    formula: "EBIT / Ingresos", unit: "%",
    domain: "profitability", subdomain: "margenes",
    interpretation: ">20%: Excelente. 12-20%: Bueno. 5-12%: Regular. <5%: Riesgo",
    thresholds: { excellent: 0.2, good: 0.12, moderate: 0.05, critical: 0.02, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-fin-020", "kpi-fin-022", "kpi-fin-030"],
    relatedRisks: ["riesgo-rentabilidad", "riesgo-operativo"],
    recommendedActions: ["Revisar gastos de ventas y administración", "Automatizar procesos operativos"],
    ifrsConcepts: ["ifrs-full:OperatingProfitLoss", "ifrs-full:Revenue"],
  },
  {
    id: "kpi-fin-022", name: "Margen Neto", abbreviation: "MARG_NET",
    description: "Rentabilidad final después de todos los gastos, intereses e impuestos",
    formula: "Utilidad Neta / Ingresos", unit: "%",
    domain: "profitability", subdomain: "margenes",
    interpretation: ">15%: Excelente. 8-15%: Bueno. 3-8%: Regular. <3%: Riesgo",
    thresholds: { excellent: 0.15, good: 0.08, moderate: 0.03, critical: 0, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-fin-020", "kpi-fin-021", "kpi-fin-023"],
    relatedRisks: ["riesgo-rentabilidad"],
    recommendedActions: ["Revisar estructura de costos total", "Evaluar líneas de negocio no rentables"],
    ifrsConcepts: ["ifrs-full:ProfitLoss", "ifrs-full:Revenue"],
  },
  {
    id: "kpi-fin-023", name: "ROE (Return on Equity)", abbreviation: "ROE",
    description: "Retorno generado sobre el capital invertido por los accionistas. Mide eficiencia en uso del patrimonio",
    formula: "Utilidad Neta / Patrimonio", unit: "%",
    domain: "profitability", subdomain: "retorno",
    interpretation: ">20%: Excelente. 12-20%: Bueno. 5-12%: Regular. <5%: Bajo",
    thresholds: { excellent: 0.2, good: 0.12, moderate: 0.05, critical: 0, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-fin-022", "kpi-fin-024", "kpi-fin-025"],
    relatedRisks: ["riesgo-rentabilidad", "riesgo-creacion-valor"],
    recommendedActions: ["Si < WACC: Revisar estrategia de creación de valor", "Evaluar desinversiones"],
    ifrsConcepts: ["ifrs-full:ProfitLoss", "ifrs-full:Equity"],
  },
  {
    id: "kpi-fin-024", name: "ROA (Return on Assets)", abbreviation: "ROA",
    description: "Eficiencia en uso de todos los activos para generar utilidades",
    formula: "Utilidad Neta / Activo Total", unit: "%",
    domain: "profitability", subdomain: "retorno",
    interpretation: ">10%: Excelente. 5-10%: Bueno. 2-5%: Regular. <2%: Bajo",
    thresholds: { excellent: 0.1, good: 0.05, moderate: 0.02, critical: 0, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-fin-023", "kpi-fin-025", "kpi-fin-040"],
    relatedRisks: ["riesgo-eficiencia"],
    recommendedActions: ["Mejorar rotación de activos", "Vender activos ociosos"],
    ifrsConcepts: ["ifrs-full:ProfitLoss", "ifrs-full:Assets"],
  },
  {
    id: "kpi-fin-025", name: "ROCE (Return on Capital Employed)", abbreviation: "ROCE",
    description: "Retorno sobre el capital empleado (deuda + patrimonio). Mide eficiencia del capital total",
    formula: "EBIT / (Activo Total - Pasivo Corriente)", unit: "%",
    domain: "profitability", subdomain: "retorno",
    interpretation: ">20%: Excelente. 12-20%: Bueno. 5-12%: Regular. <5%: Bajo",
    thresholds: { excellent: 0.2, good: 0.12, moderate: 0.05, critical: 0, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-fin-023", "kpi-fin-024"],
    relatedRisks: ["riesgo-eficiencia-capital"],
    recommendedActions: ["Optimizar estructura de capital", "Invertir en proyectos con ROCE > WACC"],
    ifrsConcepts: ["ifrs-full:OperatingProfitLoss", "ifrs-full:Assets", "ifrs-full:CurrentLiabilities"],
  },
  {
    id: "kpi-fin-026", name: "EVA (Economic Value Added)", abbreviation: "EVA",
    description: "Valor económico creado por encima del costo de capital. Si es positivo, la empresa crea valor",
    formula: "NOPAT - (Capital Invertido × WACC)", unit: "USD",
    domain: "profitability", subdomain: "creacion_valor",
    interpretation: "Positivo: creación de valor. Negativo: destrucción de valor",
    thresholds: { good: 0, moderate: -50000, critical: -100000, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-fin-023", "kpi-fin-025", "kpi-fin-060"],
    relatedRisks: ["riesgo-creacion-valor"],
    recommendedActions: ["Si negativo: Revisar rentabilidad del capital invertido", "Desinvertir en unidades no rentables"],
  },

  // ═══════════════════════════════════════════════════════════════
  // EFFICIENCY
  // ═══════════════════════════════════════════════════════════════
  {
    id: "kpi-fin-030", name: "EBITDA", abbreviation: "EBITDA",
    description: "Utilidad antes de intereses, impuestos, depreciación y amortización. Proxy de flujo operativo",
    formula: "EBIT + Depreciación + Amortización", unit: "USD",
    domain: "profitability", subdomain: "ebitda",
    interpretation: "Margen EBITDA > 15% es saludable para la mayoría de industrias",
    thresholds: { excellent: 1000000, good: 500000, moderate: 100000, critical: 0, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-fin-031", "kpi-fin-021"],
    relatedRisks: ["riesgo-rentabilidad"],
    recommendedActions: ["Monitorear tendencia EBITDA trimestral", "Comparar con benchmark sectorial"],
    ifrsConcepts: ["ifrs-full:OperatingProfitLoss"],
  },
  {
    id: "kpi-fin-031", name: "Flujo de Caja Libre (FCF)", abbreviation: "FCF",
    description: "Efectivo disponible después de inversiones para pagar deuda o distribuir dividendos",
    formula: "Flujo Caja Operativo - CAPEX", unit: "USD",
    domain: "profitability", subdomain: "flujo_caja",
    interpretation: "Positivo y creciente: salud financiera. Negativo persistente: riesgo de liquidez",
    thresholds: { excellent: 500000, good: 100000, moderate: 0, critical: -100000, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-fin-030", "kpi-fin-013"],
    relatedRisks: ["riesgo-liquidez", "riesgo-inversion"],
    recommendedActions: ["Si negativo: Revisar CAPEX y capital de trabajo"],
    ifrsConcepts: ["ifrs-full:NetCashFlowsFromOperatingActivities"],
  },
  {
    id: "kpi-fin-032", name: "Rotación de Activos", abbreviation: "ROT_ACT",
    description: "Eficiencia en uso de activos para generar ventas",
    formula: "Ingresos / Activo Total", unit: "veces",
    domain: "efficiency", subdomain: "rotacion",
    interpretation: ">2: Excelente. 1-2: Buena. 0.5-1: Regular. <0.5: Baja",
    thresholds: { excellent: 2, good: 1, moderate: 0.5, critical: 0.3, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-fin-040", "kpi-fin-024"],
    relatedRisks: ["riesgo-eficiencia"],
    recommendedActions: ["Optimizar activos fijos", "Vender activos subutilizados"],
    ifrsConcepts: ["ifrs-full:Revenue", "ifrs-full:Assets"],
  },
  {
    id: "kpi-fin-033", name: "Rotación de Inventario", abbreviation: "ROT_INV",
    description: "Número de veces que el inventario se vende y reemplaza en un período",
    formula: "Costo de Ventas / Inventario Promedio", unit: "veces/año",
    domain: "efficiency", subdomain: "inventarios",
    interpretation: ">12: Excelente (rotación mensual). 6-12: Buena. 3-6: Regular. <3: Baja",
    thresholds: { excellent: 12, good: 6, moderate: 3, critical: 1, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["Manufactura", "Comercio", "Retail"],
    relatedKpis: ["kpi-fin-004", "kpi-fin-034"],
    relatedRisks: ["riesgo-inventario", "riesgo-obsolescencia"],
    recommendedActions: ["Implementar clasificación ABC", "Identificar inventario obsoleto"],
    ifrsConcepts: ["ifrs-full:CostOfSales", "ifrs-full:CurrentInventories"],
  },
  {
    id: "kpi-fin-034", name: "Días de Inventario (DII)", abbreviation: "DII",
    description: "Número promedio de días que el inventario permanece almacenado antes de venderse",
    formula: "(Inventario / Costo de Ventas) × 365", unit: "días",
    domain: "efficiency", subdomain: "inventarios",
    interpretation: "<30: Excelente. 30-60: Bueno. 60-90: Regular. >90: Exceso",
    thresholds: { excellent: 30, good: 60, moderate: 90, critical: 120, direction: "lower_is_better" },
    frequency: "monthly", applicableIndustries: ["Manufactura", "Comercio", "Retail"],
    relatedKpis: ["kpi-fin-033", "kpi-fin-004"],
    relatedRisks: ["riesgo-inventario"],
    recommendedActions: ["Reducir lotes de compra", "Implementar just-in-time"],
  },
  {
    id: "kpi-fin-035", name: "Rotación de Cuentas por Cobrar", abbreviation: "ROT_CC",
    description: "Número de veces que las cuentas por cobrar se convierten en efectivo",
    formula: "Ingresos / Cuentas por Cobrar Promedio", unit: "veces/año",
    domain: "efficiency", subdomain: "cobranzas",
    interpretation: ">12: Excelente. 6-12: Buena. 4-6: Regular. <4: Riesgo",
    thresholds: { excellent: 12, good: 6, moderate: 4, critical: 2, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-fin-005", "kpi-fin-004"],
    relatedRisks: ["riesgo-credito"],
    recommendedActions: ["Revisar políticas de crédito", "Implementar scoring de clientes"],
  },

  // ═══════════════════════════════════════════════════════════════
  // GROWTH
  // ═══════════════════════════════════════════════════════════════
  {
    id: "kpi-growth-001", name: "Crecimiento de Ingresos", abbreviation: "CREC_ING",
    description: "Variación porcentual de ingresos respecto al período anterior",
    formula: "(Ingresos_t - Ingresos_{t-1}) / Ingresos_{t-1}", unit: "%",
    domain: "growth", subdomain: "ingresos",
    interpretation: "> inflación + 5%: Excelente. > inflación: Bueno. 0-inflación: Estancamiento. <0: Decrecimiento",
    thresholds: { excellent: 0.15, good: 0.08, moderate: 0, critical: -0.1, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-growth-002", "kpi-growth-003"],
    relatedRisks: ["riesgo-mercado"],
    recommendedActions: ["Si < inflación: Revisar estrategia comercial", "Diversificar canales"],
    ifrsConcepts: ["ifrs-full:Revenue"],
  },
  {
    id: "kpi-growth-002", name: "Crecimiento del EBITDA", abbreviation: "CREC_EBITDA",
    description: "Variación porcentual del EBITDA respecto al período anterior",
    formula: "(EBITDA_t - EBITDA_{t-1}) / EBITDA_{t-1}", unit: "%",
    domain: "growth", subdomain: "rentabilidad",
    interpretation: ">15%: Excelente. 5-15%: Bueno. 0-5%: Estable. <0: Deterioro",
    thresholds: { excellent: 0.15, good: 0.05, moderate: 0, critical: -0.1, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-growth-001", "kpi-fin-030"],
    relatedRisks: ["riesgo-rentabilidad"],
    recommendedActions: ["Revisar estructura de costos", "Mejorar eficiencia operativa"],
  },
  {
    id: "kpi-growth-003", name: "Market Share", abbreviation: "MKTSHARE",
    description: "Participación de la empresa en el mercado relevante",
    formula: "Ingresos Empresa / Ingresos Totales Mercado", unit: "%",
    domain: "growth", subdomain: "mercado",
    interpretation: "Creciente: ganando mercado. Decreciente: perdiendo competitividad",
    thresholds: { excellent: 0.2, good: 0.1, moderate: 0.05, critical: 0.01, direction: "higher_is_better" },
    frequency: "quarterly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-growth-001", "kpi-growth-004"],
    relatedRisks: ["riesgo-mercado", "riesgo-competitivo"],
    recommendedActions: ["Invertir en diferenciación competitiva", "Fortalecer propuesta de valor"],
  },
  {
    id: "kpi-growth-004", name: "Tasa de Retención de Clientes", abbreviation: "RET_CLI",
    description: "Porcentaje de clientes que continúan comprando en un período",
    formula: "(Clientes Final - Nuevos) / Clientes Inicio", unit: "%",
    domain: "growth", subdomain: "clientes",
    interpretation: ">90%: Excelente. 80-90%: Bueno. 70-80%: Regular. <70%: Riesgo",
    thresholds: { excellent: 0.9, good: 0.8, moderate: 0.7, critical: 0.5, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["Servicios", "Tecnología", "Suscripción"],
    relatedKpis: ["kpi-growth-005", "kpi-cust-001"],
    relatedRisks: ["riesgo-churn"],
    recommendedActions: ["Programa de fidelización", "Mejorar servicio post-venta"],
  },
  {
    id: "kpi-growth-005", name: "Churn Rate", abbreviation: "CHURN",
    description: "Porcentaje de clientes que cancelan o dejan de comprar",
    formula: "Clientes Perdidos / Clientes Totales", unit: "%",
    domain: "growth", subdomain: "clientes",
    interpretation: "<2%: Excelente. 2-5%: Bueno. 5-8%: Regular. >8%: Riesgo",
    thresholds: { excellent: 0.02, good: 0.05, moderate: 0.08, critical: 0.15, direction: "lower_is_better" },
    frequency: "monthly", applicableIndustries: ["Servicios", "Tecnología", "Suscripción"],
    relatedKpis: ["kpi-growth-004", "kpi-cust-003"],
    relatedRisks: ["riesgo-churn"],
    recommendedActions: ["Entrevistas de salida", "Programa de recuperación de clientes"],
  },

  // ═══════════════════════════════════════════════════════════════
  // VALUATION
  // ═══════════════════════════════════════════════════════════════
  {
    id: "kpi-fin-040", name: "Precio / Valor en Libros (P/BV)", abbreviation: "P_BV",
    description: "Relación entre el valor de mercado y el valor contable del patrimonio",
    formula: "Capitalización de Mercado / Patrimonio Neto", unit: "veces",
    domain: "financial", subdomain: "valoracion",
    interpretation: ">1: Mercado valora más que libros. <1: Acción subvalorada o problemas",
    thresholds: { excellent: 3, good: 1.5, moderate: 1, critical: 0.5, direction: "range", rangeMin: 1, rangeMax: 3 },
    frequency: "quarterly", applicableIndustries: ["Públicas"],
    relatedKpis: ["kpi-fin-041"],
    relatedRisks: ["riesgo-valoracion"],
    recommendedActions: ["Analizar valor intrínseco vs mercado", "Revisar estrategia de creación de valor"],
  },
  {
    id: "kpi-fin-041", name: "PER (Price Earnings Ratio)", abbreviation: "PER",
    description: "Relación entre precio de acción y utilidad por acción. Indica expectativas de crecimiento",
    formula: "Precio Acción / EPS", unit: "veces",
    domain: "financial", subdomain: "valoracion",
    interpretation: "10-20: Normal. 20-30: Altas expectativas. >30: Sobrevalorado. <10: Subvalorado",
    thresholds: { excellent: 15, good: 20, moderate: 10, critical: 30, direction: "range", rangeMin: 10, rangeMax: 20 },
    frequency: "quarterly", applicableIndustries: ["Públicas"],
    relatedKpis: ["kpi-fin-040", "kpi-fin-042"],
    relatedRisks: ["riesgo-valoracion"],
    recommendedActions: ["Comparar PER contra industria y mercado"],
  },
  {
    id: "kpi-fin-042", name: "EPS (Earnings Per Share)", abbreviation: "EPS",
    description: "Utilidad neta atribuible a cada acción ordinaria",
    formula: "Utilidad Neta / Número de Acciones", unit: "USD/acción",
    domain: "financial", subdomain: "valoracion",
    interpretation: "Creciente: buena señal. Decreciente: deterioro",
    thresholds: { excellent: 5, good: 2, moderate: 0.5, critical: 0, direction: "higher_is_better" },
    frequency: "quarterly", applicableIndustries: ["Públicas"],
    relatedKpis: ["kpi-fin-041", "kpi-fin-023"],
    relatedRisks: ["riesgo-valoracion"],
    recommendedActions: ["Monitorear tendencia EPS trimestral", "Comparar EPS vs proyecciones del mercado"],
    ifrsConcepts: ["ifrs-full:BasicEarningsPerShare"],
  },

  // ═══════════════════════════════════════════════════════════════
  // WACC / CAPITAL
  // ═══════════════════════════════════════════════════════════════
  {
    id: "kpi-fin-060", name: "WACC (Costo Promedio Ponderado de Capital)", abbreviation: "WACC",
    description: "Tasa de descuento que refleja el costo promedio de todas las fuentes de financiamiento",
    formula: "(E/V × Ke) + (D/V × Kd × (1-t))", unit: "%",
    domain: "financial", subdomain: "costo_capital",
    interpretation: "WACC bajo = estructura de capital óptima. WACC alto = costo de capital elevado",
    thresholds: { excellent: 0.08, good: 0.12, moderate: 0.15, critical: 0.2, direction: "lower_is_better" },
    frequency: "quarterly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-fin-023", "kpi-fin-025", "kpi-fin-026"],
    relatedRisks: ["riesgo-estructura-capital"],
    recommendedActions: ["Optimizar estructura de deuda/equity", "Buscar financiamiento más barato"],
  },
  {
    id: "kpi-fin-061", name: "Costo de Deuda (Kd)", abbreviation: "KD",
    description: "Tasa de interés efectiva que paga la empresa por su deuda financiera",
    formula: "Gastos Financieros / Deuda Financiera Promedio", unit: "%",
    domain: "financial", subdomain: "costo_capital",
    interpretation: "<8%: Bueno. 8-12%: Normal. 12-18%: Alto. >18%: Usura",
    thresholds: { excellent: 0.08, good: 0.12, moderate: 0.16, critical: 0.2, direction: "lower_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-fin-060", "kpi-fin-012"],
    relatedRisks: ["riesgo-endeudamiento"],
    recommendedActions: ["Refinanciar deuda de alto costo", "Mejorar perfil crediticio"],
  },
  {
    id: "kpi-fin-062", name: "Altman Z-Score", abbreviation: "ZSCORE",
    description: "Indicador de probabilidad de bancarrota en 2 años (empresas manufactureras públicas)",
    formula: "1.2A + 1.4B + 3.3C + 0.6D + 1.0E donde A=CapitalTrabajo/Activos, B=UtilRetenida/Activos, C=EBIT/Activos, D=ValorMercado/Deuda, E=Ventas/Activos", unit: "puntos",
    domain: "solvency", subdomain: "bancarrota",
    interpretation: ">2.99: Zona segura. 1.81-2.99: Zona gris. <1.81: Zona de peligro",
    thresholds: { excellent: 3, good: 2.99, moderate: 1.81, critical: 1, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["Manufactura", "Públicas"],
    relatedKpis: ["kpi-fin-010", "kpi-fin-012", "kpi-fin-013"],
    relatedRisks: ["riesgo-bancarrota"],
    recommendedActions: ["Si < 1.81: Reestructuración financiera urgente", "Buscar capitalización"],
  },

  // ═══════════════════════════════════════════════════════════════
  // OPERATIONAL — PRODUCTION
  // ═══════════════════════════════════════════════════════════════
  {
    id: "kpi-ops-001", name: "OEE (Overall Equipment Effectiveness)", abbreviation: "OEE",
    description: "Efectividad global de equipos productivos: disponibilidad × rendimiento × calidad",
    formula: "Disponibilidad × Rendimiento × Calidad", unit: "%",
    domain: "operational", subdomain: "produccion",
    interpretation: ">85%: World Class. 75-85%: Aceptable. 60-75%: Regular. <60%: Bajo",
    thresholds: { excellent: 0.85, good: 0.75, moderate: 0.6, critical: 0.4, direction: "higher_is_better" },
    frequency: "daily", applicableIndustries: ["Manufactura", "Producción"],
    relatedKpis: ["kpi-ops-002", "kpi-ops-003", "kpi-ops-004"],
    relatedRisks: ["riesgo-operativo", "riesgo-produccion"],
    recommendedActions: ["Implementar TPM", "Reducir tiempos de cambio (SMED)", "Mejorar mantenimiento preventivo"],
  },
  {
    id: "kpi-ops-002", name: "Disponibilidad de Equipos", abbreviation: "DISP_EQ",
    description: "Porcentaje de tiempo que los equipos están disponibles para producción",
    formula: "(Tiempo Planeado - Tiempo Parada) / Tiempo Planeado", unit: "%",
    domain: "operational", subdomain: "produccion",
    interpretation: ">95%: Excelente. 90-95%: Buena. 85-90%: Regular. <85%: Baja",
    thresholds: { excellent: 0.95, good: 0.9, moderate: 0.85, critical: 0.8, direction: "higher_is_better" },
    frequency: "daily", applicableIndustries: ["Manufactura"],
    relatedKpis: ["kpi-ops-001", "kpi-ops-003"],
    relatedRisks: ["riesgo-produccion"],
    recommendedActions: ["Mantenimiento preventivo programado", "Análisis de paradas críticas"],
  },
  {
    id: "kpi-ops-003", name: "Rendimiento de Producción", abbreviation: "REND_PROD",
    description: "Velocidad real de producción vs velocidad teórica",
    formula: "(Producción Real × Tiempo Ciclo Ideal) / Tiempo Operativo", unit: "%",
    domain: "operational", subdomain: "produccion",
    interpretation: ">95%: Excelente. 85-95%: Bueno. 75-85%: Regular. <75%: Bajo",
    thresholds: { excellent: 0.95, good: 0.85, moderate: 0.75, critical: 0.6, direction: "higher_is_better" },
    frequency: "daily", applicableIndustries: ["Manufactura"],
    relatedKpis: ["kpi-ops-001", "kpi-ops-002"],
    relatedRisks: ["riesgo-produccion"],
    recommendedActions: ["Reducir micro-paradas", "Estandarizar métodos de trabajo"],
  },
  {
    id: "kpi-ops-004", name: "Tasa de Defectos / Scrap", abbreviation: "DEFECTOS",
    description: "Porcentaje de productos defectuosos sobre producción total",
    formula: "Unidades Defectuosas / Unidades Totales", unit: "%",
    domain: "quality", subdomain: "calidad",
    interpretation: "<1%: Excelente. 1-3%: Bueno. 3-5%: Regular. >5%: Riesgo",
    thresholds: { excellent: 0.01, good: 0.03, moderate: 0.05, critical: 0.1, direction: "lower_is_better" },
    frequency: "daily", applicableIndustries: ["Manufactura"],
    relatedKpis: ["kpi-ops-001", "kpi-ops-008"],
    relatedRisks: ["riesgo-calidad"],
    recommendedActions: ["Análisis de causa raíz (5 porqués)", "Implementar control estadístico de procesos (SPC)"],
  },
  {
    id: "kpi-ops-005", name: "Costo por Unidad Producida", abbreviation: "CPU",
    description: "Costo total de producción dividido por unidades producidas",
    formula: "Costo Total Producción / Unidades Producidas", unit: "USD/unidad",
    domain: "operational", subdomain: "costos",
    interpretation: "Decreciente: mejora de eficiencia. Creciente: alerta",
    thresholds: { good: 100, moderate: 150, critical: 200, direction: "lower_is_better" },
    frequency: "monthly", applicableIndustries: ["Manufactura"],
    relatedKpis: ["kpi-ops-001", "kpi-fin-020"],
    relatedRisks: ["riesgo-costos"],
    recommendedActions: ["Revisar desperdicios", "Negociar insumos", "Mejorar productividad"],
  },
  {
    id: "kpi-ops-006", name: "Capacidad Utilizada", abbreviation: "CAP_USO",
    description: "Porcentaje de capacidad productiva utilizada",
    formula: "Producción Real / Capacidad Instalada", unit: "%",
    domain: "operational", subdomain: "capacidad",
    interpretation: "80-90%: Óptimo. >90%: Riesgo de saturación. <70%: Capacidad ociosa",
    thresholds: { excellent: 0.85, good: 0.8, moderate: 0.7, critical: 0.5, direction: "range", rangeMin: 0.75, rangeMax: 0.9 },
    frequency: "weekly", applicableIndustries: ["Manufactura"],
    relatedKpis: ["kpi-ops-001", "kpi-ops-005"],
    relatedRisks: ["riesgo-operativo"],
    recommendedActions: ["Si >90%: Plan de expansión. Si <70%: Buscar nuevos mercados o productos"],
  },
  {
    id: "kpi-ops-007", name: "Tiempo de Ciclo Promedio", abbreviation: "CICLO",
    description: "Tiempo total desde inicio a fin de un proceso productivo",
    formula: "Tiempo Total / Unidades Completadas", unit: "minutos",
    domain: "operational", subdomain: "eficiencia",
    interpretation: "Decreciente = mejora continua. Incremento = problema",
    thresholds: { good: 60, moderate: 120, critical: 180, direction: "lower_is_better" },
    frequency: "daily", applicableIndustries: ["Manufactura"],
    relatedKpis: ["kpi-ops-001", "kpi-ops-005"],
    relatedRisks: ["riesgo-operativo"],
    recommendedActions: ["Mapeo de flujo de valor (VSM)", "Eliminar cuellos de botella"],
  },
  {
    id: "kpi-ops-008", name: "First Pass Yield (FPY)", abbreviation: "FPY",
    description: "Porcentaje de productos que pasan todas las inspecciones sin necesidad de reproceso",
    formula: "Unidades sin Defectos / Unidades Totales", unit: "%",
    domain: "quality", subdomain: "calidad",
    interpretation: ">97%: Excelente. 95-97%: Bueno. 90-95%: Regular. <90%: Riesgo",
    thresholds: { excellent: 0.97, good: 0.95, moderate: 0.9, critical: 0.85, direction: "higher_is_better" },
    frequency: "daily", applicableIndustries: ["Manufactura"],
    relatedKpis: ["kpi-ops-004", "kpi-ops-001"],
    relatedRisks: ["riesgo-calidad"],
    recommendedActions: ["Análisis de modos de falla (FMEA)", "Mejorar procesos aguas arriba"],
  },
  {
    id: "kpi-ops-009", name: "Costo de Mantenimiento por Unidad", abbreviation: "CMU",
    description: "Costo de mantenimiento por cada unidad producida",
    formula: "Costo Total Mantenimiento / Unidades Producidas", unit: "USD/unidad",
    domain: "operational", subdomain: "mantenimiento",
    interpretation: "Indicador de eficiencia del programa de mantenimiento",
    thresholds: { good: 5, moderate: 10, critical: 15, direction: "lower_is_better" },
    frequency: "monthly", applicableIndustries: ["Manufactura"],
    relatedKpis: ["kpi-ops-002", "kpi-ops-005"],
    relatedRisks: ["riesgo-operativo"],
    recommendedActions: ["Evaluar mantenimiento preventivo vs correctivo"],
  },
  {
    id: "kpi-ops-010", name: "MTBF (Mean Time Between Failures)", abbreviation: "MTBF",
    description: "Tiempo promedio entre fallas de equipos. Mide confiabilidad",
    formula: "Tiempo Total Operativo / Número de Fallas", unit: "horas",
    domain: "operational", subdomain: "mantenimiento",
    interpretation: "Creciente: mejora. Decreciente: deterioro",
    thresholds: { excellent: 1000, good: 500, moderate: 200, critical: 100, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["Manufactura"],
    relatedKpis: ["kpi-ops-002", "kpi-ops-009"],
    relatedRisks: ["riesgo-produccion"],
    recommendedActions: ["Análisis de criticidad", "Mejorar mantenimiento predictivo"],
  },
  {
    id: "kpi-ops-011", name: "MTTR (Mean Time To Repair)", abbreviation: "MTTR",
    description: "Tiempo promedio para reparar una falla. Mide capacidad de respuesta",
    formula: "Tiempo Total Reparación / Número de Reparaciones", unit: "horas",
    domain: "operational", subdomain: "mantenimiento",
    interpretation: "Decreciente: mejora. Creciente: problema",
    thresholds: { excellent: 2, good: 4, moderate: 8, critical: 12, direction: "lower_is_better" },
    frequency: "monthly", applicableIndustries: ["Manufactura"],
    relatedKpis: ["kpi-ops-010", "kpi-ops-002"],
    relatedRisks: ["riesgo-produccion"],
    recommendedActions: ["Mejorar stock de repuestos críticos", "Capacitar técnicos"],
  },

  // ═══════════════════════════════════════════════════════════════
  // LOGISTICS & SUPPLY CHAIN
  // ═══════════════════════════════════════════════════════════════
  {
    id: "kpi-log-001", name: "Cumplimiento de Entregas (OTIF)", abbreviation: "OTIF",
    description: "On Time In Full: entregas completas en la fecha prometida",
    formula: "Pedidos Entregados a Tiempo y Completos / Total Pedidos", unit: "%",
    domain: "operational", subdomain: "logistica",
    interpretation: ">98%: Excelente. 95-98%: Bueno. 90-95%: Regular. <90%: Riesgo",
    thresholds: { excellent: 0.98, good: 0.95, moderate: 0.9, critical: 0.85, direction: "higher_is_better" },
    frequency: "weekly", applicableIndustries: ["Manufactura", "Comercio", "Logística"],
    relatedKpis: ["kpi-log-002"],
    relatedRisks: ["riesgo-logistico", "riesgo-satisfaccion"],
    recommendedActions: ["Optimizar rutas de entrega", "Mejorar gestión de inventarios"],
  },
  {
    id: "kpi-log-002", name: "Tiempo de Entrega Promedio", abbreviation: "T_ENTREGA",
    description: "Tiempo desde que se recibe el pedido hasta que se entrega al cliente",
    formula: "Suma Tiempos Entrega / Número de Entregas", unit: "días",
    domain: "operational", subdomain: "logistica",
    interpretation: "Mejor cuanto menor. Varía según industria",
    thresholds: { good: 3, moderate: 7, critical: 14, direction: "lower_is_better" },
    frequency: "weekly", applicableIndustries: ["Logística", "Comercio"],
    relatedKpis: ["kpi-log-001"],
    relatedRisks: ["riesgo-logistico"],
    recommendedActions: ["Optimizar ruteo", "Mejorar coordinación bodega-transporte"],
  },
  {
    id: "kpi-log-003", name: "Costo Logístico por Unidad", abbreviation: "CLU",
    description: "Costo total de logística dividido por unidades distribuidas",
    formula: "Costo Logístico Total / Unidades Distribuidas", unit: "USD/unidad",
    domain: "operational", subdomain: "logistica",
    interpretation: "Decreciente = mejora",
    thresholds: { good: 5, moderate: 10, critical: 15, direction: "lower_is_better" },
    frequency: "monthly", applicableIndustries: ["Logística", "Comercio", "Manufactura"],
    relatedKpis: ["kpi-log-004"],
    relatedRisks: ["riesgo-costos"],
    recommendedActions: ["Consolidar envíos", "Negociar tarifas con transportistas"],
  },
  {
    id: "kpi-log-004", name: "Rotación de Bodega", abbreviation: "ROT_BOD",
    description: "Número de veces que el inventario en bodega se renueva en un período",
    formula: "Unidades Despachadas / Inventario Promedio Bodega", unit: "veces/año",
    domain: "operational", subdomain: "bodega",
    interpretation: ">12: Alta rotación. 6-12: Normal. <6: Baja rotación",
    thresholds: { excellent: 12, good: 6, moderate: 3, critical: 1, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["Comercio", "Logística"],
    relatedKpis: ["kpi-fin-033"],
    relatedRisks: ["riesgo-inventario"],
    recommendedActions: ["Implementar slotting optimization", "Revisar política de inventarios"],
  },

  // ═══════════════════════════════════════════════════════════════
  // COMMERCIAL & SALES
  // ═══════════════════════════════════════════════════════════════
  {
    id: "kpi-sales-001", name: "Ticket Promedio", abbreviation: "TKT_PROM",
    description: "Valor promedio de cada venta o transacción",
    formula: "Ingresos Totales / Número de Transacciones", unit: "USD",
    domain: "commercial", subdomain: "ventas",
    interpretation: "Creciente: ventas de mayor valor. Decreciente: posible canibalización",
    thresholds: { good: 100, moderate: 50, critical: 25, direction: "higher_is_better" },
    frequency: "daily", applicableIndustries: ["Comercio", "Retail", "Servicios"],
    relatedKpis: ["kpi-sales-003"],
    relatedRisks: ["riesgo-comercial"],
    recommendedActions: ["Upselling y cross-selling", "Segmentar clientes por valor"],
  },
  {
    id: "kpi-sales-002", name: "Tasa de Conversión", abbreviation: "CONV",
    description: "Porcentaje de leads que se convierten en clientes",
    formula: "Clientes Nuevos / Leads Totales", unit: "%",
    domain: "commercial", subdomain: "ventas",
    interpretation: ">20%: Excelente. 10-20%: Bueno. 5-10%: Regular. <5%: Bajo",
    thresholds: { excellent: 0.2, good: 0.1, moderate: 0.05, critical: 0.02, direction: "higher_is_better" },
    frequency: "weekly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-sales-004", "kpi-sales-005"],
    relatedRisks: ["riesgo-comercial"],
    recommendedActions: ["Mejorar calificación de leads", "Optimizar proceso de ventas"],
  },
  {
    id: "kpi-sales-003", name: "CAC (Customer Acquisition Cost)", abbreviation: "CAC",
    description: "Costo de adquirir un nuevo cliente",
    formula: "Gastos de Ventas y Marketing / Nuevos Clientes", unit: "USD",
    domain: "commercial", subdomain: "ventas",
    interpretation: "Bajo vs LTV: eficiente. CAC > LTV: modelo insostenible",
    thresholds: { good: 500, moderate: 1000, critical: 2000, direction: "lower_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-sales-008", "kpi-sales-002"],
    relatedRisks: ["riesgo-comercial"],
    recommendedActions: ["Optimizar canales de adquisición", "Mejorar segmentación"],
  },
  {
    id: "kpi-sales-004", name: "Ciclo de Ventas Promedio", abbreviation: "CICLO_VTA",
    description: "Tiempo promedio desde el primer contacto hasta el cierre",
    formula: "Suma Días Ciclo / Número de Ventas Cerradas", unit: "días",
    domain: "commercial", subdomain: "ventas",
    interpretation: "Decreciente: mejora de eficiencia",
    thresholds: { excellent: 30, good: 60, moderate: 90, critical: 120, direction: "lower_is_better" },
    frequency: "monthly", applicableIndustries: ["Servicios", "Tecnología", "B2B"],
    relatedKpis: ["kpi-sales-002"],
    relatedRisks: ["riesgo-comercial"],
    recommendedActions: ["Automatizar seguimientos", "Mejorar propuesta de valor"],
  },
  {
    id: "kpi-sales-005", name: "Pipeline Coverage", abbreviation: "PIPELINE",
    description: "Valor total de oportunidades en pipeline vs cuota de ventas",
    formula: "Valor Pipeline / Cuota de Ventas", unit: "veces",
    domain: "commercial", subdomain: "ventas",
    interpretation: ">4x: Sano. 3-4x: Adecuado. 2-3x: Riesgo. <2x: Crítico",
    thresholds: { excellent: 4, good: 3, moderate: 2, critical: 1, direction: "higher_is_better" },
    frequency: "weekly", applicableIndustries: ["Servicios", "Tecnología", "B2B"],
    relatedKpis: ["kpi-sales-002", "kpi-sales-003"],
    relatedRisks: ["riesgo-comercial"],
    recommendedActions: ["Generar más leads calificados", "Revisar proceso de calificación"],
  },
  {
    id: "kpi-sales-006", name: "Ventas por Vendedor", abbreviation: "VTA_VEND",
    description: "Ingresos generados por cada vendedor en el período",
    formula: "Ingresos Totales / Número de Vendedores", unit: "USD",
    domain: "commercial", subdomain: "rendimiento",
    interpretation: "Indicador de productividad del equipo comercial",
    thresholds: { excellent: 500000, good: 200000, moderate: 100000, critical: 50000, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-sales-007"],
    relatedRisks: ["riesgo-comercial"],
    recommendedActions: ["Capacitar equipo", "Revisar territorios y cuotas"],
  },
  {
    id: "kpi-sales-007", name: "Tasa de Cierre (Win Rate)", abbreviation: "WINRATE",
    description: "Porcentaje de oportunidades que resultan en ventas cerradas",
    formula: "Oportunidades Ganadas / Oportunidades Totales", unit: "%",
    domain: "commercial", subdomain: "rendimiento",
    interpretation: ">30%: Excelente. 20-30%: Bueno. 10-20%: Regular. <10%: Bajo",
    thresholds: { excellent: 0.3, good: 0.2, moderate: 0.1, critical: 0.05, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["Servicios", "Tecnología", "B2B"],
    relatedKpis: ["kpi-sales-002", "kpi-sales-004"],
    relatedRisks: ["riesgo-comercial"],
    recommendedActions: ["Analizar por qué se pierden oportunidades", "Mejorar propuesta de valor"],
  },
  {
    id: "kpi-sales-008", name: "LTV (LifeTime Value)", abbreviation: "LTV",
    description: "Valor total que un cliente genera durante toda su relación con la empresa",
    formula: "Ticket Promedio × Frecuencia Compra × Vida Promedio", unit: "USD",
    domain: "commercial", subdomain: "clientes",
    interpretation: "LTV / CAC > 3: Saludable. > 5: Excelente",
    thresholds: { excellent: 10000, good: 5000, moderate: 2000, critical: 1000, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-sales-003", "kpi-cust-001", "kpi-growth-004"],
    relatedRisks: ["riesgo-comercial"],
    recommendedActions: ["Mejorar retención", "Aumentar frecuencia de compra"],
  },

  // ═══════════════════════════════════════════════════════════════
  // MARKETING
  // ═══════════════════════════════════════════════════════════════
  {
    id: "kpi-mkt-001", name: "ROI de Marketing", abbreviation: "ROMI",
    description: "Retorno sobre inversión en marketing",
    formula: "(Ingresos Atribuibles - Inversión Marketing) / Inversión Marketing", unit: "%",
    domain: "marketing", subdomain: "rendimiento",
    interpretation: ">5: Excelente. 3-5: Bueno. 1-3: Regular. <1: Negativo",
    thresholds: { excellent: 5, good: 3, moderate: 1, critical: 0, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-mkt-002", "kpi-mkt-005"],
    relatedRisks: ["riesgo-comercial"],
    recommendedActions: ["Optimizar canales con mejor ROI", "Revisar campañas de bajo rendimiento"],
  },
  {
    id: "kpi-mkt-002", name: "CPL (Cost Per Lead)", abbreviation: "CPL",
    description: "Costo de generar un lead calificado",
    formula: "Gasto Marketing / Leads Generados", unit: "USD",
    domain: "marketing", subdomain: "eficiencia",
    interpretation: "Bajo = eficiente. Alto = revisar canales",
    thresholds: { excellent: 20, good: 50, moderate: 100, critical: 200, direction: "lower_is_better" },
    frequency: "weekly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-mkt-003", "kpi-sales-003"],
    relatedRisks: ["riesgo-comercial"],
    recommendedActions: ["Optimizar segmentación", "Probar nuevos canales digitales"],
  },
  {
    id: "kpi-mkt-003", name: "Lead-to-Customer Rate", abbreviation: "L2C",
    description: "Porcentaje de leads que se convierten en clientes",
    formula: "Clientes Nuevos / Leads Totales", unit: "%",
    domain: "marketing", subdomain: "conversion",
    interpretation: ">10%: Bueno. 5-10%: Regular. <5%: Bajo",
    thresholds: { excellent: 0.15, good: 0.1, moderate: 0.05, critical: 0.02, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-mkt-001", "kpi-sales-002"],
    relatedRisks: ["riesgo-comercial"],
    recommendedActions: ["Mejorar calificación de leads", "Optimizar proceso de ventas"],
  },
  {
    id: "kpi-mkt-004", name: "Website Conversion Rate", abbreviation: "WEB_CONV",
    description: "Porcentaje de visitantes web que realizan una acción deseada",
    formula: "Conversiones / Visitantes Únicos", unit: "%",
    domain: "marketing", subdomain: "digital",
    interpretation: ">5%: Excelente. 2-5%: Bueno. 1-2%: Regular. <1%: Bajo",
    thresholds: { excellent: 0.05, good: 0.02, moderate: 0.01, critical: 0.005, direction: "higher_is_better" },
    frequency: "daily", applicableIndustries: ["*"],
    relatedKpis: ["kpi-mkt-001", "kpi-mkt-005"],
    relatedRisks: ["riesgo-comercial"],
    recommendedActions: ["A/B testing en landing pages", "Mejorar llamados a la acción"],
  },
  {
    id: "kpi-mkt-005", name: "CAC Payback Period", abbreviation: "CAC_PAY",
    description: "Tiempo necesario para recuperar la inversión de adquirir un cliente",
    formula: "CAC / Margen Mensual Promedio por Cliente", unit: "meses",
    domain: "marketing", subdomain: "eficiencia",
    interpretation: "<6 meses: Excelente. 6-12: Bueno. 12-18: Regular. >18: Riesgo",
    thresholds: { excellent: 6, good: 12, moderate: 18, critical: 24, direction: "lower_is_better" },
    frequency: "monthly", applicableIndustries: ["Suscripción", "Servicios", "Tecnología"],
    relatedKpis: ["kpi-sales-003", "kpi-sales-008"],
    relatedRisks: ["riesgo-comercial"],
    recommendedActions: ["Optimizar canales de adquisición", "Mejorar segmentación"],
  },

  // ═══════════════════════════════════════════════════════════════
  // CUSTOMER
  // ═══════════════════════════════════════════════════════════════
  {
    id: "kpi-cust-001", name: "NPS (Net Promoter Score)", abbreviation: "NPS",
    description: "Lealtad del cliente: qué tan probable es que recomiende la empresa",
    formula: "%Promotores - %Detractores (escala 0-10)", unit: "puntos",
    domain: "customer", subdomain: "satisfaccion",
    interpretation: ">50: Excelente. 30-50: Bueno. 0-30: Regular. <0: Riesgo",
    thresholds: { excellent: 50, good: 30, moderate: 0, critical: -30, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-cust-002", "kpi-growth-004"],
    relatedRisks: ["riesgo-satisfaccion"],
    recommendedActions: ["Programa de voz del cliente", "Cerrar el loop con detractores"],
  },
  {
    id: "kpi-cust-002", name: "CSAT (Customer Satisfaction)", abbreviation: "CSAT",
    description: "Satisfacción del cliente con producto o servicio (escala 1-5)",
    formula: "Suma Puntajes / Número de Respuestas", unit: "/5",
    domain: "customer", subdomain: "satisfaccion",
    interpretation: ">4.5: Excelente. 4-4.5: Bueno. 3.5-4: Regular. <3.5: Riesgo",
    thresholds: { excellent: 4.5, good: 4, moderate: 3.5, critical: 3, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-cust-001", "kpi-cust-003"],
    relatedRisks: ["riesgo-satisfaccion"],
    recommendedActions: ["Encuestas post-servicio", "Análisis de comentarios abiertos"],
  },
  {
    id: "kpi-cust-003", name: "CES (Customer Effort Score)", abbreviation: "CES",
    description: "Qué tan fácil es para el cliente hacer negocios con la empresa",
    formula: "Suma Puntajes / Número de Respuestas (escala 1-5)", unit: "/5",
    domain: "customer", subdomain: "experiencia",
    interpretation: "<2: Excelente (bajo esfuerzo). 2-3: Bueno. 3-4: Regular. >4: Riesgo",
    thresholds: { excellent: 2, good: 3, moderate: 4, critical: 4.5, direction: "lower_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-cust-001", "kpi-cust-002"],
    relatedRisks: ["riesgo-experiencia"],
    recommendedActions: ["Simplificar procesos", "Automatizar autogestión del cliente"],
  },
  {
    id: "kpi-cust-004", name: "Tiempo Promedio de Resolución (TTR)", abbreviation: "TTR",
    description: "Tiempo promedio para resolver un ticket o reclamo de cliente",
    formula: "Suma Tiempos Resolución / Número de Tickets", unit: "horas",
    domain: "customer", subdomain: "soporte",
    interpretation: "<4h: Excelente. 4-24h: Bueno. 24-48h: Regular. >48h: Riesgo",
    thresholds: { excellent: 4, good: 24, moderate: 48, critical: 72, direction: "lower_is_better" },
    frequency: "weekly", applicableIndustries: ["Servicios", "Tecnología"],
    relatedKpis: ["kpi-cust-005", "kpi-cust-002"],
    relatedRisks: ["riesgo-satisfaccion"],
    recommendedActions: ["Automatizar respuestas frecuentes", "Mejorar capacitación del equipo"],
  },
  {
    id: "kpi-cust-005", name: "Tickets por Cliente", abbreviation: "TPC",
    description: "Número promedio de tickets de soporte por cliente activo",
    formula: "Tickets Totales / Clientes Activos", unit: "tickets/cliente",
    domain: "customer", subdomain: "soporte",
    interpretation: "<0.5: Excelente. 0.5-1: Bueno. 1-2: Regular. >2: Riesgo",
    thresholds: { excellent: 0.5, good: 1, moderate: 2, critical: 3, direction: "lower_is_better" },
    frequency: "monthly", applicableIndustries: ["Tecnología", "Servicios"],
    relatedKpis: ["kpi-cust-004"],
    relatedRisks: ["riesgo-producto"],
    recommendedActions: ["Mejorar producto para reducir incidencias", "Crear base de conocimiento"],
  },

  // ═══════════════════════════════════════════════════════════════
  // HR & TALENT
  // ═══════════════════════════════════════════════════════════════
  {
    id: "kpi-hr-001", name: "Rotación de Personal (Turnover)", abbreviation: "TURNOVER",
    description: "Porcentaje de empleados que dejan la empresa en un período",
    formula: "Salidas / Promedio Empleados", unit: "%",
    domain: "hr", subdomain: "retencion",
    interpretation: "<10%: Excelente. 10-20%: Normal. 20-30%: Alto. >30%: Crítico",
    thresholds: { excellent: 0.1, good: 0.2, moderate: 0.3, critical: 0.4, direction: "lower_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-hr-002", "kpi-hr-003"],
    relatedRisks: ["riesgo-talento"],
    recommendedActions: ["Entrevistas de salida", "Mejorar clima laboral", "Revisar compensaciones"],
  },
  {
    id: "kpi-hr-002", name: "Rotación Voluntaria", abbreviation: "TURN_VOL",
    description: "Empleados que renuncian voluntariamente (excluye despidos)",
    formula: "Renuncias / Promedio Empleados", unit: "%",
    domain: "hr", subdomain: "retencion",
    interpretation: "<5%: Excelente. 5-10%: Normal. 10-15%: Alerta. >15%: Riesgo",
    thresholds: { excellent: 0.05, good: 0.1, moderate: 0.15, critical: 0.2, direction: "lower_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-hr-001", "kpi-hr-004"],
    relatedRisks: ["riesgo-talento"],
    recommendedActions: ["Encuesta de clima laboral", "Plan de retención de talento clave"],
  },
  {
    id: "kpi-hr-003", name: "Tiempo Promedio de Contratación", abbreviation: "TIME2HIRE",
    description: "Días promedio desde apertura de vacante hasta aceptación de oferta",
    formula: "Suma Días Contratación / Número de Contrataciones", unit: "días",
    domain: "hr", subdomain: "reclutamiento",
    interpretation: "<30: Excelente. 30-60: Bueno. 60-90: Regular. >90: Lento",
    thresholds: { excellent: 30, good: 60, moderate: 90, critical: 120, direction: "lower_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-hr-005"],
    relatedRisks: ["riesgo-talento"],
    recommendedActions: ["Optimizar proceso de selección", "Mejorar employer branding"],
  },
  {
    id: "kpi-hr-004", name: "Clima Laboral (eNPS)", abbreviation: "ENPS",
    description: "Net Promoter Score interno: empleados recomendarían la empresa como lugar para trabajar",
    formula: "%Promotores - %Detractores", unit: "puntos",
    domain: "hr", subdomain: "clima",
    interpretation: ">30: Excelente. 10-30: Bueno. -10-10: Regular. <-10: Riesgo",
    thresholds: { excellent: 30, good: 10, moderate: -10, critical: -30, direction: "higher_is_better" },
    frequency: "quarterly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-hr-001", "kpi-hr-002"],
    relatedRisks: ["riesgo-talento"],
    recommendedActions: ["Plan de acción basado en encuesta", "Mejorar comunicación interna"],
  },
  {
    id: "kpi-hr-005", name: "Costo por Contratación", abbreviation: "CPH",
    description: "Costo total de reclutar y contratar un nuevo empleado",
    formula: "Costos Reclutamiento / Número de Contrataciones", unit: "USD",
    domain: "hr", subdomain: "reclutamiento",
    interpretation: "Varía según nivel del cargo y sector",
    thresholds: { good: 2000, moderate: 5000, critical: 10000, direction: "lower_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-hr-003"],
    relatedRisks: ["riesgo-costos"],
    recommendedActions: ["Optimizar proceso de selección", "Mejorar employer branding"],
  },
  {
    id: "kpi-hr-006", name: "Horas de Capacitación por Empleado", abbreviation: "HR_CAP",
    description: "Inversión en desarrollo del talento humano",
    formula: "Total Horas Capacitación / Número Empleados", unit: "horas/año",
    domain: "hr", subdomain: "desarrollo",
    interpretation: ">40: Excelente. 20-40: Bueno. 10-20: Regular. <10: Bajo",
    thresholds: { excellent: 40, good: 20, moderate: 10, critical: 5, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-hr-001", "kpi-hr-007"],
    relatedRisks: ["riesgo-talento"],
    recommendedActions: ["Implementar plan de desarrollo individual", "Crear biblioteca de cursos"],
  },
  {
    id: "kpi-hr-007", name: "Costo Laboral como % de Ingresos", abbreviation: "CL_ING",
    description: "Porcentaje de ingresos destinado a costos de personal",
    formula: "Costo Laboral Total / Ingresos Totales", unit: "%",
    domain: "hr", subdomain: "costos",
    interpretation: "20-30%: Normal servicios. 15-25%: Normal manufactura. >40%: Alerta",
    thresholds: { excellent: 0.2, good: 0.3, moderate: 0.4, critical: 0.5, direction: "range", rangeMin: 0.15, rangeMax: 0.3 },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-hr-001", "kpi-fin-021"],
    relatedRisks: ["riesgo-costos"],
    recommendedActions: ["Revisar productividad por empleado", "Automatizar procesos"],
  },
  {
    id: "kpi-hr-008", name: "Ausentismo Laboral", abbreviation: "AUSENT",
    description: "Porcentaje de horas perdidas por ausencias no programadas",
    formula: "Horas Ausencia / Horas Programadas", unit: "%",
    domain: "hr", subdomain: "asistencia",
    interpretation: "<3%: Excelente. 3-5%: Normal. 5-8%: Alerta. >8%: Riesgo",
    thresholds: { excellent: 0.03, good: 0.05, moderate: 0.08, critical: 0.12, direction: "lower_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-hr-001", "kpi-hr-004"],
    relatedRisks: ["riesgo-operativo"],
    recommendedActions: ["Programa de bienestar", "Revisar causas de ausentismo"],
  },

  // ═══════════════════════════════════════════════════════════════
  // TAX & COMPLIANCE
  // ═══════════════════════════════════════════════════════════════
  {
    id: "kpi-comp-001", name: "Carga Tributaria Efectiva", abbreviation: "CTE",
    description: "Porcentaje de ingresos pagado en impuestos totales",
    formula: "Total Impuestos Pagados / Ingresos", unit: "%",
    domain: "tax", subdomain: "carga",
    interpretation: "Comparar con benchmark sectorial. Desviación significativa = alerta",
    thresholds: { excellent: 0.08, good: 0.12, moderate: 0.15, critical: 0.2, direction: "range", rangeMin: 0.05, rangeMax: 0.15 },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-comp-002", "kpi-comp-003"],
    relatedRisks: ["riesgo-tributario"],
    recommendedActions: ["Revisar planificación tributaria", "Identificar beneficios fiscales aplicables"],
  },
  {
    id: "kpi-comp-002", name: "Tasa Efectiva de IR", abbreviation: "TIR_EFEC",
    description: "Tasa de impuesto a la renta realmente pagada vs utilidad",
    formula: "IR Causado / Utilidad Antes de Impuestos", unit: "%",
    domain: "tax", subdomain: "cumplimiento",
    interpretation: "25%: Tasa nominal. <25%: Beneficios fiscales. >25%: Posible ajuste",
    thresholds: { excellent: 0.2, good: 0.25, moderate: 0.3, critical: 0.35, direction: "lower_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-comp-001", "kpi-comp-003"],
    relatedRisks: ["riesgo-tributario"],
    recommendedActions: ["Revisar beneficios tributarios aplicados", "Evaluar reinversión de utilidades"],
  },
  {
    id: "kpi-comp-003", name: "Cumplimiento de Declaraciones", abbreviation: "CUMP_DEC",
    description: "Porcentaje de declaraciones tributarias presentadas a tiempo",
    formula: "Declaraciones a Tiempo / Total Declaraciones", unit: "%",
    domain: "compliance", subdomain: "cumplimiento",
    interpretation: "100%: Excelente. 95-99%: Bueno. 85-95%: Regular. <85%: Riesgo",
    thresholds: { excellent: 1, good: 0.95, moderate: 0.85, critical: 0.7, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-comp-004"],
    relatedRisks: ["riesgo-tributario", "riesgo-multas"],
    recommendedActions: ["Implementar calendario tributario", "Automatizar recordatorios"],
  },
  {
    id: "kpi-comp-004", name: "Pasivo Tributario / Ingresos", abbreviation: "PAS_TRIB",
    description: "Proporción de deuda tributaria pendiente sobre ingresos",
    formula: "Pasivo Tributario Total / Ingresos", unit: "%",
    domain: "tax", subdomain: "riesgo",
    interpretation: "<5%: Normal. 5-10%: Alerta. 10-20%: Riesgo. >20%: Crítico",
    thresholds: { excellent: 0.05, good: 0.1, moderate: 0.2, critical: 0.3, direction: "lower_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-comp-001", "kpi-comp-003"],
    relatedRisks: ["riesgo-tributario"],
    recommendedActions: ["Regularizar pasivos tributarios", "Negociar facilidades de pago"],
  },

  // ═══════════════════════════════════════════════════════════════
  // DIGITAL & TECHNOLOGY
  // ═══════════════════════════════════════════════════════════════
  {
    id: "kpi-dig-001", name: "Madurez Digital", abbreviation: "MAD_DIG",
    description: "Nivel de madurez digital de la organización (escala 1-5)",
    formula: "Evaluación multidimensional basada en adopción tecnológica, automatización y cultura digital", unit: "nivel",
    domain: "digital", subdomain: "madurez",
    interpretation: "5: Transformado. 4: Avanzado. 3: Integrado. 2: Emergente. 1: Analógico",
    thresholds: { excellent: 4, good: 3, moderate: 2, critical: 1, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-dig-002", "kpi-dig-003"],
    relatedRisks: ["riesgo-digital"],
    recommendedActions: ["Diagnóstico de madurez digital", "Plan de transformación digital"],
  },
  {
    id: "kpi-dig-002", name: "Automatización de Procesos", abbreviation: "AUTO_PROC",
    description: "Porcentaje de procesos críticos automatizados",
    formula: "Procesos Automatizados / Procesos Totales", unit: "%",
    domain: "digital", subdomain: "automatizacion",
    interpretation: ">70%: Avanzado. 40-70%: En desarrollo. <40%: Incipiente",
    thresholds: { excellent: 0.7, good: 0.4, moderate: 0.2, critical: 0.1, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-dig-001", "kpi-dig-003"],
    relatedRisks: ["riesgo-digital"],
    recommendedActions: ["Identificar procesos con mayor ROI de automatización", "Implementar RPA"],
  },
  {
    id: "kpi-dig-003", name: "Ciberseguridad - Índice de Protección", abbreviation: "CYBER",
    description: "Nivel de madurez en ciberseguridad basado en controles implementados",
    formula: "Controles Implementados / Controles Requeridos", unit: "%",
    domain: "digital", subdomain: "seguridad",
    interpretation: ">90%: Protegido. 70-90%: Adecuado. 50-70%: En riesgo. <50%: Vulnerable",
    thresholds: { excellent: 0.9, good: 0.7, moderate: 0.5, critical: 0.3, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-dig-004"],
    relatedRisks: ["riesgo-ciberseguridad"],
    recommendedActions: ["Implementar ISO 27001", "Auditoría de seguridad", "Capacitar empleados"],
  },
  {
    id: "kpi-dig-004", name: "Uptime de Sistemas Críticos", abbreviation: "UPTIME",
    description: "Disponibilidad de sistemas de TI críticos para la operación",
    formula: "Tiempo Operativo / Tiempo Total", unit: "%",
    domain: "digital", subdomain: "infraestructura",
    interpretation: "99.9%+ (3 nueves): Excelente. 99% (2 nueves): Bueno. 95%: Regular. <90%: Riesgo",
    thresholds: { excellent: 99.9, good: 99, moderate: 95, critical: 90, direction: "higher_is_better" },
    frequency: "daily", applicableIndustries: ["*"],
    relatedKpis: ["kpi-dig-003"],
    relatedRisks: ["riesgo-operativo", "riesgo-TI"],
    recommendedActions: ["Implementar monitoreo 24/7", "Contingencia y disaster recovery"],
  },

  // ═══════════════════════════════════════════════════════════════
  // ESG & SUSTAINABILITY
  // ═══════════════════════════════════════════════════════════════
  {
    id: "kpi-esg-001", name: "Huella de Carbono", abbreviation: "CO2",
    description: "Emisiones de CO2 equivalente generadas por la operación",
    formula: "Toneladas CO2e / Año", unit: "tCO2e/año",
    domain: "esg", subdomain: "ambiental",
    interpretation: "Decreciente = mejora. Comparar contra benchmark sectorial",
    thresholds: { excellent: 100, good: 500, moderate: 1000, critical: 5000, direction: "lower_is_better" },
    frequency: "monthly", applicableIndustries: ["Manufactura", "Logística", "Agricultura"],
    relatedKpis: ["kpi-esg-002", "kpi-esg-003"],
    relatedRisks: ["riesgo-ambiental"],
    recommendedActions: ["Implementar eficiencia energética", "Compensar emisiones"],
  },
  {
    id: "kpi-esg-002", name: "Consumo Energético por Unidad", abbreviation: "ENERGY_U",
    description: "Energía consumida por unidad de producción",
    formula: "kWh Consumidos / Unidades Producidas", unit: "kWh/unidad",
    domain: "esg", subdomain: "ambiental",
    interpretation: "Decreciente = mejora de eficiencia energética",
    thresholds: { good: 50, moderate: 100, critical: 200, direction: "lower_is_better" },
    frequency: "monthly", applicableIndustries: ["Manufactura"],
    relatedKpis: ["kpi-esg-001", "kpi-ops-005"],
    relatedRisks: ["riesgo-ambiental", "riesgo-costos"],
    recommendedActions: ["Auditoría energética", "Implementar energías renovables"],
  },
  {
    id: "kpi-esg-003", name: "Diversidad de Género", abbreviation: "DIVERSIDAD",
    description: "Porcentaje de mujeres en posiciones de liderazgo",
    formula: "Mujeres en Liderazgo / Total Posiciones Liderazgo", unit: "%",
    domain: "esg", subdomain: "social",
    interpretation: ">40%: Excelente. 30-40%: Bueno. 20-30%: Regular. <20%: Bajo",
    thresholds: { excellent: 0.4, good: 0.3, moderate: 0.2, critical: 0.1, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-esg-004"],
    relatedRisks: ["riesgo-reputacional"],
    recommendedActions: ["Programa de mentoring", "Política de diversidad e inclusión"],
  },
  {
    id: "kpi-esg-004", name: "Inversión Social", abbreviation: "INV_SOCIAL",
    description: "Inversión en programas de responsabilidad social como % de utilidades",
    formula: "Gasto Social / Utilidad Neta", unit: "%",
    domain: "esg", subdomain: "social",
    interpretation: ">3%: Comprometido. 1-3%: Participativo. <1%: Básico",
    thresholds: { excellent: 0.05, good: 0.03, moderate: 0.01, critical: 0, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-esg-003"],
    relatedRisks: ["riesgo-reputacional"],
    recommendedActions: ["Implementar programa de RSE", "Medir impacto social de operaciones"],
  },

  // ═══════════════════════════════════════════════════════════════
  // PROJECT MANAGEMENT
  // ═══════════════════════════════════════════════════════════════
  {
    id: "kpi-proj-001", name: "SPI (Schedule Performance Index)", abbreviation: "SPI",
    description: "Eficiencia del cronograma del proyecto (Earned Value Management)",
    formula: "EV (Earned Value) / PV (Planned Value)", unit: "índice",
    domain: "project", subdomain: "cronograma",
    interpretation: ">1: Adelantado. =1: En plan. <1: Atrasado",
    thresholds: { excellent: 1.1, good: 1, moderate: 0.9, critical: 0.8, direction: "higher_is_better" },
    frequency: "weekly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-proj-002", "kpi-proj-003"],
    relatedRisks: ["riesgo-proyecto"],
    recommendedActions: ["Revisar ruta crítica", "Asignar más recursos si SPI < 0.9"],
  },
  {
    id: "kpi-proj-002", name: "CPI (Cost Performance Index)", abbreviation: "CPI",
    description: "Eficiencia del presupuesto del proyecto (Earned Value Management)",
    formula: "EV (Earned Value) / AC (Actual Cost)", unit: "índice",
    domain: "project", subdomain: "presupuesto",
    interpretation: ">1: Por debajo de presupuesto. =1: En presupuesto. <1: Sobrepresupuesto",
    thresholds: { excellent: 1.1, good: 1, moderate: 0.9, critical: 0.8, direction: "higher_is_better" },
    frequency: "weekly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-proj-001", "kpi-proj-003"],
    relatedRisks: ["riesgo-proyecto"],
    recommendedActions: ["Revisar variaciones de costos", "Controlar gastos no planificados"],
  },
  {
    id: "kpi-proj-003", name: "% de Proyectos a Tiempo", abbreviation: "PROJ_TIME",
    description: "Porcentaje de proyectos completados dentro del plazo planificado",
    formula: "Proyectos a Tiempo / Total Proyectos Completados", unit: "%",
    domain: "project", subdomain: "cumplimiento",
    interpretation: ">90%: Excelente. 70-90%: Bueno. 50-70%: Regular. <50%: Riesgo",
    thresholds: { excellent: 0.9, good: 0.7, moderate: 0.5, critical: 0.3, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-proj-001", "kpi-proj-004"],
    relatedRisks: ["riesgo-proyecto"],
    recommendedActions: ["Mejorar estimación inicial", "Implementar metodología ágil"],
  },
  {
    id: "kpi-proj-004", name: "% de Proyectos en Presupuesto", abbreviation: "PROJ_BUDG",
    description: "Porcentaje de proyectos completados dentro del presupuesto asignado",
    formula: "Proyectos en Presupuesto / Total Proyectos", unit: "%",
    domain: "project", subdomain: "presupuesto",
    interpretation: ">90%: Excelente. 75-90%: Bueno. 60-75%: Regular. <60%: Riesgo",
    thresholds: { excellent: 0.9, good: 0.75, moderate: 0.6, critical: 0.4, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-proj-002", "kpi-proj-003"],
    relatedRisks: ["riesgo-proyecto"],
    recommendedActions: ["Revisar estimaciones iniciales", "Mejorar control de costos del proyecto"],
  },

  // ═══════════════════════════════════════════════════════════════
  // INNOVATION
  // ═══════════════════════════════════════════════════════════════
  {
    id: "kpi-inn-001", name: "Inversión en I+D como % de Ingresos", abbreviation: "ID_ING",
    description: "Porcentaje de ingresos reinvertido en investigación y desarrollo",
    formula: "Gasto I+D / Ingresos Totales", unit: "%",
    domain: "innovation", subdomain: "inversion",
    interpretation: ">5%: Alta innovación. 2-5%: Moderada. 1-2%: Baja. <1%: Mínima",
    thresholds: { excellent: 0.05, good: 0.02, moderate: 0.01, critical: 0, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["Tecnología", "Manufactura", "Farmacéutica"],
    relatedKpis: ["kpi-inn-002", "kpi-inn-003"],
    relatedRisks: ["riesgo-innovacion"],
    recommendedActions: ["Crear fondo de innovación", "Establecer partnerships con universidades"],
  },
  {
    id: "kpi-inn-002", name: "Nuevos Productos Lanzados", abbreviation: "NUEVOS_PROD",
    description: "Número de nuevos productos o servicios lanzados al mercado en el período",
    formula: "Conteo de lanzamientos", unit: "unidades",
    domain: "innovation", subdomain: "resultados",
    interpretation: ">5/año: Alta innovación. 2-5: Moderada. 1: Baja. 0: Sin innovación",
    thresholds: { excellent: 5, good: 3, moderate: 1, critical: 0, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-inn-001", "kpi-inn-003"],
    relatedRisks: ["riesgo-innovacion"],
    recommendedActions: ["Fomentar cultura de innovación", "Establecer proceso de ideación estructurado"],
  },
  {
    id: "kpi-inn-003", name: "Ingresos de Nuevos Productos", abbreviation: "ING_NVO",
    description: "Porcentaje de ingresos provenientes de productos lanzados en los últimos 3 años",
    formula: "Ingresos Nuevos Productos / Ingresos Totales", unit: "%",
    domain: "innovation", subdomain: "resultados",
    interpretation: ">20%: Saludable. 10-20%: Moderado. 5-10%: Bajo. <5%: Estancamiento",
    thresholds: { excellent: 0.2, good: 0.1, moderate: 0.05, critical: 0, direction: "higher_is_better" },
    frequency: "monthly", applicableIndustries: ["*"],
    relatedKpis: ["kpi-inn-001", "kpi-inn-002"],
    relatedRisks: ["riesgo-innovacion"],
    recommendedActions: ["Invertir en I+D", "Monitorear pipeline de innovación"],
  },
]

export const kpiMap = new Map(kpiCatalog.map((k) => [k.id, k]))
export const kpiByDomain = new Map<KpiDomain, KPIDefinition[]>()
for (const kpi of kpiCatalog) {
  const arr = kpiByDomain.get(kpi.domain) || []
  arr.push(kpi)
  kpiByDomain.set(kpi.domain, arr)
}

export const kpiDomains: { domain: KpiDomain; label: string; count: number }[] = [
  { domain: "liquidity", label: "Liquidez", count: 0 },
  { domain: "solvency", label: "Solvencia", count: 0 },
  { domain: "profitability", label: "Rentabilidad", count: 0 },
  { domain: "efficiency", label: "Eficiencia", count: 0 },
  { domain: "growth", label: "Crecimiento", count: 0 },
  { domain: "financial", label: "Financieros", count: 0 },
  { domain: "operational", label: "Operativos", count: 0 },
  { domain: "commercial", label: "Comerciales", count: 0 },
  { domain: "marketing", label: "Marketing", count: 0 },
  { domain: "customer", label: "Cliente", count: 0 },
  { domain: "hr", label: "RRHH", count: 0 },
  { domain: "tax", label: "Tributarios", count: 0 },
  { domain: "compliance", label: "Cumplimiento", count: 0 },
  { domain: "digital", label: "Digital/TI", count: 0 },
  { domain: "esg", label: "ESG", count: 0 },
  { domain: "project", label: "Proyectos", count: 0 },
  { domain: "innovation", label: "Innovación", count: 0 },
  { domain: "quality", label: "Calidad", count: 0 },
]
for (const d of kpiDomains) {
  d.count = kpiByDomain.get(d.domain)?.length || 0
}
