import type { KnowledgeEntry } from "./types"

export const knowledgeBase: KnowledgeEntry[] = [
  // ── Normativa Ecuatoriana ──
  {
    id: "kb-ec-001",
    type: "regulation",
    title: "Ley de Régimen Tributario Interno (LRTI)",
    description: "Marco legal principal del sistema tributario ecuatoriano. Establece impuesto a la renta, IVA, ICE y régimen de retenciones.",
    category: "tax",
    jurisdiction: "Ecuador",
    source: "SRI — Servicio de Rentas Internas",
    url: "https://www.sri.gob.ec/ley-de-regimen-tributario-interno",
    tags: ["tributario", "ecuador", "lrti", "sri", "impuesto-renta", "iva"],
    content: "La LRTI regula los impuestos internos del Ecuador. Tasa de IR: 25% para sociedades, tabla progresiva para personas. IVA: 12% general, 0% para exportaciones y productos básicos. ICE: aplica a bienes y servicios específicos. Retenciones en la fuente: 1%, 2%, 8%, 10% según el tipo de renta.",
  },
  {
    id: "kb-ec-002",
    type: "regulation",
    title: "Normas Internacionales de Información Financiera (NIIF)",
    description: "Estándares contables adoptados en Ecuador para preparación de estados financieros.",
    category: "compliance",
    jurisdiction: "Ecuador",
    source: "Superintendencia de Compañías",
    url: "https://www.supercias.gob.ec",
    tags: ["contabilidad", "niif", "ifrs", "estados-financieros"],
    content: "Ecuador adoptó NIIF/NIIF para PYMES desde 2010. Las compañías deben presentar estados financieros bajo NIIF. Las PYMES pueden usar NIIF para PYMES si cumplen criterios de: ingresos < $5M, activos < $4M, empleados < 200.",
  },
  {
    id: "kb-ec-003",
    type: "regulation",
    title: "Código Orgánico de la Producción, Comercio e Inversiones (COPCI)",
    description: "Regula incentivos tributarios para sectores prioritarios, zonas francas y desarrollo productivo.",
    category: "tax",
    jurisdiction: "Ecuador",
    source: "Ministerio de Producción",
    tags: ["produccion", "incentivos", "copol", "zonas-francas"],
    content: "El COPCI establece incentivos: exoneración de IR por 5 años para inversiones nuevas en sectores prioritarios, reducción de 10 puntos en IR para empresas que reinviertan utilidades, beneficios para zonas francas y regímenes especiales.",
  },
  {
    id: "kb-ec-004",
    type: "regulation",
    title: "Código de Trabajo Ecuatoriano",
    description: "Regula relaciones laborales: contratos, jornada, remuneraciones, beneficios sociales y terminación.",
    category: "legal",
    jurisdiction: "Ecuador",
    source: "Ministerio de Trabajo",
    tags: ["laboral", "trabajo", "contratos", "beneficios"],
    content: "Jornada máxima: 8h diarias / 40h semanales. Salario básico unificado (SBU) 2026: $500. Décimo tercero (bonificación navideña): 12ava parte de ingresos anuales. Décimo cuarto: 1 SBU. Fondos de reserva: 8.33% mensual después del 1er año. Utilidades: 15% de ganancias (10% para trabajadores, 5% para cargas familiares).",
  },
  {
    id: "kb-ec-005",
    type: "regulation",
    title: "Ley Orgánica de Economía Popular y Solidaria (LOEPS)",
    description: "Regula cooperativas, asociaciones y organizaciones del sector solidario.",
    category: "legal",
    jurisdiction: "Ecuador",
    source: "SEPS — Superintendencia de Economía Popular y Solidaria",
    tags: ["economia-solidaria", "cooperativas", "seps"],
    content: "Regula cooperativas de ahorro y crédito, asociaciones, y organizaciones del sector solidario. Las cooperativas deben mantener: solvencia patrimonial mínima del 12% de activos ponderados, liquidez mínima del 14% de depósitos, límites de concentración de crédito.",
  },
  // ── Metodologías ──
  {
    id: "kb-met-001",
    type: "methodology",
    title: "Análisis Dupont",
    description: "Metodología de descomposición del ROE en sus componentes: margen, rotación y apalancamiento.",
    category: "profitability",
    tags: ["dupont", "roe", "analisis-financiero"],
    content: "ROE = (Net Income / Revenue) × (Revenue / Total Assets) × (Total Assets / Equity) = Margen Neto × Rotación de Activos × Apalancamiento. Permite identificar qué componente impulsa o limita la rentabilidad.",
  },
  {
    id: "kb-met-002",
    type: "methodology",
    title: "Análisis FODA / SWOT",
    description: "Herramienta de planeación estratégica que evalúa Fortalezas, Oportunidades, Debilidades y Amenazas.",
    category: "strategic",
    tags: ["foda", "swot", "estrategia"],
    content: "Fortalezas: capacidades internas que dan ventaja. Debilidades: limitaciones internas. Oportunidades: factores externos aprovechables. Amenazas: factores externos que pueden afectar. Se recomienda realizar FODA cruzado: FO (estrategias ofensivas), DO (mejora), FA (defensivas), DA (supervivencia).",
  },
  {
    id: "kb-met-003",
    type: "methodology",
    title: "Modelo DCF (Flujo de Caja Descontado)",
    description: "Metodología de valoración basada en proyección de flujos de caja futuros descontados a valor presente.",
    category: "profitability",
    tags: ["dcf", "valoracion", "flujo-caja", "wacc"],
    content: "Valor = Σ FCF_t / (1+WACC)^t. Pasos: (1) Proyectar FCF 5-10 años, (2) Calcular valor terminal (Gordon), (3) Descontar con WACC, (4) Restar deuda neta. WACC = E/(D+E) × Ke + D/(D+E) × Kd × (1-t).",
  },
  {
    id: "kb-met-004",
    type: "methodology",
    title: "OKR (Objectives and Key Results)",
    description: "Metodología de gestión de objetivos que conecta estrategia con ejecución.",
    category: "strategic",
    tags: ["okr", "objetivos", "resultados-clave", "gestion"],
    content: "Objetivo: qué se quiere lograr, cualitativo e inspirador. Key Results: cómo se mide el progreso, cuantitativos y medibles. Cada objetivo debe tener 3-5 KRs. Los KRs deben ser ambiciosos (70% completado = éxito) y tener propietario asignado.",
  },
  // ── Benchmarks por Industria ──
  {
    id: "kb-bm-001",
    type: "benchmark",
    title: "Benchmark de Liquidez por Sector (Ecuador)",
    description: "Ratios de liquidez promedio por sector económico en Ecuador.",
    category: "liquidity",
    jurisdiction: "Ecuador",
    tags: ["benchmark", "liquidez", "sector"],
    content: "Comercio: 1.3-1.8. Manufactura: 1.5-2.0. Construcción: 1.2-1.5. Servicios: 1.4-1.9. Agricultura: 1.6-2.2. Tecnología: 1.8-2.5. Una empresa con liquidez muy superior al promedio del sector puede tener exceso de activos circulantes ociosos.",
  },
  {
    id: "kb-bm-002",
    type: "benchmark",
    title: "Benchmark de Endeudamiento por Sector (Ecuador)",
    description: "Niveles de endeudamiento promedio por sector.",
    category: "solvency",
    jurisdiction: "Ecuador",
    tags: ["benchmark", "endeudamiento", "sector"],
    content: "Comercio: D/E 1.5-2.5. Manufactura: 1.0-1.8. Construcción: 2.0-3.5. Servicios: 0.8-1.5. Agricultura: 1.0-1.8. Tecnología: 0.3-0.8. El endeudamiento óptimo depende del sector y etapa del ciclo económico.",
  },
  {
    id: "kb-bm-003",
    type: "benchmark",
    title: "Benchmark de Rentabilidad (PYME Ecuador)",
    description: "Márgenes de rentabilidad promedio para PYMES ecuatorianas.",
    category: "profitability",
    jurisdiction: "Ecuador",
    tags: ["benchmark", "rentabilidad", "pyme"],
    content: "Margen Bruto promedio: 35-55%. Margen Operativo: 8-18%. Margen Neto: 3-12%. ROE: 8-20%. ROA: 4-10%. PYMES exitosas suelen tener margen neto >10% y ROE >15%. Márgenes bajo 3% indican alerta.",
  },
  // ── Best Practices ──
  {
    id: "kb-bp-001",
    type: "best_practice",
    title: "Gestión de Capital de Trabajo",
    description: "Prácticas recomendadas para optimizar el ciclo de conversión de efectivo.",
    category: "efficiency",
    tags: ["capital-trabajo", "mejores-practicas", "ccc"],
    content: "Ciclo de Conversión de Efectivo (CCC) = Días Inventario + Días Cuentas por Cobrar - Días Cuentas por Pagar. Meta: CCC < 60 días. Prácticas: (1) Negociar plazos con proveedores, (2) Implementar descuentos por pronto pago, (3) Segmentar clientes por riesgo y ajustar políticas de crédito, (4) Mantener inventarios ajustados con sistema just-in-time.",
  },
  {
    id: "kb-bp-002",
    type: "best_practice",
    title: "Planificación Tributaria Efectiva",
    description: "Estrategias legales para optimizar la carga tributaria.",
    category: "tax",
    tags: ["tributario", "planificacion", "mejores-practicas"],
    content: "Estrategias permitidas: (1) Reinversión de utilidades (reducción 10% IR), (2) Beneficios de zonas francas y sectores prioritarios, (3) Deducción de gastos necesarios, (4) Uso de convenios de doble tributación, (5) Crédito tributario por IVA en activos fijos. Importante: la planificación tributaria no es evasión. Toda estrategia debe tener sustento legal.",
  },
  {
    id: "kb-bp-003",
    type: "best_practice",
    title: "Implementación de OKRs",
    description: "Guía práctica para implementar OKRs en PYMES.",
    category: "strategic",
    tags: ["okr", "implementacion", "gestion"],
    content: "Fase 1 (Mes 1-2): Capacitar equipo, definir objetivos estratégicos, establecer KRs. Fase 2 (Mes 3): Implementar en un área piloto. Fase 3 (Mes 4-6): Extender a toda la organización. Recomendaciones: máximo 3 objetivos por ciclo, reuniones semanales de check-in, KRs deben ser medibles objetivamente, celebrar progreso (no solo resultados).",
  },
]
