import type { RecommendationPattern } from "./types"

export const recommendationPatterns: RecommendationPattern[] = [
  {
    id: "rec-liq-001",
    name: "Mejora de Liquidez",
    trigger: "liquidez_corriente_baja",
    priority: "urgent",
    category: "liquidity",
    template: "Implementar plan de mejora de liquidez: (1) Renegociar plazos con proveedores, (2) Acelerar cobro de cartera, (3) Reducir inventarios de lenta rotación, (4) Evaluar líneas de crédito corto plazo.",
    conditions: ["current_ratio < 1.0", "quick_ratio < 0.5"],
    examples: ["Cliente con liquidez de 0.8 — se recomendó factoring y reducción de inventarios, mejorando a 1.3 en 3 meses"],
  },
  {
    id: "rec-liq-002",
    name: "Optimización de Capital de Trabajo",
    trigger: "capital_trabajo_negativo",
    priority: "urgent",
    category: "liquidity",
    template: "Optimizar capital de trabajo: (1) Revisar políticas de crédito, (2) Implementar descuento por pronto pago, (3) Consolidar deudas corto plazo, (4) Evaluar ciclo de conversión de efectivo.",
    conditions: ["working_capital < 0"],
    examples: ["Empresa con capital de trabajo negativo de -$50K — se implementó descuento 2/10 neto 60, recuperando positivo en 45 días"],
  },
  {
    id: "rec-sol-001",
    name: "Desapalancamiento",
    trigger: "endeudamiento_alto",
    priority: "high",
    category: "solvency",
    template: "Reducir nivel de endeudamiento: (1) Refinanciar deuda de alto costo, (2) Evaluar venta de activos no estratégicos, (3) Capitalización de utilidades, (4) Revisar política de dividendos.",
    conditions: ["debt_to_equity > 2.0", "interest_coverage < 1.5"],
    examples: ["Cliente con D/E de 3.5 — se refinanció deuda bancaria de 18% a 11%, reduciendo D/E a 2.1 en 6 meses"],
  },
  {
    id: "rec-sol-002",
    name: "Reestructuración de Deuda",
    trigger: "cobertura_intereses_critica",
    priority: "urgent",
    category: "solvency",
    template: "Reestructurar deuda urgentemente: (1) Negociar períodos de gracia, (2) Consolidar pasivos financieros, (3) Evaluar conversión de deuda en capital, (4) Buscar líneas de financiamiento blandas.",
    conditions: ["interest_coverage < 1.0"],
    examples: ["Empresa no cubría intereses (0.8) — se reestructuró deuda a 5 años con 1 año de gracia, recuperando cobertura a 2.1"],
  },
  {
    id: "rec-prof-001",
    name: "Mejora de Rentabilidad",
    trigger: "margen_bajo",
    priority: "high",
    category: "profitability",
    template: "Mejorar rentabilidad: (1) Revisar estructura de costos y gastos, (2) Analizar rentabilidad por producto/línea, (3) Optimizar precios, (4) Reducir gastos no operativos.",
    conditions: ["net_margin < 0.05", "roe < 0.08"],
    examples: ["Margen neto de 2.5% — se identificaron 3 líneas no rentables (18% de ingresos), se descontinuaron y margen subió a 6.8%"],
  },
  {
    id: "rec-prof-002",
    name: "Creación de Valor",
    trigger: "roe_menor_wacc",
    priority: "high",
    category: "profitability",
    template: "Recuperar creación de valor: (1) Evaluar proyectos con ROE > WACC, (2) Desinvertir en unidades que destruyen valor, (3) Optimizar estructura de capital, (4) Mejorar eficiencia operativa.",
    conditions: ["roe < wacc"],
    examples: ["ROE de 6% vs WACC de 11% — se vendió unidad de negocio no estratégica con ROE de 2%, mejorando ROE consolidado a 9.5%"],
  },
  {
    id: "rec-eff-001",
    name: "Eficiencia Operativa",
    trigger: "rotacion_baja",
    priority: "medium",
    category: "efficiency",
    template: "Mejorar eficiencia operativa: (1) Revisar procesos productivos, (2) Implementar mejoras lean, (3) Automatizar procesos repetitivos, (4) Optimizar cadena de suministro.",
    conditions: ["asset_turnover < 1.0", "operating_margin < industry_benchmark * 0.7"],
    examples: ["Rotación de activos de 0.6 — se implementó sistema ERP y reingeniería de procesos, mejorando a 1.2 en 8 meses"],
  },
  {
    id: "rec-eff-002",
    name: "Gestión de Cartera",
    trigger: "dias_cobro_elevados",
    priority: "high",
    category: "efficiency",
    template: "Mejorar gestión de cartera: (1) Segmentar clientes por riesgo, (2) Implementar políticas de cobro diferenciadas, (3) Automatizar recordatorios de pago, (4) Evaluar factoring selectivo.",
    conditions: ["days_sales_outstanding > 90"],
    examples: ["DSO de 112 días — se implementó scoring de clientes y cobro automatizado, reduciendo a 58 días en 4 meses"],
  },
  {
    id: "rec-eff-003",
    name: "Optimización de Inventarios",
    trigger: "rotacion_inventario_baja",
    priority: "medium",
    category: "efficiency",
    template: "Optimizar gestión de inventarios: (1) Implementar sistema ABC, (2) Revisar lotes económicos de compra, (3) Identificar inventario obsoleto, (4) Mejorar pronóstico de demanda.",
    conditions: ["inventory_turnover < 3.0"],
    examples: ["Rotación de inventario de 2.1 — se implementó clasificación ABC y se eliminaron SKUs obsoletos, mejorando a 5.4"],
  },
  {
    id: "rec-str-001",
    name: "Plan Estratégico",
    trigger: "crecimiento_declive",
    priority: "high",
    category: "strategic",
    template: "Desarrollar plan estratégico: (1) Análisis FODA actualizado, (2) Definir ventaja competitiva, (3) Establecer objetivos 3-5 años, (4) Crear roadmap de iniciativas, (5) Definir KPIs y metas.",
    conditions: ["revenue_growth < inflation_rate", "market_share_declining"],
    examples: ["Empresa con 2 años de decrecimiento real — se definió nueva estrategia de nicho, recuperando crecimiento positivo en 12 meses"],
  },
  {
    id: "rec-comp-001",
    name: "Regularización Tributaria",
    trigger: "inconsistencia_tributaria",
    priority: "urgent",
    category: "compliance",
    template: "Regularizar situación tributaria: (1) Revisar declaraciones de últimos 4 años, (2) Identificar diferencias con estados financieros, (3) Preparar plan de regularización, (4) Evaluar beneficios de cumplimiento voluntario.",
    conditions: ["tax_gap > 0.05"],
    examples: ["Discrepancia del 12% entre ingresos contables y tributarios — se realizó declaración sustitutiva y se evitó multa del 100%"],
  },
  {
    id: "rec-comp-002",
    name: "Cumplimiento Normativo",
    trigger: "brechas_cumplimiento",
    priority: "high",
    category: "compliance",
    template: "Cerrar brechas de cumplimiento: (1) Identificar normativas aplicables no cumplidas, (2) Priorizar por riesgo y materialidad, (3) Asignar responsables y fechas, (4) Implementar controles internos.",
    conditions: ["compliance_score < 70"],
    examples: ["Score de cumplimiento de 45% — se implementó matriz de cumplimiento con 32 controles, subiendo a 85% en 6 meses"],
  },
  {
    id: "rec-risk-001",
    name: "Mitigación de Riesgo de Concentración",
    trigger: "alta_concentracion",
    priority: "high",
    category: "market",
    template: "Reducir concentración: (1) Establecer límite máximo por cliente (ej: 20% ingresos), (2) Desarrollar plan de diversificación comercial, (3) Identificar segmentos de mercado adyacentes, (4) Evaluar alianzas estratégicas.",
    conditions: ["client_concentration > 0.5"],
    examples: ["Cliente A representa 65% de ingresos — se desarrollaron 3 nichos nuevos, reduciendo concentración a 38% en 18 meses"],
  },
  {
    id: "rec-dig-001",
    name: "Transformación Digital",
    trigger: "madurez_digital_baja",
    priority: "medium",
    category: "digital",
    template: "Impulsar transformación digital: (1) Diagnosticar madurez digital actual, (2) Identificar procesos con mayor ROI de digitalización, (3) Implementar piloto en área crítica, (4) Escalar basado en resultados.",
    conditions: ["digital_maturity < 3"],
    examples: ["Madurez digital nivel 2 — se digitalizó proceso de facturación y cobranza, reduciendo DSO de 75 a 45 días"],
  },
  {
    id: "rec-mgmt-001",
    name: "Gobierno Corporativo",
    trigger: "debilidad_gobierno",
    priority: "high",
    category: "management",
    template: "Fortalecer gobierno corporativo: (1) Definir estructura organizativa clara, (2) Establecer comités de dirección, (3) Implementar políticas de control interno, (4) Separar funciones clave.",
    conditions: ["management_score < 50"],
    examples: ["Empresa familiar sin separación de roles — se implementó estructura con CEO, CFO y COO independientes, mejorando score de 35 a 72"],
  },
]
