import type { RiskThreshold } from "./types"

export const riskThresholds: RiskThreshold[] = [
  {
    id: "risk-liq-001",
    name: "Liquidez Corriente",
    category: "liquidity",
    indicator: "current_ratio",
    low: 2.0,
    medium: 1.5,
    high: 1.0,
    critical: 0.5,
    unit: "veces",
    inverse: true,
  },
  {
    id: "risk-liq-002",
    name: "Prueba Ácida",
    category: "liquidity",
    indicator: "quick_ratio",
    low: 1.5,
    medium: 1.0,
    high: 0.5,
    critical: 0.3,
    unit: "veces",
    inverse: true,
  },
  {
    id: "risk-liq-003",
    name: "Capital de Trabajo",
    category: "liquidity",
    indicator: "working_capital",
    low: 100000,
    medium: 50000,
    high: 0,
    critical: -50000,
    unit: "USD",
    inverse: true,
  },
  {
    id: "risk-sol-001",
    name: "Endeudamiento Patrimonial",
    category: "solvency",
    indicator: "debt_to_equity",
    low: 0.5,
    medium: 1.0,
    high: 2.0,
    critical: 3.0,
    unit: "veces",
    inverse: false,
  },
  {
    id: "risk-sol-002",
    name: "Endeudamiento de Activos",
    category: "solvency",
    indicator: "debt_to_assets",
    low: 0.3,
    medium: 0.5,
    high: 0.7,
    critical: 0.85,
    unit: "veces",
    inverse: false,
  },
  {
    id: "risk-sol-003",
    name: "Cobertura de Intereses",
    category: "solvency",
    indicator: "interest_coverage",
    low: 5.0,
    medium: 3.0,
    high: 1.5,
    critical: 1.0,
    unit: "veces",
    inverse: true,
  },
  {
    id: "risk-prof-001",
    name: "Margen Neto",
    category: "profitability",
    indicator: "net_margin",
    low: 0.15,
    medium: 0.08,
    high: 0.03,
    critical: 0.0,
    unit: "porcentaje",
    inverse: true,
  },
  {
    id: "risk-prof-002",
    name: "ROE",
    category: "profitability",
    indicator: "roe",
    low: 0.20,
    medium: 0.12,
    high: 0.05,
    critical: 0.0,
    unit: "porcentaje",
    inverse: true,
  },
  {
    id: "risk-prof-003",
    name: "ROA",
    category: "profitability",
    indicator: "roa",
    low: 0.10,
    medium: 0.05,
    high: 0.02,
    critical: 0.0,
    unit: "porcentaje",
    inverse: true,
  },
  {
    id: "risk-eff-001",
    name: "Rotación de Activos",
    category: "efficiency",
    indicator: "asset_turnover",
    low: 2.0,
    medium: 1.0,
    high: 0.5,
    critical: 0.3,
    unit: "veces",
    inverse: true,
  },
  {
    id: "risk-eff-002",
    name: "Rotación de Inventario",
    category: "efficiency",
    indicator: "inventory_turnover",
    low: 12.0,
    medium: 6.0,
    high: 3.0,
    critical: 1.0,
    unit: "veces/año",
    inverse: true,
  },
  {
    id: "risk-eff-003",
    name: "Días de Cobro",
    category: "efficiency",
    indicator: "days_sales_outstanding",
    low: 30,
    medium: 60,
    high: 90,
    critical: 120,
    unit: "días",
    inverse: false,
  },
  {
    id: "risk-market-001",
    name: "Concentración de Clientes",
    category: "market",
    indicator: "client_concentration",
    low: 0.2,
    medium: 0.35,
    high: 0.5,
    critical: 0.7,
    unit: "porcentaje",
    inverse: false,
  },
  {
    id: "risk-market-002",
    name: "Dependencia de Proveedores",
    category: "market",
    indicator: "supplier_concentration",
    low: 0.2,
    medium: 0.35,
    high: 0.5,
    critical: 0.7,
    unit: "porcentaje",
    inverse: false,
  },
]
