export interface OntologyClass {
  id: string
  name: string
  description: string
  parentId?: string
  properties: string[]
  examples: string[]
}

export interface OntologyRelation {
  source: string
  target: string
  type: string
  label: string
  inverseLabel: string
  description: string
}

export const enterpriseOntology: OntologyClass[] = [
  {
    id: "ent:Enterprise",
    name: "Empresa",
    description: "Organización con personalidad jurídica que realiza actividades económicas",
    properties: ["id", "name", "industry", "size", "jurisdiction", "status"],
    examples: ["Constructora del Sur S.A.", "RetailMax S.A."],
  },
  {
    id: "ent:Organization",
    name: "Organización",
    description: "Estructura organizacional de la empresa",
    parentId: "ent:Enterprise",
    properties: ["departments", "hierarchy", "reportingLines"],
    examples: ["Dirección General", "VP Operaciones"],
  },
  {
    id: "ent:Department",
    name: "Departamento",
    description: "Unidad organizacional con función específica",
    parentId: "ent:Organization",
    properties: ["name", "head", "budget", "headcount", "functions"],
    examples: ["Finanzas", "Ventas", "Producción", "RRHH", "TI"],
  },
  {
    id: "ent:BusinessCapability",
    name: "Capacidad de Negocio",
    description: "Capacidad que la empresa posee para ejecutar una función de negocio",
    properties: ["name", "maturity", "risk", "cost", "owner", "dependencies"],
    examples: ["Gestión de Ventas", "Planificación Financiera", "Logística"],
  },
  {
    id: "ent:BusinessProcess",
    name: "Proceso de Negocio",
    description: "Conjunto de actividades relacionadas que transforman entradas en salidas",
    parentId: "ent:BusinessCapability",
    properties: ["name", "type", "trigger", "inputs", "outputs", "kpis", "owner"],
    examples: ["Ciclo de Ventas", "Cuentas por Cobrar", "Reclutamiento"],
  },
  {
    id: "ent:Activity",
    name: "Actividad",
    description: "Acción específica dentro de un proceso",
    parentId: "ent:BusinessProcess",
    properties: ["name", "duration", "cost", "responsible", "systems", "controls"],
    examples: ["Generar factura", "Aprobar crédito", "Conciliar banco"],
  },
  {
    id: "ent:BusinessFunction",
    name: "Función de Negocio",
    description: "Área de responsabilidad continua dentro de la organización",
    properties: ["name", "objective", "scope", "kpis"],
    examples: ["Gestión Financiera", "Gestión Comercial", "Gestión Legal"],
  },
  {
    id: "ent:BusinessService",
    name: "Servicio de Negocio",
    description: "Servicio que la empresa ofrece interna o externamente",
    properties: ["name", "type", "sla", "cost", "consumers"],
    examples: ["Servicio de Nómina", "Atención al Cliente", "Asesoría Legal"],
  },
  {
    id: "ent:BusinessAsset",
    name: "Activo de Negocio",
    description: "Recurso de valor para la empresa",
    properties: ["name", "type", "value", "depreciation", "owner", "location"],
    examples: ["Edificio Corporativo", "Flota Vehículos", "Marca Comercial"],
  },
  {
    id: "ent:FinancialAsset",
    name: "Activo Financiero",
    description: "Recurso financiero con valor económico",
    parentId: "ent:BusinessAsset",
    properties: ["type", "value", "liquidity", "risk", "return"],
    examples: ["Efectivo", "Cuentas por Cobrar", "Inversiones", "Inventarios"],
  },
  {
    id: "ent:IntangibleAsset",
    name: "Activo Intangible",
    description: "Activo no físico con valor económico",
    parentId: "ent:BusinessAsset",
    properties: ["type", "value", "amortization", "legalProtection"],
    examples: ["Software", "Patentes", "Marca", "Know-how", "Licencias"],
  },
  {
    id: "ent:BusinessObjective",
    name: "Objetivo de Negocio",
    description: "Meta estratégica, táctica u operativa que la empresa persigue",
    properties: ["name", "type", "target", "timeframe", "owner", "status"],
    examples: ["Crecer 20% en ingresos", "Reducir costos 15%", "Mejorar liquidez a 1.5"],
  },
  {
    id: "ent:StrategicObjective",
    name: "Objetivo Estratégico",
    description: "Meta de largo plazo alineada con la visión empresarial",
    parentId: "ent:BusinessObjective",
    properties: ["vision", "mission", "strategicPillars", "timeframeYears"],
    examples: ["Liderazgo en mercado nacional", "Transformación digital integral"],
  },
  {
    id: "ent:BusinessPolicy",
    name: "Política de Negocio",
    description: "Directriz que guía la toma de decisiones Organización",
    properties: ["name", "scope", "applicability", "enforcement"],
    examples: ["Política de Crédito", "Política de Viajes", "Política de Seguridad"],
  },
  {
    id: "ent:BusinessRule",
    name: "Regla de Negocio",
    description: "Condición que restringe o define aspectos operativos",
    parentId: "ent:BusinessPolicy",
    properties: ["name", "condition", "action", "priority", "automated"],
    examples: ["if client_score < 50 then require_guarantor", "if invoice > 30d then block_new_orders"],
  },
  {
    id: "ent:BusinessControl",
    name: "Control Interno",
    description: "Mecanismo para mitigar riesgos y asegurar cumplimiento",
    properties: ["name", "type", "frequency", "owner", "evidence", "automated"],
    examples: ["Dual approval for payments >$5K", "Monthly bank reconciliation"],
  },
  {
    id: "ent:BusinessRisk",
    name: "Riesgo de Negocio",
    description: "Evento incierto que puede afectar objetivos empresariales",
    properties: ["name", "probability", "impact", "riskLevel", "controls", "mitigation"],
    examples: ["Riesgo de liquidez", "Concentración de clientes", "Incumplimiento tributario"],
  },
  {
    id: "ent:FinancialRisk",
    name: "Riesgo Financiero",
    description: "Riesgo relacionado con la estructura financiera y mercado",
    parentId: "ent:BusinessRisk",
    properties: ["type", "exposure", "mitigation", "indicators"],
    examples: ["Riesgo de crédito", "Riesgo de tasa de interés", "Riesgo de tipo de cambio"],
  },
  {
    id: "ent:OperationalRisk",
    name: "Riesgo Operacional",
    description: "Riesgo de pérdida por procesos, personas o sistemas inadecuados",
    parentId: "ent:BusinessRisk",
    properties: ["process", "cause", "effect", "severity"],
    examples: ["Falla en sistema de facturación", "Error humano en conciliación"],
  },
  {
    id: "ent:ComplianceRisk",
    name: "Riesgo de Cumplimiento",
    description: "Riesgo por incumplimiento de leyes y regulaciones",
    parentId: "ent:BusinessRisk",
    properties: ["regulation", "sanction", "probability", "impact"],
    examples: ["Multas SRI", "Sanciones laborales", "Incumplimiento NIIF"],
  },
  {
    id: "ent:Stakeholder",
    name: "Interesado",
    description: "Persona o entidad con interés en la empresa",
    properties: ["name", "type", "interest", "influence", "expectations"],
    examples: ["Accionistas", "Clientes", "Proveedores", "Empleados", "SRI", "Supercias"],
  },
  {
    id: "ent:Client",
    name: "Cliente",
    description: "Persona o entidad que adquiere productos o servicios",
    parentId: "ent:Stakeholder",
    properties: ["segment", "industry", "revenue", "lifetime", "satisfaction"],
    examples: ["Cliente Corporativo", "PYME", "Consumidor Final"],
  },
  {
    id: "ent:Supplier",
    name: "Proveedor",
    description: "Entidad que suministra bienes o servicios a la empresa",
    parentId: "ent:Stakeholder",
    properties: ["category", "criticality", "spend", "contract", "performance"],
    examples: ["Proveedor de Materia Prima", "Consultor TI", "Servicio de Outsourcing"],
  },
  {
    id: "ent:Regulator",
    name: "Ente Regulador",
    description: "Autoridad que establece normas de cumplimiento obligatorio",
    parentId: "ent:Stakeholder",
    properties: ["jurisdiction", "scope", "powers", "sanctions"],
    examples: ["SRI", "Superintendencia de Compañías", "Ministerio de Trabajo", "BCE"],
  },
  {
    id: "ent:Employee",
    name: "Empleado",
    description: "Persona que trabaja para la empresa",
    properties: ["role", "department", "seniority", "skills", "cost"],
    examples: ["CEO", "CFO", "Contador", "Vendedor", "Operario"],
  },
  {
    id: "ent:BusinessRole",
    name: "Rol de Negocio",
    description: "Conjunto de responsabilidades asignadas a una persona",
    properties: ["name", "responsibilities", "authorities", "requiredSkills"],
    examples: ["Director Financiero", "Jefe de Ventas", "Analista de Riesgos"],
  },
  {
    id: "ent:Project",
    name: "Proyecto",
    description: "Esfuerzo temporal para crear un resultado único",
    properties: ["name", "scope", "budget", "timeline", "status", "sponsor"],
    examples: ["Implementación ERP", "Transformación Digital", "Reestructuración Deuda"],
  },
  {
    id: "ent:Mission",
    name: "Misión",
    description: "Propósito fundamental de la empresa",
    parentId: "ent:BusinessObjective",
    properties: ["statement", "values"],
    examples: ["Proveer soluciones financieras accesibles"],
  },
  {
    id: "ent:Vision",
    name: "Visión",
    description: "Aspiración futura de la empresa",
    parentId: "ent:BusinessObjective",
    properties: ["statement", "timeframe"],
    examples: ["Ser líder en consultoría financiera en Ecuador para 2030"],
  },
  {
    id: "ent:KPI",
    name: "Indicador Clave de Desempeño",
    description: "Métrica cuantificable que mide el logro de objetivos",
    properties: ["name", "formula", "unit", "target", "thresholds", "frequency"],
    examples: ["ROE", "Margen Neto", "Rotación de Inventario", "NPS"],
  },
  {
    id: "ent:FinancialStatement",
    name: "Estado Financiero",
    description: "Reporte formal de la situación financiera de la empresa",
    properties: ["type", "period", "currency", "standard", "audited"],
    examples: ["Balance General", "Estado Resultados", "Flujo de Efectivo"],
  },
  {
    id: "ent:IFRSConcept",
    name: "Concepto IFRS",
    description: "Elemento de la taxonomía IFRS oficial con definición normativa",
    properties: ["code", "name", "definition", "type", "balance", "periodType"],
    examples: ["ifrs-full:CurrentAssets", "ifrs-full:Revenue", "ifrs-full:CashAndCashEquivalents"],
  },
  {
    id: "ent:Regulation",
    name: "Normativa",
    description: "Ley, decreto, resolución o norma de cumplimiento obligatorio",
    properties: ["name", "type", "jurisdiction", "effectiveDate", "authority", "articles"],
    examples: ["LRTI", "NIIF 16", "Código de Trabajo", "COPCI"],
  },
  {
    id: "ent:Article",
    name: "Artículo",
    description: "Disposición específica dentro de una norma",
    parentId: "ent:Regulation",
    properties: ["number", "text", "topic", "sanctions", "exceptions"],
    examples: ["Art. 9 LRTI", "Art. 42 Código Trabajo"],
  },
  {
    id: "ent:Evidence",
    name: "Evidencia",
    description: "Documento o registro que demuestra cumplimiento o resultado",
    properties: ["name", "type", "source", "date", "validity", "link"],
    examples: ["Acta de reunión", "Balance firmado", "Declaración SRI"],
  },
  {
    id: "ent:BusinessOutcome",
    name: "Resultado de Negocio",
    description: "Consecuencia medible de una acción o decisión empresarial",
    properties: ["name", "type", "value", "timeframe", "variance"],
    examples: ["Aumento de rentabilidad", "Reducción de deuda", "Mejora de liquidez"],
  },
  {
    id: "ent:BusinessValue",
    name: "Valor de Negocio",
    description: "Beneficio generado por las actividades empresariales",
    properties: ["name", "type", "measure", "stakeholder"],
    examples: ["Valor para accionista", "Valor para cliente", "Valor social"],
  },
  {
    id: "ent:BusinessConstraint",
    name: "Restricción de Negocio",
    description: "Limitación que afecta las decisiones y operaciones",
    properties: ["name", "type", "source", "impact", "flexibility"],
    examples: ["Presupuesto limitado", "Capacidad instalada", "Regulación cambiaria"],
  },
  {
    id: "ent:BusinessDependency",
    name: "Dependencia de Negocio",
    description: "Relación donde un elemento requiere de otro para funcionar",
    properties: ["name", "type", "criticality", "redundancy"],
    examples: ["Ventas depende de Inventario", "Facturación depende de TI"],
  },
  {
    id: "ent:Industry",
    name: "Industria",
    description: "Sector económico donde opera la empresa",
    properties: ["code", "name", "superSector", "benchmarks"],
    examples: ["Manufactura", "Comercio", "Construcción", "Servicios", "Agricultura"],
  },
  {
    id: "ent:Market",
    name: "Mercado",
    description: "Entorno donde la empresa compite y opera",
    properties: ["name", "type", "size", "growth", "participants", "barriers"],
    examples: ["Mercado PYME Ecuador", "Sector Construcción Quito"],
  },
  {
    id: "ent:Product",
    name: "Producto",
    description: "Bien o servicio que la empresa ofrece al mercado",
    properties: ["name", "type", "price", "cost", "margin", "lifecycle"],
    examples: ["Consulting Intelligence Suite", "Servicio de Auditoría"],
  },
  {
    id: "ent:Technology",
    name: "Tecnología",
    description: "Sistema o herramienta tecnológica utilizada por la empresa",
    properties: ["name", "type", "vendor", "version", "lifecycle", "integration"],
    examples: ["SAP ERP", "Salesforce CRM", "Power BI", "BI OS Platform"],
  },
  {
    id: "ent:InformationSystem",
    name: "Sistema de Información",
    description: "Sistema que procesa y almacena datos empresariales",
    parentId: "ent:Technology",
    properties: ["name", "purpose", "data", "users", "interfaces"],
    examples: ["ERP", "CRM", "SCM", "HRM", "BI Platform"],
  },
  {
    id: "ent:Document",
    name: "Documento",
    description: "Registro formal de información empresarial",
    properties: ["name", "type", "classification", "retention", "confidentiality"],
    examples: ["Balance General 2025", "Contrato de Crédito", "Declaración IVA"],
  },
  {
    id: "ent:BusinessEvent",
    name: "Evento de Negocio",
    description: "Ocurrencia relevante que afecta la operación o estrategia",
    properties: ["name", "type", "date", "impact", "response"],
    examples: ["Fusión", "Cambio normativo", "Crisis de liquidez", "Nuevo competidor"],
  },
  {
    id: "ent:Decision",
    name: "Decisión",
    description: "Elección entre alternativas con impacto en el negocio",
    properties: ["name", "type", "context", "alternatives", "criteria", "outcome"],
    examples: ["Aprobación de inversión", "Selección de proveedor", "Cambio de estrategia"],
  },
  {
    id: "ent:BestPractice",
    name: "Mejor Práctica",
    description: "Método o técnica que produce resultados superiores comprobados",
    properties: ["name", "domain", "description", "evidence", "applicability"],
    examples: ["Gestión Lean", "OKR", "Cuadro de Mando Integral", "Ciclo PDCA"],
  },
  {
    id: "ent:Methodology",
    name: "Metodología",
    description: "Conjunto sistematizado de métodos para lograr un objetivo",
    properties: ["name", "domain", "steps", "tools", "deliverables"],
    examples: ["Análisis Dupont", "DCF Valuation", "FODA", "BPMN"],
  },
]

export const enterpriseRelations: OntologyRelation[] = [
  { source: "ent:Enterprise", target: "ent:Organization", type: "has", label: "tiene", inverseLabel: "pertenece a", description: "La empresa tiene una organización" },
  { source: "ent:Organization", target: "ent:Department", type: "has", label: "tiene departamentos", inverseLabel: "pertenece a", description: "La organización se estructura en departamentos" },
  { source: "ent:Enterprise", target: "ent:BusinessCapability", type: "has", label: "posee capacidad", inverseLabel: "capacidad de", description: "La empresa posee capacidades de negocio" },
  { source: "ent:BusinessCapability", target: "ent:BusinessProcess", type: "has", label: "se ejecuta mediante", inverseLabel: "implementa", description: "La capacidad se realiza mediante procesos" },
  { source: "ent:BusinessProcess", target: "ent:Activity", type: "has", label: "contiene actividades", inverseLabel: "pertenece a", description: "El proceso contiene actividades" },
  { source: "ent:BusinessProcess", target: "ent:KPI", type: "measured_by", label: "medido por KPI", inverseLabel: "mide proceso", description: "El proceso tiene KPIs asociados" },
  { source: "ent:BusinessCapability", target: "ent:BusinessService", type: "delivers", label: "entrega servicio", inverseLabel: "provisto por", description: "La capacidad entrega servicios" },
  { source: "ent:Enterprise", target: "ent:BusinessAsset", type: "owns", label: "posee activo", inverseLabel: "propiedad de", description: "La empresa posee activos" },
  { source: "ent:Enterprise", target: "ent:BusinessObjective", type: "pursues", label: "persigue objetivo", inverseLabel: "objetivo de", description: "La empresa persigue objetivos" },
  { source: "ent:BusinessObjective", target: "ent:StrategicObjective", type: "refines", label: "se detalla en", inverseLabel: "alineado con", description: "Objetivos tácticos detallan estratégicos" },
  { source: "ent:Enterprise", target: "ent:Mission", type: "defined_by", label: "definido por misión", inverseLabel: "define", description: "La empresa tiene una misión" },
  { source: "ent:Enterprise", target: "ent:Vision", type: "aspires_to", label: "aspira a visión", inverseLabel: "aspiración de", description: "La empresa tiene una visión" },
  { source: "ent:Enterprise", target: "ent:Industry", type: "operates_in", label: "opera en industria", inverseLabel: "empresas de", description: "La empresa opera en una industria" },
  { source: "ent:Enterprise", target: "ent:Market", type: "competes_in", label: "compite en mercado", inverseLabel: "", description: "La empresa compite en un mercado" },
  { source: "ent:Enterprise", target: "ent:Stakeholder", type: "relates_to", label: "se relaciona con", inverseLabel: "interesado en", description: "La empresa se relaciona con interesados" },
  { source: "ent:Enterprise", target: "ent:Product", type: "offers", label: "ofrece producto", inverseLabel: "ofrecido por", description: "La empresa ofrece productos" },
  { source: "ent:Enterprise", target: "ent:Technology", type: "uses", label: "usa tecnología", inverseLabel: "usado por", description: "La empresa usa tecnologías" },
  { source: "ent:Enterprise", target: "ent:Document", type: "produces", label: "produce documento", inverseLabel: "producido por", description: "La empresa produce documentos" },
  { source: "ent:Enterprise", target: "ent:BusinessEvent", type: "experiences", label: "experimenta evento", inverseLabel: "afecta a", description: "La empresa experimenta eventos" },
  { source: "ent:Enterprise", target: "ent:Decision", type: "makes", label: "toma decisiones", inverseLabel: "afecta a", description: "La empresa toma decisiones" },
  { source: "ent:Department", target: "ent:BusinessRole", type: "has", label: "tiene roles", inverseLabel: "pertenece a", description: "El departamento tiene roles" },
  { source: "ent:BusinessRole", target: "ent:Employee", type: "assigned_to", label: "asignado a", inverseLabel: "ocupa rol", description: "El rol es ocupado por empleados" },
  { source: "ent:Employee", target: "ent:BusinessRole", type: "occupies", label: "ocupa", inverseLabel: "ocupado por", description: "El empleado ocupa un rol" },
  { source: "ent:BusinessCapability", target: "ent:Employee", type: "staffed_by", label: "dotada por", inverseLabel: "trabaja en", description: "La capacidad es ejecutada por personas" },
  { source: "ent:BusinessProcess", target: "ent:BusinessControl", type: "controlled_by", label: "controlado por", inverseLabel: "controla", description: "El proceso tiene controles" },
  { source: "ent:BusinessControl", target: "ent:BusinessRisk", type: "mitigates", label: "mitiga riesgo", inverseLabel: "mitigado por", description: "El control mitiga riesgos" },
  { source: "ent:BusinessRisk", target: "ent:BusinessObjective", type: "threatens", label: "amenaza objetivo", inverseLabel: "amenazado por", description: "El riesgo amenaza objetivos" },
  { source: "ent:BusinessRisk", target: "ent:BusinessControl", type: "has_control", label: "tiene control", inverseLabel: "controla", description: "El riesgo tiene controles asociados" },
  { source: "ent:BusinessPolicy", target: "ent:BusinessRule", type: "implemented_by", label: "implementado por reglas", inverseLabel: "implementa", description: "La política se implementa mediante reglas" },
  { source: "ent:BusinessPolicy", target: "ent:BusinessControl", type: "enforced_by", label: "reforzado por", inverseLabel: "refuerza", description: "La política se refuerza con controles" },
  { source: "ent:Regulation", target: "ent:Article", type: "contains", label: "contiene artículo", inverseLabel: "artículo de", description: "La norma contiene artículos" },
  { source: "ent:Enterprise", target: "ent:Regulation", type: "must_comply", label: "debe cumplir", inverseLabel: "aplica a", description: "La empresa debe cumplir normativas" },
  { source: "ent:BusinessRisk", target: "ent:Regulation", type: "regulated_by", label: "regulado por", inverseLabel: "regula", description: "El riesgo está regulado por normas" },
  { source: "ent:Activity", target: "ent:Document", type: "produces", label: "produce documento", inverseLabel: "generado por", description: "La actividad produce documentos" },
  { source: "ent:Activity", target: "ent:Technology", type: "uses", label: "usa sistema", inverseLabel: "usado en", description: "La actividad usa sistemas" },
  { source: "ent:FinancialStatement", target: "ent:IFRSConcept", type: "composed_of", label: "compuesto por conceptos", inverseLabel: "pertenece a", description: "El estado financiero usa conceptos IFRS" },
  { source: "ent:IFRSConcept", target: "ent:IFRSConcept", type: "part_of", label: "es parte de", inverseLabel: "contiene", description: "Jerarquía de conceptos IFRS" },
  { source: "ent:IFRSConcept", target: "ent:KPI", type: "feeds", label: "alimenta KPI", inverseLabel: "calculado de", description: "El concepto IFRS alimenta KPIs" },
  { source: "ent:KPI", target: "ent:BusinessObjective", type: "measures", label: "mide objetivo", inverseLabel: "medido por", description: "El KPI mide progreso de objetivo" },
  { source: "ent:KPI", target: "ent:BusinessRisk", type: "indicates", label: "indica riesgo", inverseLabel: "alertado por", description: "El KPI puede indicar riesgos" },
  { source: "ent:BusinessEvent", target: "ent:Decision", type: "triggers", label: "desencadena decisión", inverseLabel: "respuesta a", description: "Eventos desencadenan decisiones" },
  { source: "ent:Decision", target: "ent:BusinessOutcome", type: "produces", label: "produce resultado", inverseLabel: "resultado de", description: "Las decisiones producen resultados" },
  { source: "ent:BusinessOutcome", target: "ent:BusinessValue", type: "generates", label: "genera valor", inverseLabel: "valor generado por", description: "Los resultados generan valor" },
  { source: "ent:Project", target: "ent:BusinessCapability", type: "enhances", label: "mejora capacidad", inverseLabel: "mejorada por", description: "Los proyectos mejoran capacidades" },
  { source: "ent:Project", target: "ent:BusinessProcess", type: "improves", label: "mejora proceso", inverseLabel: "mejorado por", description: "Los proyectos mejoran procesos" },
  { source: "ent:BusinessCapability", target: "ent:BusinessCapability", type: "depends_on", label: "depende de", inverseLabel: "requerido por", description: "Dependencia entre capacidades" },
  { source: "ent:BusinessProcess", target: "ent:BusinessProcess", type: "depends_on", label: "depende de", inverseLabel: "requerido por", description: "Dependencia entre procesos" },
  { source: "ent:BusinessConstraint", target: "ent:BusinessObjective", type: "limits", label: "limita objetivo", inverseLabel: "limitado por", description: "Restricciones que afectan objetivos" },
  { source: "ent:BusinessConstraint", target: "ent:BusinessProcess", type: "affects", label: "afecta proceso", inverseLabel: "afectado por", description: "Restricciones que afectan procesos" },
  { source: "ent:Technology", target: "ent:BusinessCapability", type: "enables", label: "habilita capacidad", inverseLabel: "habilitada por", description: "La tecnología habilita capacidades" },
  { source: "ent:Technology", target: "ent:BusinessProcess", type: "supports", label: "soporta proceso", inverseLabel: "soportado por", description: "La tecnología soporta procesos" },
  { source: "ent:InformationSystem", target: "ent:BusinessCapability", type: "automates", label: "automatiza capacidad", inverseLabel: "automatizado por", description: "Sistemas automatizan capacidades" },
  { source: "ent:Stakeholder", target: "ent:BusinessObjective", type: "has_interest", label: "tiene interés en", inverseLabel: "interesa a", description: "Interesados tienen interés en objetivos" },
  { source: "ent:Client", target: "ent:Product", type: "consumes", label: "consume producto", inverseLabel: "consumido por", description: "Clientes consumen productos" },
  { source: "ent:Supplier", target: "ent:BusinessAsset", type: "provides", label: "provee activo", inverseLabel: "provisto por", description: "Proveedores suministran activos" },
  { source: "ent:Market", target: "ent:Client", type: "contains", label: "contiene clientes", inverseLabel: "pertenece a", description: "El mercado contiene clientes" },
  { source: "ent:Industry", target: "ent:Market", type: "has_market", label: "tiene mercado", inverseLabel: "mercado de", description: "La industria tiene mercados" },
  { source: "ent:BestPractice", target: "ent:Methodology", type: "applied_through", label: "aplica mediante", inverseLabel: "implementa", description: "La mejor práctica se aplica con metodologías" },
  { source: "ent:Methodology", target: "ent:BusinessProcess", type: "guides", label: "guía proceso", inverseLabel: "guiado por", description: "La metodología guía la ejecución de procesos" },
  { source: "ent:Enterprise", target: "ent:Evidence", type: "produces", label: "genera evidencia", inverseLabel: "evidencia de", description: "La empresa produce evidencia" },
  { source: "ent:BusinessControl", target: "ent:Evidence", type: "requires", label: "requiere evidencia", inverseLabel: "evidencia para", description: "Los controles requieren evidencia" },
  { source: "ent:Regulation", target: "ent:BusinessPolicy", type: "requires", label: "requiere política", inverseLabel: "exigida por", description: "La regulación exige políticas" },
]
