import type { SuccessMetric } from "./types"

export const successMetrics: SuccessMetric[] = [
  {
    id: "nsm-001",
    name: "Empresas con Análisis Activo",
    category: "adopcion",
    description: "Número de empresas que generaron al menos un análisis completo en los últimos 30 días. Es nuestra North Star Metric.",
    formula: "COUNT(empresas WHERE last_analysis_date > now() - 30d)",
    target: "10 empresas en beta, 50 en GA",
    current: null,
    unit: "empresas",
    frequency: "diaria",
  },
  {
    id: "met-001",
    name: "Tasa de Activación",
    category: "activacion",
    description: "Porcentaje de empresas registradas que completan el flujo: registrar → crear cliente → subir documento → analizar.",
    formula: "empresas_con_analisis / empresas_registradas * 100",
    target: "> 60%",
    current: null,
    unit: "porcentaje",
    frequency: "semanal",
  },
  {
    id: "met-002",
    name: "Tiempo hasta Primer Análisis",
    category: "activacion",
    description: "Tiempo promedio desde que una empresa se registra hasta que completa su primer análisis financiero.",
    formula: "AVG(timestamp_primer_analisis - timestamp_registro)",
    target: "< 7 días",
    current: null,
    unit: "días",
    frequency: "semanal",
  },
  {
    id: "met-003",
    name: "Retención Mensual",
    category: "retencion",
    description: "Porcentaje de empresas que generan análisis en dos meses consecutivos.",
    formula: "empresas_activas_mes_actual / empresas_activas_mes_anterior * 100",
    target: "> 80%",
    current: null,
    unit: "porcentaje",
    frequency: "mensual",
  },
  {
    id: "met-004",
    name: "Análisis por Empresa",
    category: "adopcion",
    description: "Promedio de análisis generados por empresa activa en el último mes.",
    formula: "total_analisis_mes / empresas_activas_mes",
    target: "> 3 análisis/empresa/mes",
    current: null,
    unit: "análisis/empresa",
    frequency: "mensual",
  },
  {
    id: "met-005",
    name: "Uso del Copilot",
    category: "ia",
    description: "Porcentaje de usuarios activos que interactúan con el AI Copilot al menos una vez por semana.",
    formula: "usuarios_conversacion_semana / usuarios_activos_semana * 100",
    target: "> 40%",
    current: null,
    unit: "porcentaje",
    frequency: "semanal",
  },
  {
    id: "met-006",
    name: "Tasa de Aceptación de Recomendaciones",
    category: "calidad",
    description: "Porcentaje de recomendaciones generadas por IA que son aceptadas o marcadas como útiles por el consultor.",
    formula: "recomendaciones_aceptadas / recomendaciones_generadas * 100",
    target: "> 70%",
    current: null,
    unit: "porcentaje",
    frequency: "mensual",
  },
  {
    id: "met-007",
    name: "Feedback Score Promedio",
    category: "calidad",
    description: "Score promedio de feedback de usuarios sobre respuestas del AI Copilot (escala 1-5).",
    formula: "AVG(feedback_score)",
    target: "> 4.0",
    current: null,
    unit: "score",
    frequency: "semanal",
  },
  {
    id: "met-008",
    name: "Informes Generados",
    category: "adopcion",
    description: "Número total de informes PDF generados en el período.",
    formula: "COUNT(reportes_generados)",
    target: "> 5 por empresa/mes",
    current: null,
    unit: "informes",
    frequency: "mensual",
  },
  {
    id: "met-009",
    name: "Planes Estratégicos Ejecutados",
    category: "adopcion",
    description: "Número de planes estratégicos creados y con al menos una tarea completada.",
    formula: "COUNT(planes WHERE tareas_completadas > 0)",
    target: "> 2 por empresa/mes",
    current: null,
    unit: "planes",
    frequency: "mensual",
  },
  {
    id: "met-010",
    name: "Tasa de Conversión a Pago",
    category: "monetizacion",
    description: "Porcentaje de empresas en beta que estarían dispuestas a pagar por el servicio.",
    formula: "empresas_interesadas_pago / empresas_beta * 100",
    target: "> 40% en beta",
    current: null,
    unit: "porcentaje",
    frequency: "mensual",
  },
  {
    id: "met-011",
    name: "Ingreso por Empresa",
    category: "monetizacion",
    description: "Ingreso mensual promedio por empresa activa.",
    formula: "MRR / empresas_activas",
    target: "> $150 ARPU",
    current: null,
    unit: "USD",
    frequency: "mensual",
  },
  {
    id: "met-012",
    name: "Tiempo Ahorrado por Consultor",
    category: "ia",
    description: "Horas estimadas ahorradas por consultor al mes usando la plataforma vs proceso manual.",
    formula: "AVG(horas_estimadas_manual - horas_reales_plataforma)",
    target: "> 20 horas/mes",
    current: null,
    unit: "horas",
    frequency: "mensual",
  },
]
