import type { PricingPlan } from "./types"

export const pricing: PricingPlan[] = [
  {
    tier: "starter",
    name: "Starter",
    price: 49,
    priceLabel: "$49/mes",
    description: "Para consultores individuales que inician su práctica de análisis financiero asistido por IA.",
    highlighted: false,
    limits: [
      { feature: "Clientes activos", starter: 5, professional: 25, enterprise: -1, unit: "clientes" },
      { feature: "Usuarios", starter: 1, professional: 5, enterprise: -1, unit: "usuarios" },
      { feature: "Análisis financieros / mes", starter: 10, professional: 50, enterprise: -1, unit: "análisis" },
      { feature: "Documentos almacenados", starter: 100, professional: 1000, enterprise: 10000, unit: "documentos" },
      { feature: "Conversaciones AI / mes", starter: 50, professional: 500, enterprise: -1, unit: "conversaciones" },
      { feature: "Informes PDF", starter: false, professional: true, enterprise: true, unit: "" },
      { feature: "Plan estratégico ejecutable", starter: false, professional: true, enterprise: true, unit: "" },
      { feature: "Benchmarking sectorial", starter: false, professional: true, enterprise: true, unit: "" },
      { feature: "Simulación de escenarios", starter: false, professional: false, enterprise: true, unit: "" },
      { feature: "API Access", starter: false, professional: false, enterprise: true, unit: "" },
      { feature: "Soporte", starter: "Email", professional: "Prioritario", enterprise: "Dedicado 24/7", unit: "" },
      { feature: "Almacenamiento", starter: "1 GB", professional: "10 GB", enterprise: "100 GB", unit: "" },
    ],
    addons: [
      { name: "Usuario adicional", description: "Consulta adicional para tu equipo", price: 29, unit: "usuario/mes" },
    ],
  },
  {
    tier: "professional",
    name: "Professional",
    price: 149,
    priceLabel: "$149/mes",
    description: "Para firmas de consultoría que necesitan análisis profundos, informes profesionales y colaboración en equipo.",
    highlighted: true,
    limits: [
      { feature: "Clientes activos", starter: 5, professional: 25, enterprise: -1, unit: "clientes" },
      { feature: "Usuarios", starter: 1, professional: 5, enterprise: -1, unit: "usuarios" },
      { feature: "Análisis financieros / mes", starter: 10, professional: 50, enterprise: -1, unit: "análisis" },
      { feature: "Documentos almacenados", starter: 100, professional: 1000, enterprise: 10000, unit: "documentos" },
      { feature: "Conversaciones AI / mes", starter: 50, professional: 500, enterprise: -1, unit: "conversaciones" },
      { feature: "Informes PDF", starter: false, professional: true, enterprise: true, unit: "" },
      { feature: "Plan estratégico ejecutable", starter: false, professional: true, enterprise: true, unit: "" },
      { feature: "Benchmarking sectorial", starter: false, professional: true, enterprise: true, unit: "" },
      { feature: "Simulación de escenarios", starter: false, professional: false, enterprise: true, unit: "" },
      { feature: "API Access", starter: false, professional: false, enterprise: true, unit: "" },
      { feature: "Soporte", starter: "Email", professional: "Prioritario", enterprise: "Dedicado 24/7", unit: "" },
      { feature: "Almacenamiento", starter: "1 GB", professional: "10 GB", enterprise: "100 GB", unit: "" },
    ],
    addons: [
      { name: "Usuario adicional", description: "Miembro extra del equipo", price: 49, unit: "usuario/mes" },
      { name: "Lote 10 análisis", description: "10 análisis financieros adicionales", price: 29, unit: "lote/mes" },
    ],
  },
  {
    tier: "enterprise",
    name: "Enterprise",
    price: 499,
    priceLabel: "$499/mes",
    description: "Para organizaciones que requieren capacidad ilimitada, agentes dedicados, simulación y soporte premium.",
    highlighted: false,
    limits: [
      { feature: "Clientes activos", starter: 5, professional: 25, enterprise: -1, unit: "clientes" },
      { feature: "Usuarios", starter: 1, professional: 5, enterprise: -1, unit: "usuarios" },
      { feature: "Análisis financieros / mes", starter: 10, professional: 50, enterprise: -1, unit: "análisis" },
      { feature: "Documentos almacenados", starter: 100, professional: 1000, enterprise: 10000, unit: "documentos" },
      { feature: "Conversaciones AI / mes", starter: 50, professional: 500, enterprise: -1, unit: "conversaciones" },
      { feature: "Informes PDF", starter: false, professional: true, enterprise: true, unit: "" },
      { feature: "Plan estratégico ejecutable", starter: false, professional: true, enterprise: true, unit: "" },
      { feature: "Benchmarking sectorial", starter: false, professional: true, enterprise: true, unit: "" },
      { feature: "Simulación de escenarios", starter: false, professional: false, enterprise: true, unit: "" },
      { feature: "API Access", starter: false, professional: false, enterprise: true, unit: "" },
      { feature: "Soporte", starter: "Email", professional: "Prioritario", enterprise: "Dedicado 24/7", unit: "" },
      { feature: "Almacenamiento", starter: "1 GB", professional: "10 GB", enterprise: "100 GB", unit: "" },
    ],
    addons: [
      { name: "Usuario adicional", description: "Miembro del equipo", price: 79, unit: "usuario/mes" },
      { name: "Agente especializado", description: "Agente AI adicional (tax, legal, etc.)", price: 99, unit: "agente/mes" },
      { name: "On-premise", description: "Despliegue en infraestructura del cliente", price: 999, unit: "instalación única" },
    ],
  },
]
