// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../../src/app/(public)/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../../../src/app/(public)/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(public)/auth/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/register">> = Specific
  const handler = {} as typeof import("../../../../src/app/(public)/auth/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(public)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../src/app/(public)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(public)/precios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/precios">> = Specific
  const handler = {} as typeof import("../../../../src/app/(public)/precios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/admin/flags/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/flags">> = Specific
  const handler = {} as typeof import("../../../../src/app/admin/flags/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/admin/rules/[ruleId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/rules/[ruleId]">> = Specific
  const handler = {} as typeof import("../../../../src/app/admin/rules/[ruleId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/admin/rules/[ruleId]/sandbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/rules/[ruleId]/sandbox">> = Specific
  const handler = {} as typeof import("../../../../src/app/admin/rules/[ruleId]/sandbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/admin/rules/[ruleId]/versions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/rules/[ruleId]/versions">> = Specific
  const handler = {} as typeof import("../../../../src/app/admin/rules/[ruleId]/versions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/admin/rules/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/rules/analytics">> = Specific
  const handler = {} as typeof import("../../../../src/app/admin/rules/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/admin/rules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/rules">> = Specific
  const handler = {} as typeof import("../../../../src/app/admin/rules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/cliente/documentos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cliente/documentos">> = Specific
  const handler = {} as typeof import("../../../../src/app/cliente/documentos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/cliente/mensajes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cliente/mensajes">> = Specific
  const handler = {} as typeof import("../../../../src/app/cliente/mensajes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/cliente/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cliente">> = Specific
  const handler = {} as typeof import("../../../../src/app/cliente/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/cliente/reportes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cliente/reportes">> = Specific
  const handler = {} as typeof import("../../../../src/app/cliente/reportes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/cliente/reuniones/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cliente/reuniones">> = Specific
  const handler = {} as typeof import("../../../../src/app/cliente/reuniones/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/consultor/clientes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/consultor/clientes">> = Specific
  const handler = {} as typeof import("../../../../src/app/consultor/clientes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/consultor/dashboard/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/consultor/dashboard/agents">> = Specific
  const handler = {} as typeof import("../../../../src/app/consultor/dashboard/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/consultor/dashboard/data-hub/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/consultor/dashboard/data-hub">> = Specific
  const handler = {} as typeof import("../../../../src/app/consultor/dashboard/data-hub/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/consultor/dashboard/margins/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/consultor/dashboard/margins">> = Specific
  const handler = {} as typeof import("../../../../src/app/consultor/dashboard/margins/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/consultor/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/consultor/dashboard">> = Specific
  const handler = {} as typeof import("../../../../src/app/consultor/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/consultor/dashboard/stress-simulator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/consultor/dashboard/stress-simulator">> = Specific
  const handler = {} as typeof import("../../../../src/app/consultor/dashboard/stress-simulator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/consultor/dashboard/valuation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/consultor/dashboard/valuation">> = Specific
  const handler = {} as typeof import("../../../../src/app/consultor/dashboard/valuation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/consultor/documentos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/consultor/documentos">> = Specific
  const handler = {} as typeof import("../../../../src/app/consultor/documentos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/consultor/legal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/consultor/legal">> = Specific
  const handler = {} as typeof import("../../../../src/app/consultor/legal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/consultor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/consultor">> = Specific
  const handler = {} as typeof import("../../../../src/app/consultor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/consultor/proyectos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/consultor/proyectos">> = Specific
  const handler = {} as typeof import("../../../../src/app/consultor/proyectos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/consultor/tributario/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/consultor/tributario">> = Specific
  const handler = {} as typeof import("../../../../src/app/consultor/tributario/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/director/adn/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/director/adn">> = Specific
  const handler = {} as typeof import("../../../../src/app/director/adn/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/director/biblioteca/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/director/biblioteca">> = Specific
  const handler = {} as typeof import("../../../../src/app/director/biblioteca/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/director/clientes-global/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/director/clientes-global">> = Specific
  const handler = {} as typeof import("../../../../src/app/director/clientes-global/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/director/clientes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/director/clientes/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/director/clientes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/director/clientes/crear/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/director/clientes/crear">> = Specific
  const handler = {} as typeof import("../../../../src/app/director/clientes/crear/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/director/ejecucion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/director/ejecucion">> = Specific
  const handler = {} as typeof import("../../../../src/app/director/ejecucion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/director/equipo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/director/equipo">> = Specific
  const handler = {} as typeof import("../../../../src/app/director/equipo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/director/finanzas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/director/finanzas">> = Specific
  const handler = {} as typeof import("../../../../src/app/director/finanzas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/director/genoma/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/director/genoma">> = Specific
  const handler = {} as typeof import("../../../../src/app/director/genoma/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/director/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/director">> = Specific
  const handler = {} as typeof import("../../../../src/app/director/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/director/planificacion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/director/planificacion">> = Specific
  const handler = {} as typeof import("../../../../src/app/director/planificacion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/director/platform/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/director/platform">> = Specific
  const handler = {} as typeof import("../../../../src/app/director/platform/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/director/product-os/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/director/product-os">> = Specific
  const handler = {} as typeof import("../../../../src/app/director/product-os/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/director/productos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/director/productos">> = Specific
  const handler = {} as typeof import("../../../../src/app/director/productos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/director/riesgos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/director/riesgos">> = Specific
  const handler = {} as typeof import("../../../../src/app/director/riesgos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/director/telemetria/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/director/telemetria">> = Specific
  const handler = {} as typeof import("../../../../src/app/director/telemetria/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/due-diligence/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/due-diligence/history">> = Specific
  const handler = {} as typeof import("../../../../src/app/due-diligence/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/due-diligence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/due-diligence">> = Specific
  const handler = {} as typeof import("../../../../src/app/due-diligence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/portal/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/login">> = Specific
  const handler = {} as typeof import("../../../../src/app/portal/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/portal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal">> = Specific
  const handler = {} as typeof import("../../../../src/app/portal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../../../src/app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(public)/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../../src/app/(public)/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(public)/auth/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/confirm">> = Specific
  const handler = {} as typeof import("../../../../src/app/(public)/auth/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/admin/flags/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/flags">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/admin/flags/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/admin/rules/[ruleId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/rules/[ruleId]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/admin/rules/[ruleId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/admin/rules/[ruleId]/versions/diff/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/rules/[ruleId]/versions/diff">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/admin/rules/[ruleId]/versions/diff/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/admin/rules/[ruleId]/versions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/rules/[ruleId]/versions">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/admin/rules/[ruleId]/versions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/admin/rules/analytics/[ruleId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/rules/analytics/[ruleId]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/admin/rules/analytics/[ruleId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/admin/rules/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/rules/analytics">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/admin/rules/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/admin/rules/analytics/top/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/rules/analytics/top">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/admin/rules/analytics/top/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/admin/rules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/rules">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/admin/rules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/admin/rules/simulate-batch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/rules/simulate-batch">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/admin/rules/simulate-batch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/ai/copilot/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/copilot/feedback">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/ai/copilot/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/ai/copilot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/copilot">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/ai/copilot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/ai/copilot/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/copilot/stats">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/ai/copilot/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analyze">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/auth/invite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/invite">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/auth/invite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/session">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/beta/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/beta">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/beta/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/clients/[id]/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clients/[id]/report">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/clients/[id]/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/clients/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clients/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/clients/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/clients/[id]/strategic-plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clients/[id]/strategic-plan">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/clients/[id]/strategic-plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/clients/onboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clients/onboard">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/clients/onboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/clients/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clients">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/clients/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/confidence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/confidence">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/confidence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/consulting-dna/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/consulting-dna">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/consulting-dna/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/consulting/analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/consulting/analyze">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/consulting/analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/consulting/compliance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/consulting/compliance">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/consulting/compliance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/consulting/strategy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/consulting/strategy">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/consulting/strategy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/dashboard/[tenantId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/[tenantId]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/dashboard/[tenantId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/due-diligence/analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/due-diligence/analyze">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/due-diligence/analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/due-diligence/companies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/due-diligence/companies">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/due-diligence/companies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/due-diligence/jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/due-diligence/jobs">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/due-diligence/jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/due-diligence/parse/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/due-diligence/parse">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/due-diligence/parse/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/due-diligence/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/due-diligence/start">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/due-diligence/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/due-diligence/template/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/due-diligence/template">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/due-diligence/template/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/execution/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/execution">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/execution/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/executive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/executive">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/executive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/financial-statements/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/financial-statements/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/financial-statements/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/financial-statements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/financial-statements">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/financial-statements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/genome/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/genome">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/genome/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/identity/roles/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/identity/roles/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/identity/roles/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/identity/roles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/identity/roles">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/identity/roles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/knowledge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/knowledge">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/knowledge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/leads/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/leads/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/leads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/leads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/learning/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/learning">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/learning/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/margins/[tenantId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/margins/[tenantId]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/margins/[tenantId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/memory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/memory">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/memory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/memory/timeline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/memory/timeline">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/memory/timeline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/metrics">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/monte-carlo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monte-carlo">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/monte-carlo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/nlu/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/nlu">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/nlu/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/optimization/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/optimization">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/optimization/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/planning/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/planning">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/planning/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/platform/certification/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/platform/certification">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/platform/certification/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/platform/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/platform">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/platform/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/portal/change-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/change-password">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/portal/change-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/portal/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/login">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/portal/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/portal/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/logout">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/portal/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/portal/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/reports">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/portal/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/prediction/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/prediction">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/prediction/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/product-os/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/product-os">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/product-os/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/products/[id]/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[id]/config">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/products/[id]/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/products/[id]/lifecycle/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[id]/lifecycle">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/products/[id]/lifecycle/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/products/[id]/migrate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[id]/migrate">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/products/[id]/migrate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/products/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/products/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/ratios/[tenantId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ratios/[tenantId]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/ratios/[tenantId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/reasoning/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reasoning">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/reasoning/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/reports/[jobId]/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/[jobId]/pdf">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/reports/[jobId]/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/scraping/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scraping">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/scraping/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/stripe/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/checkout">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/stripe/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/stripe/portal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/portal">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/stripe/portal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/stripe/subscription/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/subscription">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/stripe/subscription/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/stripe/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/webhook">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/stripe/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/system/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/system/tasks">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/system/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/system/telemetry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/system/telemetry">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/system/telemetry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/system/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/system/validate">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/system/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/valuation/[tenantId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/valuation/[tenantId]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/valuation/[tenantId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/workflows/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workflows">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/workflows/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/xbrl/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/xbrl">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/xbrl/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../../src/app/cliente/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/cliente">> = Specific
  const handler = {} as typeof import("../../../../src/app/cliente/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/consultor/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/consultor/dashboard">> = Specific
  const handler = {} as typeof import("../../../../src/app/consultor/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/consultor/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/consultor">> = Specific
  const handler = {} as typeof import("../../../../src/app/consultor/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/director/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/director">> = Specific
  const handler = {} as typeof import("../../../../src/app/director/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/due-diligence/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/due-diligence">> = Specific
  const handler = {} as typeof import("../../../../src/app/due-diligence/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
