export interface SRITaxRate {
  id: string
  name: string
  type: "income_tax" | "vat" | "ice" | "withholding" | "social_benefits" | "contributions"
  rate: number
  description: string
  reference: string
  applicability: string
  effectiveDate: string
}

export interface SRIEconomicActivity {
  code: string
  name: string
  sector: string
  description: string
}

export interface SRIBenchmark {
  sector: string
  industryCode: string
  averageRevenue: number
  averageTaxBurden: number
  averageVATDeclared: number
  averageEmployees: number
  averageOperatingMargin: number
  sampleSize: number
  year: number
}

export const ecuadorTaxRates2026: SRITaxRate[] = [
  {
    id: "sri-ir-001",
    name: "Impuesto a la Renta Sociedades",
    type: "income_tax",
    rate: 0.25,
    description: "Tasa general del 25% sobre utilidades gravables para sociedades ecuatorianas",
    reference: "LRTI Art. 37",
    applicability: "Todas las sociedades constituidas en Ecuador",
    effectiveDate: "2026-01-01",
  },
  {
    id: "sri-ir-002",
    name: "Impuesto a la Renta Personas Naturales",
    type: "income_tax",
    rate: 0.00,
    description: "Tarifa progresiva desde 0% hasta 35% según tabla de ingresos",
    reference: "LRTI Art. 36, Reglamento Art. 28",
    applicability: "Personas naturales residentes en Ecuador",
    effectiveDate: "2026-01-01",
  },
  {
    id: "sri-ir-003",
    name: "Anticipo Impuesto a la Renta",
    type: "income_tax",
    rate: 0.50,
    description: "50% del IR causado del ejercicio anterior como anticipo para el ejercicio corriente",
    reference: "LRTI Art. 41",
    applicability: "Sociedades y personas obligadas a llevar contabilidad",
    effectiveDate: "2026-01-01",
  },
  {
    id: "sri-iva-001",
    name: "IVA Tarifa General",
    type: "vat",
    rate: 0.15,
    description: "Tarifa general del Impuesto al Valor Agregado (reducida del 12% al 15% según reforma 2026)",
    reference: "LRTI Art. 52, 55",
    applicability: "Transferencia de bienes y prestación de servicios gravados",
    effectiveDate: "2026-03-01",
  },
  {
    id: "sri-iva-002",
    name: "IVA Tarifa 0%",
    type: "vat",
    rate: 0.00,
    description: "Exportaciones, productos alimenticios básicos, medicinas, transporte, educación, salud",
    reference: "LRTI Art. 55",
    applicability: "Bienes y servicios específicos de primera necesidad",
    effectiveDate: "2026-01-01",
  },
  {
    id: "sri-rte-001",
    name: "Retención en la Fuente IR - Servicios",
    type: "withholding",
    rate: 0.02,
    description: "Retención del 2% sobre servicios en general",
    reference: "Resolución SRI",
    applicability: "Personas jurídicas que pagan a personas naturales",
    effectiveDate: "2026-01-01",
  },
  {
    id: "sri-rte-002",
    name: "Retención en la Fuente IR - Honorarios",
    type: "withholding",
    rate: 0.08,
    description: "Retención del 8% sobre honorarios profesionales",
    reference: "Resolución SRI",
    applicability: "Pagos a profesionales liberales",
    effectiveDate: "2026-01-01",
  },
  {
    id: "sri-rte-003",
    name: "Retención en la Fuente IR - Arriendos",
    type: "withholding",
    rate: 0.08,
    description: "Retención del 8% sobre arriendos de bienes inmuebles",
    reference: "Resolución SRI",
    applicability: "Pagos de arrendamiento a personas naturales",
    effectiveDate: "2026-01-01",
  },
  {
    id: "sri-rte-004",
    name: "Retención en la Fuente IR - Dividendos",
    type: "withholding",
    rate: 0.10,
    description: "Retención del 10% sobre dividendos distribuidos a personas naturales",
    reference: "LRTI Art. 47",
    applicability: "Distribución de utilidades a accionistas personas naturales",
    effectiveDate: "2026-01-01",
  },
  {
    id: "sri-rte-005",
    name: "Retención IVA - Servicios",
    type: "withholding",
    rate: 0.30,
    description: "Retención del 30% del IVA en servicios profesionales",
    reference: "Resolución SRI",
    applicability: "Agentes de retención que reciben servicios profesionales",
    effectiveDate: "2026-01-01",
  },
  {
    id: "sri-ice-001",
    name: "ICE - Vehículos Motorizados",
    type: "ice",
    rate: 0.10,
    description: "ICE entre 5% y 35% según precio y cilindraje del vehículo",
    reference: "LRTI Art. 75-82",
    applicability: "Importación y venta de vehículos motorizados",
    effectiveDate: "2026-01-01",
  },
  {
    id: "sri-ice-002",
    name: "ICE - Bebidas Alcohólicas",
    type: "ice",
    rate: 0.40,
    description: "ICE 40% sobre bebidas alcohólicas",
    reference: "LRTI Art. 75-82",
    applicability: "Productores e importadores de bebidas alcohólicas",
    effectiveDate: "2026-01-01",
  },
  {
    id: "sri-lab-001",
    name: "Aporte IESS Patronal",
    type: "social_benefits",
    rate: 0.1175,
    description: "Aporte patronal al IESS del 11.75% sobre remuneración",
    reference: "Código de Trabajo, Ley IESS",
    applicability: "Todos los empleadores con trabajadores afiliados",
    effectiveDate: "2026-01-01",
  },
  {
    id: "sri-lab-002",
    name: "Aporte IESS Personal",
    type: "social_benefits",
    rate: 0.0945,
    description: "Aporte personal al IESS del 9.45% sobre remuneración",
    reference: "Ley IESS",
    applicability: "Todos los trabajadores afiliados",
    effectiveDate: "2026-01-01",
  },
  {
    id: "sri-lab-003",
    name: "Fondos de Reserva",
    type: "social_benefits",
    rate: 0.0833,
    description: "8.33% mensual después del primer año de trabajo",
    reference: "Código de Trabajo Art. 196",
    applicability: "Trabajadores con más de 1 año de antigüedad",
    effectiveDate: "2026-01-01",
  },
  {
    id: "sri-lab-004",
    name: "Décimo Tercero (13th Salary)",
    type: "social_benefits",
    rate: 0.0833,
    description: "Doceava parte de ingresos anuales, pagadero en diciembre",
    reference: "Código de Trabajo Art. 111",
    applicability: "Todos los trabajadores",
    effectiveDate: "2026-01-01",
  },
  {
    id: "sri-lab-005",
    name: "Décimo Cuarto (14th Salary)",
    type: "social_benefits",
    rate: 0.0833,
    description: "Un salario básico unificado, pagadero en agosto (costa) o marzo (sierra)",
    reference: "Código de Trabajo Art. 113",
    applicability: "Todos los trabajadores",
    effectiveDate: "2026-01-01",
  },
  {
    id: "sri-lab-006",
    name: "Participación Utilidades Trabajadores",
    type: "contributions",
    rate: 0.15,
    description: "15% de utilidades netas: 10% para trabajadores, 5% cargas familiares",
    reference: "Código de Trabajo Art. 97",
    applicability: "Empresas con más de 10 empleados",
    effectiveDate: "2026-01-01",
  },
  {
    id: "sri-lab-007",
    name: "Salario Básico Unificado 2026",
    type: "social_benefits",
    rate: 500,
    description: "Salario básico mensual para trabajadores del sector privado",
    reference: "Ministerio de Trabajo, Resolución SBU 2026",
    applicability: "Todos los trabajadores del sector privado",
    effectiveDate: "2026-01-01",
  },
]

export const sriActivities: SRIEconomicActivity[] = [
  { code: "A0111", name: "Cultivo de cereales", sector: "Agricultura", description: "Cultivo de arroz, maíz, trigo, cebada, avena y otros cereales" },
  { code: "A0121", name: "Cultivo de hortalizas", sector: "Agricultura", description: "Cultivo de hortalizas, melones, raíces y tubérculos" },
  { code: "A0141", name: "Ganadería", sector: "Agricultura", description: "Cría de ganado bovino, ovino, caprino, equino" },
  { code: "A0311", name: "Pesca marítima", sector: "Pesca", description: "Pesca de arrastre, cerco y palangre" },
  { code: "C1011", name: "Procesamiento de carne", sector: "Manufactura", description: "Producción de carnes rojas y embutidos" },
  { code: "C1021", name: "Procesamiento de pescado", sector: "Manufactura", description: "Elaboración de productos pesqueros" },
  { code: "C1041", name: "Aceites y grasas", sector: "Manufactura", description: "Elaboración de aceites y grasas de origen vegetal y animal" },
  { code: "C1071", name: "Panadería", sector: "Manufactura", description: "Elaboración de productos de panadería y pastelería" },
  { code: "C1101", name: "Bebidas no alcohólicas", sector: "Manufactura", description: "Elaboración de bebidas no alcohólicas y aguas" },
  { code: "C1311", name: "Textiles", sector: "Manufactura", description: "Preparación e hilatura de fibras textiles" },
  { code: "C1411", name: "Prendas de vestir", sector: "Manufactura", description: "Confección de prendas de vestir" },
  { code: "C1511", name: "Curtido de cuero", sector: "Manufactura", description: "Curtido y adobo de cueros" },
  { code: "C2011", name: "Químicos básicos", sector: "Manufactura", description: "Fabricación de sustancias químicas básicas" },
  { code: "C2101", name: "Productos farmacéuticos", sector: "Manufactura", description: "Fabricación de productos farmacéuticos" },
  { code: "C2221", name: "Plásticos", sector: "Manufactura", description: "Fabricación de productos de plástico" },
  { code: "C2311", name: "Vidrio", sector: "Manufactura", description: "Fabricación de vidrio y productos de vidrio" },
  { code: "C2511", name: "Estructuras metálicas", sector: "Manufactura", description: "Fabricación de estructuras metálicas" },
  { code: "C2611", name: "Electrónicos", sector: "Manufactura", description: "Fabricación de componentes electrónicos" },
  { code: "C2711", name: "Equipo eléctrico", sector: "Manufactura", description: "Fabricación de motores, generadores y transformadores" },
  { code: "C2811", name: "Maquinaria industrial", sector: "Manufactura", description: "Fabricación de maquinaria de uso general" },
  { code: "C3101", name: "Muebles", sector: "Manufactura", description: "Fabricación de muebles" },
  { code: "C3211", name: "Joyas y bisutería", sector: "Manufactura", description: "Fabricación de joyas y artículos conexos" },
  { code: "C3221", name: "Instrumentos musicales", sector: "Manufactura", description: "Fabricación de instrumentos musicales" },
  { code: "F4101", name: "Construcción edificios", sector: "Construcción", description: "Construcción de edificios residenciales y no residenciales" },
  { code: "F4211", name: "Construcción carreteras", sector: "Construcción", description: "Construcción de carreteras y vías de ferrocarril" },
  { code: "F4291", name: "Otras obras ingeniería", sector: "Construcción", description: "Obras de ingeniería civil no clasificadas" },
  { code: "G4511", name: "Venta de vehículos", sector: "Comercio", description: "Venta de vehículos automotores" },
  { code: "G4711", name: "Comercio al por menor", sector: "Comercio", description: "Venta al por menor en almacenes no especializados" },
  { code: "G4721", name: "Alimentos y bebidas", sector: "Comercio", description: "Venta al por menor de alimentos y bebidas" },
  { code: "G4741", name: "Equipo informático", sector: "Comercio", description: "Venta al por menor de equipos informáticos" },
  { code: "G4751", name: "Equipo hogar", sector: "Comercio", description: "Venta al por menor de electrodomésticos" },
  { code: "G4761", name: "Libros y periódicos", sector: "Comercio", description: "Venta al por menor de libros y periódicos" },
  { code: "G4771", name: "Prendas de vestir", sector: "Comercio", description: "Venta al por menor de prendas de vestir" },
  { code: "G4781", name: "Mercados", sector: "Comercio", description: "Venta al por menor en puestos de venta y mercados" },
  { code: "H4911", name: "Transporte ferroviario", sector: "Transporte", description: "Transporte interurbano de pasajeros y carga" },
  { code: "H4921", name: "Transporte terrestre", sector: "Transporte", description: "Transporte de pasajeros y carga por carretera" },
  { code: "H5011", name: "Transporte marítimo", sector: "Transporte", description: "Transporte marítimo de pasajeros y carga" },
  { code: "H5111", name: "Transporte aéreo", sector: "Transporte", description: "Transporte aéreo de pasajeros y carga" },
  { code: "H5211", name: "Almacenamiento", sector: "Transporte", description: "Servicios de almacenamiento y depósito" },
  { code: "I5511", name: "Hoteles", sector: "Servicios", description: "Servicios de alojamiento en hoteles" },
  { code: "I5611", name: "Restaurantes", sector: "Servicios", description: "Servicios de comidas y bebidas" },
  { code: "J5811", name: "Edición de libros", sector: "Servicios", description: "Edición de libros y publicaciones" },
  { code: "J5911", name: "Producción audiovisual", sector: "Servicios", description: "Actividades de producción de películas y videos" },
  { code: "J6111", name: "Telecomunicaciones", sector: "Servicios", description: "Actividades de telecomunicaciones alámbricas" },
  { code: "J6201", name: "Desarrollo de software", sector: "Tecnología", description: "Desarrollo de software a la medida" },
  { code: "J6311", name: "Procesamiento de datos", sector: "Tecnología", description: "Procesamiento de datos y hosting" },
  { code: "K6411", name: "Banca", sector: "Financiero", description: "Banca múltiple y banca de desarrollo" },
  { code: "K6421", name: "Cooperativas", sector: "Financiero", description: "Cooperativas de ahorro y crédito" },
  { code: "K6511", name: "Seguros", sector: "Financiero", description: "Seguros generales y de vida" },
  { code: "K6611", name: "Servicios financieros", sector: "Financiero", description: "Servicios auxiliares a la intermediación financiera" },
  { code: "L6811", name: "Bienes raíces", sector: "Servicios", description: "Actividades inmobiliarias con bienes propios" },
  { code: "M6911", name: "Actividades jurídicas", sector: "Servicios", description: "Servicios jurídicos y notariales" },
  { code: "M6921", name: "Contabilidad y auditoría", sector: "Servicios", description: "Servicios de contabilidad y auditoría" },
  { code: "M7021", name: "Consultoría gestión", sector: "Servicios", description: "Servicios de consultoría de gestión empresarial" },
  { code: "M7111", name: "Arquitectura e ingeniería", sector: "Servicios", description: "Servicios de arquitectura e ingeniería" },
  { code: "M7311", name: "Publicidad", sector: "Servicios", description: "Agencias de publicidad" },
  { code: "M7491", name: "Servicios técnicos", sector: "Servicios", description: "Servicios técnicos profesionales" },
  { code: "N7711", name: "Alquiler de vehículos", sector: "Servicios", description: "Alquiler de vehículos automotores" },
  { code: "N7821", name: "Empleo temporal", sector: "Servicios", description: "Servicios de empleo temporal" },
  { code: "N8011", name: "Seguridad privada", sector: "Servicios", description: "Servicios de seguridad privada" },
  { code: "N8121", name: "Limpieza", sector: "Servicios", description: "Servicios de limpieza general" },
  { code: "N8221", name: "Centros de llamadas", sector: "Servicios", description: "Actividades de centros de llamadas" },
  { code: "P8511", name: "Educación inicial", sector: "Educación", description: "Enseñanza preescolar y educación inicial" },
  { code: "P8521", name: "Educación básica", sector: "Educación", description: "Enseñanza primaria y secundaria" },
  { code: "P8531", name: "Educación superior", sector: "Educación", description: "Enseñanza superior universitaria" },
  { code: "Q8611", name: "Hospitales", sector: "Salud", description: "Actividades de hospitales y clínicas" },
  { code: "Q8621", name: "Consultorios", sector: "Salud", description: "Servicios de consultorios médicos" },
  { code: "Q8691", name: "Servicios de salud", sector: "Salud", description: "Otros servicios de atención de salud" },
  { code: "R9311", name: "Actividades deportivas", sector: "Deportes", description: "Gestión de instalaciones deportivas" },
  { code: "S9411", name: "Asociaciones", sector: "Servicios", description: "Actividades de asociaciones empresariales" },
  { code: "S9511", name: "Reparación computadoras", sector: "Servicios", description: "Mantenimiento y reparación de equipos informáticos" },
  { code: "S9601", name: "Servicios personales", sector: "Servicios", description: "Servicios personales diversos" },
]

export const sriBenchmarks: SRIBenchmark[] = [
  { sector: "Agricultura", industryCode: "A", averageRevenue: 450000, averageTaxBurden: 0.08, averageVATDeclared: 54000, averageEmployees: 12, averageOperatingMargin: 0.18, sampleSize: 1250, year: 2025 },
  { sector: "Manufactura", industryCode: "C", averageRevenue: 1200000, averageTaxBurden: 0.10, averageVATDeclared: 156000, averageEmployees: 28, averageOperatingMargin: 0.15, sampleSize: 3400, year: 2025 },
  { sector: "Construcción", industryCode: "F", averageRevenue: 850000, averageTaxBurden: 0.07, averageVATDeclared: 76500, averageEmployees: 20, averageOperatingMargin: 0.12, sampleSize: 2100, year: 2025 },
  { sector: "Comercio", industryCode: "G", averageRevenue: 950000, averageTaxBurden: 0.06, averageVATDeclared: 57000, averageEmployees: 15, averageOperatingMargin: 0.10, sampleSize: 5800, year: 2025 },
  { sector: "Transporte", industryCode: "H", averageRevenue: 600000, averageTaxBurden: 0.05, averageVATDeclared: 18000, averageEmployees: 18, averageOperatingMargin: 0.14, sampleSize: 980, year: 2025 },
  { sector: "Servicios", industryCode: "I-S", averageRevenue: 350000, averageTaxBurden: 0.09, averageVATDeclared: 31500, averageEmployees: 10, averageOperatingMargin: 0.22, sampleSize: 4200, year: 2025 },
  { sector: "Tecnología", industryCode: "J", averageRevenue: 500000, averageTaxBurden: 0.08, averageVATDeclared: 40000, averageEmployees: 8, averageOperatingMargin: 0.25, sampleSize: 650, year: 2025 },
  { sector: "Financiero", industryCode: "K", averageRevenue: 2500000, averageTaxBurden: 0.12, averageVATDeclared: 150000, averageEmployees: 35, averageOperatingMargin: 0.30, sampleSize: 520, year: 2025 },
  { sector: "Salud", industryCode: "Q", averageRevenue: 300000, averageTaxBurden: 0.06, averageVATDeclared: 18000, averageEmployees: 14, averageOperatingMargin: 0.18, sampleSize: 780, year: 2025 },
  { sector: "Educación", industryCode: "P", averageRevenue: 200000, averageTaxBurden: 0.04, averageVATDeclared: 0, averageEmployees: 22, averageOperatingMargin: 0.15, sampleSize: 450, year: 2025 },
]
