module.exports = [
"[next]/internal/font/google/inter_c90aabcd.module.css [app-rsc] (css module)", ((__turbopack_context__) => {

__turbopack_context__.v({
  "className": "inter_c90aabcd-module__Q2KVYa__className",
  "variable": "inter_c90aabcd-module__Q2KVYa__variable",
});
}),
"[next]/internal/font/google/inter_c90aabcd.js [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$next$5d2f$internal$2f$font$2f$google$2f$inter_c90aabcd$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__ = __turbopack_context__.i("[next]/internal/font/google/inter_c90aabcd.module.css [app-rsc] (css module)");
;
const fontData = {
    className: __TURBOPACK__imported__module__$5b$next$5d2f$internal$2f$font$2f$google$2f$inter_c90aabcd$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].className,
    style: {
        fontFamily: "'Inter', 'Inter Fallback'",
        fontStyle: "normal"
    }
};
if (__TURBOPACK__imported__module__$5b$next$5d2f$internal$2f$font$2f$google$2f$inter_c90aabcd$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].variable != null) {
    fontData.variable = __TURBOPACK__imported__module__$5b$next$5d2f$internal$2f$font$2f$google$2f$inter_c90aabcd$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].variable;
}
const __TURBOPACK__default__export__ = fontData;
}),
"[next]/internal/font/google/jetbrains_mono_e6129a51.module.css [app-rsc] (css module)", ((__turbopack_context__) => {

__turbopack_context__.v({
  "className": "jetbrains_mono_e6129a51-module__UWGkRa__className",
  "variable": "jetbrains_mono_e6129a51-module__UWGkRa__variable",
});
}),
"[next]/internal/font/google/jetbrains_mono_e6129a51.js [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$next$5d2f$internal$2f$font$2f$google$2f$jetbrains_mono_e6129a51$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__ = __turbopack_context__.i("[next]/internal/font/google/jetbrains_mono_e6129a51.module.css [app-rsc] (css module)");
;
const fontData = {
    className: __TURBOPACK__imported__module__$5b$next$5d2f$internal$2f$font$2f$google$2f$jetbrains_mono_e6129a51$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].className,
    style: {
        fontFamily: "'JetBrains Mono', 'JetBrains Mono Fallback'",
        fontStyle: "normal"
    }
};
if (__TURBOPACK__imported__module__$5b$next$5d2f$internal$2f$font$2f$google$2f$jetbrains_mono_e6129a51$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].variable != null) {
    fontData.variable = __TURBOPACK__imported__module__$5b$next$5d2f$internal$2f$font$2f$google$2f$jetbrains_mono_e6129a51$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].variable;
}
const __TURBOPACK__default__export__ = fontData;
}),
"[project]/apps/web/src/app/providers.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "Providers",
    ()=>Providers
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const Providers = (0, __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call Providers() from the server but Providers is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/apps/web/src/app/providers.tsx <module evaluation>", "Providers");
}),
"[project]/apps/web/src/app/providers.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "Providers",
    ()=>Providers
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const Providers = (0, __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call Providers() from the server but Providers is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/apps/web/src/app/providers.tsx", "Providers");
}),
"[project]/apps/web/src/app/providers.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$app$2f$providers$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/apps/web/src/app/providers.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$app$2f$providers$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/apps/web/src/app/providers.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$app$2f$providers$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/apps/web/src/core/bus/CommandBus.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "CommandBus",
    ()=>CommandBus,
    "commandBus",
    ()=>commandBus
]);
class CommandBus {
    handlers = new Map();
    register(type, handler) {
        if (this.handlers.has(type)) {
            throw new Error(`Handler already registered for command: ${type}`);
        }
        this.handlers.set(type, handler);
    }
    async dispatch(command) {
        const handler = this.handlers.get(command.type);
        if (!handler) {
            throw new Error(`No handler registered for command: ${command.type}`);
        }
        return handler.handle(command);
    }
}
const commandBus = new CommandBus();
}),
"[project]/apps/web/src/core/bus/QueryBus.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "QueryBus",
    ()=>QueryBus,
    "queryBus",
    ()=>queryBus
]);
class QueryBus {
    handlers = new Map();
    register(type, handler) {
        if (this.handlers.has(type)) {
            throw new Error(`Handler already registered for query: ${type}`);
        }
        this.handlers.set(type, handler);
    }
    async ask(query) {
        const handler = this.handlers.get(query.type);
        if (!handler) {
            throw new Error(`No handler registered for query: ${query.type}`);
        }
        return handler.handle(query);
    }
}
const queryBus = new QueryBus();
}),
"[project]/apps/web/src/core/bus/EventBus.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "EventBus",
    ()=>EventBus,
    "eventBus",
    ()=>eventBus
]);
class EventBus {
    handlers = new Map();
    register(type, handler) {
        const handlers = this.handlers.get(type) || [];
        handlers.push(handler);
        this.handlers.set(type, handlers);
    }
    async publish(event) {
        const handlers = this.handlers.get(event.type) || [];
        await Promise.all(handlers.map((h)=>h.handle(event)));
    }
}
const eventBus = new EventBus();
}),
"[project]/apps/web/src/lib/logger.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "createRequestLogger",
    ()=>createRequestLogger,
    "logger",
    ()=>logger
]);
var __TURBOPACK__imported__module__$5b$externals$5d2f$pino__$5b$external$5d$__$28$pino$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f$pino$29$__ = __turbopack_context__.i("[externals]/pino [external] (pino, cjs, [project]/node_modules/pino)");
;
const level = process.env.LOG_LEVEL || (("TURBOPACK compile-time falsy", 0) ? "TURBOPACK unreachable" : "debug");
const targets = [];
if ("TURBOPACK compile-time truthy", 1) {
    targets.push({
        target: "pino-pretty",
        options: {
            colorize: true
        },
        level
    });
} else //TURBOPACK unreachable
;
const logger = (0, __TURBOPACK__imported__module__$5b$externals$5d2f$pino__$5b$external$5d$__$28$pino$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f$pino$29$__["default"])({
    level,
    ...targets.length > 1 || ("TURBOPACK compile-time value", "development") !== "production" ? {
        transport: {
            targets
        }
    } : "TURBOPACK unreachable",
    redact: {
        paths: [
            "req.headers.authorization",
            "req.headers.cookie",
            "body.password",
            "body.token",
            "body.secret"
        ],
        censor: "[REDACTED]"
    },
    serializers: {
        req: (r)=>({
                method: r.method,
                url: r.url
            }),
        err: __TURBOPACK__imported__module__$5b$externals$5d2f$pino__$5b$external$5d$__$28$pino$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f$pino$29$__["default"].stdSerializers.err
    }
});
function createRequestLogger(req) {
    const start = Date.now();
    const requestId = crypto.randomUUID().slice(0, 8);
    const url = new URL(req.url);
    return {
        requestId,
        info (message, data) {
            logger.info({
                requestId,
                method: req.method,
                path: url.pathname,
                ...data
            }, message);
        },
        warn (message, data) {
            logger.warn({
                requestId,
                method: req.method,
                path: url.pathname,
                ...data
            }, message);
        },
        error (message, data) {
            logger.error({
                requestId,
                method: req.method,
                path: url.pathname,
                ...data
            }, message);
        },
        done () {
            const duration = Date.now() - start;
            logger.info({
                requestId,
                method: req.method,
                path: url.pathname,
                durationMs: duration
            }, "request completed");
        }
    };
}
}),
"[project]/apps/web/src/core/outbox/index.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "OutboxWorker",
    ()=>OutboxWorker,
    "appendToOutbox",
    ()=>appendToOutbox,
    "outboxWorker",
    ()=>outboxWorker,
    "processOutbox",
    ()=>processOutbox
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$EventBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/bus/EventBus.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$logger$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/lib/logger.ts [app-rsc] (ecmascript)");
;
;
const inbox = [];
async function appendToOutbox(event) {
    inbox.push({
        id: crypto.randomUUID(),
        eventType: event.type,
        aggregateId: event.aggregateId,
        payload: event,
        status: "pending",
        createdAt: new Date()
    });
}
async function processOutbox(batchSize = 50) {
    const pending = inbox.filter((m)=>m.status === "pending").slice(0, batchSize);
    for (const msg of pending){
        try {
            await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$EventBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["eventBus"].publish(msg.payload);
            msg.status = "sent";
        } catch  {
            msg.status = "failed";
        }
    }
    return pending.length;
}
class OutboxWorker {
    running = false;
    interval = null;
    start(ms = 5000) {
        if (this.running) return;
        this.running = true;
        this.interval = setInterval(async ()=>{
            try {
                await processOutbox();
            } catch (e) {
                __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$logger$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["logger"].error({
                    err: e
                }, "outbox worker error");
            }
        }, ms);
    }
    stop() {
        this.running = false;
        if (this.interval) {
            clearInterval(this.interval);
            this.interval = null;
        }
    }
}
const outboxWorker = new OutboxWorker();
}),
"[project]/apps/web/src/lib/db/prisma.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "prisma",
    ()=>prisma
]);
var __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f40$prisma$2f$client$29$__ = __turbopack_context__.i("[externals]/@prisma/client [external] (@prisma/client, cjs, [project]/node_modules/@prisma/client)");
;
const globalForPrisma = globalThis;
const prisma = globalForPrisma.prisma ?? new __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f40$prisma$2f$client$29$__["PrismaClient"]();
if ("TURBOPACK compile-time truthy", 1) globalForPrisma.prisma = prisma;
}),
"[project]/apps/web/src/core/bus/index.ts [app-rsc] (ecmascript) <locals>", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([]);
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$CommandBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/bus/CommandBus.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$QueryBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/bus/QueryBus.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$EventBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/bus/EventBus.ts [app-rsc] (ecmascript)");
;
;
;
}),
"[project]/apps/web/src/core/errors/index.ts [app-rsc] (ecmascript) <locals>", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([]);
;
}),
"[project]/apps/web/src/core/errors/DomainError.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "ConflictError",
    ()=>ConflictError,
    "DomainError",
    ()=>DomainError,
    "NotFoundError",
    ()=>NotFoundError,
    "UnauthorizedError",
    ()=>UnauthorizedError,
    "ValidationError",
    ()=>ValidationError
]);
class DomainError extends Error {
    constructor(message){
        super(message);
        this.name = this.constructor.name;
    }
}
class NotFoundError extends DomainError {
    code = "NOT_FOUND";
}
class ValidationError extends DomainError {
    code = "VALIDATION_ERROR";
}
class UnauthorizedError extends DomainError {
    code = "UNAUTHORIZED";
}
class ConflictError extends DomainError {
    code = "CONFLICT";
}
}),
"[project]/apps/web/src/core/use-cases/identity/RegisterCompanyUseCase.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "RegisterCompanyUseCase",
    ()=>RegisterCompanyUseCase,
    "registerCompanyUseCase",
    ()=>registerCompanyUseCase
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/lib/db/prisma.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/apps/web/src/core/bus/index.ts [app-rsc] (ecmascript) <locals>");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$EventBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/bus/EventBus.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/apps/web/src/core/errors/index.ts [app-rsc] (ecmascript) <locals>");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/errors/DomainError.ts [app-rsc] (ecmascript)");
;
;
;
class RegisterCompanyUseCase {
    deps;
    constructor(deps){
        this.deps = deps;
    }
    async handle(command) {
        const { name, taxId, email, phone, firstName, lastName } = command;
        if (!name || !email) {
            throw new Error("VALIDATION: name and email are required");
        }
        const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
        const existing = await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].company.findUnique({
            where: {
                slug
            }
        });
        if (existing) throw new __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ConflictError"]("A company with this name already exists");
        const company = await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].company.create({
            data: {
                name,
                slug,
                taxId: taxId || null,
                email,
                phone: phone || null,
                status: "active"
            }
        });
        await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].companySettings.create({
            data: {
                companyId: company.id
            }
        });
        const roles = await Promise.all([
            __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].role.create({
                data: {
                    companyId: company.id,
                    name: "admin",
                    description: "Administrador del sistema",
                    isSystem: true,
                    permissions: [
                        "all"
                    ]
                }
            }),
            __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].role.create({
                data: {
                    companyId: company.id,
                    name: "director",
                    description: "Director de consultoría",
                    isSystem: true,
                    permissions: [
                        "clients.read",
                        "clients.write",
                        "reports.read",
                        "team.read",
                        "team.write"
                    ]
                }
            }),
            __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].role.create({
                data: {
                    companyId: company.id,
                    name: "consultant",
                    description: "Consultor",
                    isSystem: true,
                    permissions: [
                        "clients.read",
                        "clients.write",
                        "reports.read"
                    ]
                }
            }),
            __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].role.create({
                data: {
                    companyId: company.id,
                    name: "viewer",
                    description: "Solo lectura",
                    isSystem: true,
                    permissions: [
                        "clients.read",
                        "reports.read"
                    ]
                }
            })
        ]);
        const adminRole = roles.find((r)=>r.name === "admin");
        const admin = await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].user.create({
            data: {
                email,
                firstName: firstName || "Admin",
                lastName: lastName || "",
                companyId: company.id
            }
        });
        await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].userRole.create({
            data: {
                userId: admin.id,
                roleId: adminRole.id
            }
        });
        await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$EventBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["eventBus"].publish({
            type: "identity.companyRegistered",
            aggregateId: company.id,
            occurredAt: new Date(),
            companyId: company.id,
            name: company.name,
            email,
            adminId: admin.id
        });
        return {
            companyId: company.id,
            slug: company.slug,
            name: company.name,
            userId: admin.id
        };
    }
}
const registerCompanyUseCase = new RegisterCompanyUseCase();
}),
"[project]/apps/web/src/core/use-cases/identity/InviteUserUseCase.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "InviteUserUseCase",
    ()=>InviteUserUseCase,
    "inviteUserUseCase",
    ()=>inviteUserUseCase
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/lib/db/prisma.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/apps/web/src/core/bus/index.ts [app-rsc] (ecmascript) <locals>");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$EventBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/bus/EventBus.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/apps/web/src/core/errors/index.ts [app-rsc] (ecmascript) <locals>");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/errors/DomainError.ts [app-rsc] (ecmascript)");
;
;
;
class InviteUserUseCase {
    deps;
    constructor(deps){
        this.deps = deps;
    }
    async handle(command) {
        const { companyId, email, roleId, invitedBy } = command;
        if (!email) throw new __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ValidationError"]("Email is required");
        const company = await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].company.findUnique({
            where: {
                id: companyId
            },
            select: {
                id: true
            }
        });
        if (!company) throw new __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["NotFoundError"]("Company not found");
        const existing = await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].user.findFirst({
            where: {
                email,
                companyId
            },
            select: {
                id: true
            }
        });
        if (existing) throw new __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ValidationError"]("User already exists in this company");
        const role = await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].role.findFirst({
            where: {
                id: roleId,
                companyId
            },
            select: {
                id: true
            }
        });
        if (!role) throw new __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["NotFoundError"]("Role not found in this company");
        const user = await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].user.create({
            data: {
                email,
                companyId,
                firstName: email.split("@")[0],
                lastName: ""
            }
        });
        await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].userRole.create({
            data: {
                userId: user.id,
                roleId
            }
        });
        await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$EventBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["eventBus"].publish({
            type: "identity.userInvited",
            aggregateId: user.id,
            occurredAt: new Date(),
            companyId,
            userId: user.id,
            email,
            invitedBy
        });
        return {
            userId: user.id,
            email: user.email
        };
    }
}
const inviteUserUseCase = new InviteUserUseCase();
}),
"[project]/apps/web/src/core/use-cases/identity/CreateRoleUseCase.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "CreateRoleUseCase",
    ()=>CreateRoleUseCase,
    "createRoleUseCase",
    ()=>createRoleUseCase
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/lib/db/prisma.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/apps/web/src/core/bus/index.ts [app-rsc] (ecmascript) <locals>");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$EventBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/bus/EventBus.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/apps/web/src/core/errors/index.ts [app-rsc] (ecmascript) <locals>");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/errors/DomainError.ts [app-rsc] (ecmascript)");
;
;
;
class CreateRoleUseCase {
    deps;
    constructor(deps){
        this.deps = deps;
    }
    async handle(command) {
        const { companyId, name, permissions, createdBy } = command;
        if (!name) throw new __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ValidationError"]("Role name is required");
        const existing = await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].role.findFirst({
            where: {
                name,
                companyId
            },
            select: {
                id: true
            }
        });
        if (existing) throw new __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ValidationError"]("Role already exists in this company");
        const role = await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].role.create({
            data: {
                companyId,
                name,
                description: `Custom role: ${name}`,
                permissions
            }
        });
        await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$EventBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["eventBus"].publish({
            type: "identity.roleCreated",
            aggregateId: role.id,
            occurredAt: new Date(),
            companyId,
            roleId: role.id,
            name: role.name,
            createdBy
        });
        return {
            roleId: role.id,
            name: role.name
        };
    }
}
const createRoleUseCase = new CreateRoleUseCase();
}),
"[project]/apps/web/src/core/use-cases/crm/CreateClientUseCase.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "CreateClientUseCase",
    ()=>CreateClientUseCase,
    "createClientUseCase",
    ()=>createClientUseCase
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/lib/db/prisma.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/apps/web/src/core/bus/index.ts [app-rsc] (ecmascript) <locals>");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$EventBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/bus/EventBus.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/apps/web/src/core/errors/index.ts [app-rsc] (ecmascript) <locals>");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/errors/DomainError.ts [app-rsc] (ecmascript)");
;
;
;
class CreateClientUseCase {
    deps;
    constructor(deps){
        this.deps = deps;
    }
    async handle(command) {
        const company = await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].company.findUnique({
            where: {
                id: command.companyId
            },
            select: {
                id: true
            }
        });
        if (!company) throw new __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["NotFoundError"]("Company not found");
        const client = await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].client.create({
            data: {
                companyId: command.companyId,
                name: command.name,
                taxId: command.taxId || null,
                industry: command.industry || null,
                segment: command.segment || null,
                email: command.email || null,
                phone: command.phone || null,
                createdBy: command.createdBy,
                contacts: {
                    create: {
                        firstName: command.contactFirstName,
                        lastName: command.contactLastName,
                        email: command.contactEmail,
                        isPrimary: true
                    }
                }
            }
        });
        await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$EventBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["eventBus"].publish({
            type: "crm.clientCreated",
            aggregateId: client.id,
            occurredAt: new Date(),
            companyId: command.companyId,
            clientId: client.id,
            name: client.name,
            createdBy: command.createdBy
        });
        return {
            clientId: client.id,
            name: client.name
        };
    }
}
const createClientUseCase = new CreateClientUseCase();
}),
"[project]/apps/web/src/core/exceptions/index.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "AiProviderException",
    ()=>AiProviderException,
    "ClientAlreadyExistsException",
    ()=>ClientAlreadyExistsException,
    "CompanyNotActiveException",
    ()=>CompanyNotActiveException,
    "DocumentNotFoundException",
    ()=>DocumentNotFoundException,
    "DuplicateEmailException",
    ()=>DuplicateEmailException,
    "FinancialStatementException",
    ()=>FinancialStatementException,
    "InsufficientPermissionsException",
    ()=>InsufficientPermissionsException,
    "InvalidOperationException",
    ()=>InvalidOperationException,
    "LeadAlreadyConvertedException",
    ()=>LeadAlreadyConvertedException,
    "SubscriptionExpiredException",
    ()=>SubscriptionExpiredException,
    "WorkflowExecutionException",
    ()=>WorkflowExecutionException
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/apps/web/src/core/errors/index.ts [app-rsc] (ecmascript) <locals>");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/errors/DomainError.ts [app-rsc] (ecmascript)");
;
class ClientAlreadyExistsException extends __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["DomainError"] {
    code = "CLIENT_ALREADY_EXISTS";
    constructor(email){
        super(`Client already exists: ${email}`);
    }
}
class SubscriptionExpiredException extends __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["DomainError"] {
    code = "SUBSCRIPTION_EXPIRED";
    constructor(companyId){
        super(`Subscription expired for company: ${companyId}`);
    }
}
class LeadAlreadyConvertedException extends __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["DomainError"] {
    code = "LEAD_ALREADY_CONVERTED";
    constructor(leadId){
        super(`Lead already converted: ${leadId}`);
    }
}
class InsufficientPermissionsException extends __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["DomainError"] {
    code = "INSUFFICIENT_PERMISSIONS";
    constructor(userId, action){
        super(`User ${userId} lacks permission: ${action}`);
    }
}
class CompanyNotActiveException extends __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["DomainError"] {
    code = "COMPANY_NOT_ACTIVE";
    constructor(companyId){
        super(`Company not active: ${companyId}`);
    }
}
class DuplicateEmailException extends __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["DomainError"] {
    code = "DUPLICATE_EMAIL";
    constructor(email){
        super(`Email already in use: ${email}`);
    }
}
class InvalidOperationException extends __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["DomainError"] {
    code = "INVALID_OPERATION";
    constructor(message){
        super(message);
    }
}
class DocumentNotFoundException extends __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["DomainError"] {
    code = "DOCUMENT_NOT_FOUND";
    constructor(id){
        super(`Document not found: ${id}`);
    }
}
class FinancialStatementException extends __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["DomainError"] {
    code = "FINANCIAL_STATEMENT_ERROR";
    constructor(message){
        super(message);
    }
}
class WorkflowExecutionException extends __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["DomainError"] {
    code = "WORKFLOW_EXECUTION_ERROR";
    constructor(message){
        super(message);
    }
}
class AiProviderException extends __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["DomainError"] {
    code = "AI_PROVIDER_ERROR";
    constructor(provider, message){
        super(`AI provider ${provider} error: ${message}`);
    }
}
}),
"[project]/apps/web/src/core/use-cases/crm/ConvertLeadToClientUseCase.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "ConvertLeadToClientUseCase",
    ()=>ConvertLeadToClientUseCase,
    "convertLeadToClientUseCase",
    ()=>convertLeadToClientUseCase
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/lib/db/prisma.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/apps/web/src/core/bus/index.ts [app-rsc] (ecmascript) <locals>");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$EventBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/bus/EventBus.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/apps/web/src/core/errors/index.ts [app-rsc] (ecmascript) <locals>");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/errors/DomainError.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$exceptions$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/exceptions/index.ts [app-rsc] (ecmascript)");
;
;
;
;
class ConvertLeadToClientUseCase {
    deps;
    constructor(deps){
        this.deps = deps;
    }
    async handle(command) {
        const lead = await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].lead.findUnique({
            where: {
                id: command.leadId
            }
        });
        if (!lead) throw new __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["NotFoundError"]("Lead not found");
        if (lead.convertedToClientId) throw new __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$exceptions$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["LeadAlreadyConvertedException"](command.leadId);
        const client = await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].client.create({
            data: {
                companyId: command.companyId,
                name: `${lead.firstName} ${lead.lastName}`,
                email: lead.email,
                phone: lead.phone,
                source: lead.source,
                score: lead.score,
                createdBy: command.convertedBy
            }
        });
        await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].lead.update({
            where: {
                id: lead.id
            },
            data: {
                convertedToClientId: client.id,
                status: "converted",
                updatedBy: command.convertedBy
            }
        });
        await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].leadActivity.create({
            data: {
                leadId: lead.id,
                type: "conversion",
                notes: "Lead convertido a cliente",
                performedBy: command.convertedBy
            }
        });
        await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$EventBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["eventBus"].publish({
            type: "crm.leadConverted",
            aggregateId: lead.id,
            occurredAt: new Date(),
            companyId: command.companyId,
            leadId: lead.id,
            clientId: client.id,
            convertedBy: command.convertedBy
        });
        return {
            clientId: client.id
        };
    }
}
const convertLeadToClientUseCase = new ConvertLeadToClientUseCase();
}),
"[project]/apps/web/src/core/services/FinancialAnalysisService.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "FinancialAnalysisService",
    ()=>FinancialAnalysisService,
    "financialAnalysisService",
    ()=>financialAnalysisService
]);
class FinancialAnalysisService {
    calculateRatios(data) {
        return {
            liquidity: {
                current: data.currentAssets / (data.currentLiabilities || 1),
                quick: (data.currentAssets - data.inventory) / (data.currentLiabilities || 1),
                cash: data.cash / (data.currentLiabilities || 1)
            },
            solvency: {
                debtToEquity: data.totalLiabilities / (data.equity || 1),
                debtRatio: data.totalLiabilities / (data.totalAssets || 1)
            },
            profitability: {
                grossMargin: data.grossProfit / (data.revenue || 1),
                operatingMargin: data.ebitda / (data.revenue || 1),
                netMargin: data.netIncome / (data.revenue || 1),
                roe: data.netIncome / (data.equity || 1),
                roa: data.netIncome / (data.totalAssets || 1)
            },
            efficiency: {
                assetTurnover: data.revenue / (data.totalAssets || 1),
                inventoryTurnover: data.cogs / (data.inventory || 1)
            }
        };
    }
    assessHealth(ratios) {
        const alerts = [];
        let score = 100;
        if (ratios.liquidity.current < 1.2) {
            score -= 15;
            alerts.push("Liquidez crítica: ratio corriente < 1.2");
        } else if (ratios.liquidity.current < 1.5) {
            score -= 5;
        } else {
            score += 5;
        }
        if (ratios.liquidity.quick < 0.8) {
            score -= 10;
            alerts.push("Prueba ácida baja: < 0.8");
        }
        if (ratios.solvency.debtToEquity > 2.0) {
            score -= 15;
            alerts.push("Endeudamiento alto: D/E > 2.0");
        } else if (ratios.solvency.debtToEquity > 1.0) {
            score -= 5;
        }
        if (ratios.profitability.netMargin < 0.02) {
            score -= 10;
            alerts.push("Margen neto muy bajo");
        } else if (ratios.profitability.netMargin < 0.05) {
            score -= 3;
        }
        if (ratios.profitability.roe < 0.05) {
            score -= 5;
        }
        const status = score >= 80 ? "healthy" : score >= 50 ? "warning" : "critical";
        return {
            score,
            status,
            alerts
        };
    }
}
const financialAnalysisService = new FinancialAnalysisService();
}),
"[project]/apps/web/src/core/use-cases/crm/OnboardClientUseCase.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "OnboardClientUseCase",
    ()=>OnboardClientUseCase,
    "onboardClientUseCase",
    ()=>onboardClientUseCase
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/lib/db/prisma.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/apps/web/src/core/bus/index.ts [app-rsc] (ecmascript) <locals>");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$CommandBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/bus/CommandBus.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$EventBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/bus/EventBus.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$services$2f$FinancialAnalysisService$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/services/FinancialAnalysisService.ts [app-rsc] (ecmascript)");
;
;
;
class OnboardClientUseCase {
    deps;
    constructor(deps){
        this.deps = deps;
    }
    async handle(command) {
        const cmd = {
            type: "crm.createClient",
            companyId: command.companyId,
            name: command.clientData.name,
            taxId: command.clientData.taxId,
            industry: command.clientData.industry,
            email: command.clientData.email,
            phone: command.clientData.phone,
            contactFirstName: command.contactName.split(" ")[0] || command.contactName,
            contactLastName: command.contactName.split(" ").slice(1).join(" ") || "",
            contactEmail: command.contactEmail,
            createdBy: command.createdBy
        };
        const { clientId } = await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$CommandBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["commandBus"].dispatch(cmd);
        if (command.initialDocs) {
            await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].document.createMany({
                data: command.initialDocs.map((doc)=>({
                        companyId: command.companyId,
                        clientId,
                        title: doc.title,
                        documentType: doc.documentType,
                        fileUrl: doc.fileUrl,
                        status: "pending",
                        uploadedBy: command.createdBy
                    }))
            });
        }
        if (command.leadId) {
            const convertCmd = {
                type: "crm.convertLeadToClient",
                leadId: command.leadId,
                companyId: command.companyId,
                convertedBy: command.createdBy
            };
            await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$CommandBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["commandBus"].dispatch(convertCmd);
        }
        const health = __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$services$2f$FinancialAnalysisService$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["financialAnalysisService"].assessHealth(__TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$services$2f$FinancialAnalysisService$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["financialAnalysisService"].calculateRatios({
            currentAssets: 0,
            cash: 0,
            accountsReceivable: 0,
            inventory: 0,
            nonCurrentAssets: 0,
            totalAssets: 0,
            currentLiabilities: 0,
            longTermDebt: 0,
            totalLiabilities: 0,
            equity: 0,
            revenue: 0,
            cogs: 0,
            grossProfit: 0,
            opex: 0,
            ebitda: 0,
            netIncome: 0
        }));
        await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].auditLog.create({
            data: {
                companyId: command.companyId,
                userId: command.createdBy,
                action: "CLIENT_ONBOARDED",
                entity: "client",
                entityId: clientId,
                newValues: {
                    clientId,
                    healthStatus: health.status,
                    healthScore: health.score
                }
            }
        });
        await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$EventBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["eventBus"].publish({
            type: "crm.clientOnboarded",
            aggregateId: clientId,
            occurredAt: new Date(),
            companyId: command.companyId,
            clientId,
            documentsCount: command.initialDocs?.length ?? 0,
            healthStatus: health.status,
            createdBy: command.createdBy
        });
        return {
            clientId
        };
    }
}
const onboardClientUseCase = new OnboardClientUseCase();
}),
"[project]/apps/web/src/core/services/RiskAssessmentService.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "RiskAssessmentService",
    ()=>RiskAssessmentService,
    "riskAssessmentService",
    ()=>riskAssessmentService
]);
class RiskAssessmentService {
    assess(factors) {
        const evaluated = factors.map((f)=>({
                name: f.name || "unknown",
                weight: f.weight || 1,
                score: Math.min(100, Math.max(0, f.score || 0)),
                description: f.description || ""
            }));
        const totalWeight = evaluated.reduce((sum, f)=>sum + f.weight, 0);
        const overallScore = totalWeight > 0 ? Math.round(evaluated.reduce((sum, f)=>sum + f.score * f.weight, 0) / totalWeight) : 0;
        const level = overallScore >= 70 ? "low" : overallScore >= 50 ? "moderate" : overallScore >= 30 ? "high" : "critical";
        const recommendations = [];
        evaluated.filter((f)=>f.score < 50).forEach((f)=>{
            recommendations.push(`Mitigar riesgo en "${f.name}": ${f.description}`);
        });
        return {
            overallScore,
            level,
            factors: evaluated,
            recommendations
        };
    }
}
const riskAssessmentService = new RiskAssessmentService();
}),
"[project]/apps/web/src/core/use-cases/consulting/AnalyzeFinancialStatementsUseCase.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "AnalyzeFinancialStatementsUseCase",
    ()=>AnalyzeFinancialStatementsUseCase,
    "analyzeFinancialStatementsUseCase",
    ()=>analyzeFinancialStatementsUseCase
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/lib/db/prisma.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/apps/web/src/core/bus/index.ts [app-rsc] (ecmascript) <locals>");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$EventBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/bus/EventBus.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$services$2f$FinancialAnalysisService$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/services/FinancialAnalysisService.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$services$2f$RiskAssessmentService$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/services/RiskAssessmentService.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/apps/web/src/core/errors/index.ts [app-rsc] (ecmascript) <locals>");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/errors/DomainError.ts [app-rsc] (ecmascript)");
;
;
;
;
;
class AnalyzeFinancialStatementsUseCase {
    deps;
    constructor(deps){
        this.deps = deps;
    }
    async handle(command) {
        const client = await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].client.findFirst({
            where: {
                id: command.clientId,
                companyId: command.companyId
            }
        });
        if (!client) throw new __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["NotFoundError"]("Client not found");
        const statements = await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].financialStatement.findMany({
            where: {
                id: {
                    in: command.financialStatementIds
                },
                clientId: command.clientId
            }
        });
        if (statements.length === 0) throw new __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$errors$2f$DomainError$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["NotFoundError"]("No financial statements found");
        const latest = statements[statements.length - 1];
        const data = latest.data;
        const financialData = {
            currentAssets: data.current_assets || 0,
            cash: data.cash || 0,
            accountsReceivable: data.accounts_receivable || 0,
            inventory: data.inventory || 0,
            nonCurrentAssets: data.non_current_assets || 0,
            totalAssets: data.total_assets || 0,
            currentLiabilities: data.current_liabilities || 0,
            longTermDebt: data.long_term_debt || 0,
            totalLiabilities: data.total_liabilities || 0,
            equity: data.equity || 0,
            revenue: data.revenue || 0,
            cogs: data.cogs || 0,
            grossProfit: data.gross_profit || 0,
            opex: data.opex || 0,
            ebitda: data.ebitda || 0,
            netIncome: data.net_income || 0
        };
        const ratios = __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$services$2f$FinancialAnalysisService$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["financialAnalysisService"].calculateRatios(financialData);
        const health = __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$services$2f$FinancialAnalysisService$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["financialAnalysisService"].assessHealth(ratios);
        const riskAssessment = __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$services$2f$RiskAssessmentService$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["riskAssessmentService"].assess([
            {
                name: "Liquidez",
                weight: 3,
                score: ratios.liquidity.current * 50,
                description: "Capacidad de pago a corto plazo"
            },
            {
                name: "Solvencia",
                weight: 3,
                score: ratios.solvency.debtToEquity < 1 ? 80 : ratios.solvency.debtToEquity < 2 ? 50 : 20,
                description: "Nivel de endeudamiento"
            },
            {
                name: "Rentabilidad",
                weight: 2,
                score: ratios.profitability.netMargin * 2000,
                description: "Generación de utilidades"
            },
            {
                name: "Eficiencia",
                weight: 1,
                score: ratios.efficiency.assetTurnover * 50,
                description: "Uso de activos"
            }
        ]);
        await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].auditLog.create({
            data: {
                companyId: command.companyId,
                userId: command.performedBy,
                action: "FINANCIAL_ANALYSIS",
                entity: "financial_statement",
                entityId: command.financialStatementIds.join(","),
                newValues: {
                    healthScore: health.score,
                    healthStatus: health.status,
                    alerts: health.alerts
                }
            }
        });
        await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$EventBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["eventBus"].publish({
            type: "consulting.financialAnalysisCompleted",
            aggregateId: command.clientId,
            occurredAt: new Date(),
            companyId: command.companyId,
            clientId: command.clientId,
            status: health.status,
            score: health.score,
            performedBy: command.performedBy
        });
        return {
            ratios,
            healthScore: health.score,
            healthStatus: health.status,
            alerts: health.alerts,
            riskAssessment,
            recommendations: [
                ...riskAssessment.recommendations,
                ...health.alerts
            ]
        };
    }
}
const analyzeFinancialStatementsUseCase = new AnalyzeFinancialStatementsUseCase();
}),
"[project]/apps/web/src/core/queries/DashboardDirectorQuery.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "DashboardDirectorHandler",
    ()=>DashboardDirectorHandler,
    "dashboardDirectorHandler",
    ()=>dashboardDirectorHandler
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/lib/db/prisma.ts [app-rsc] (ecmascript)");
;
class DashboardDirectorHandler {
    async handle(query) {
        const [totalClients, activeProjects, clients] = await Promise.all([
            __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].client.count({
                where: {
                    companyId: query.companyId,
                    status: "active"
                }
            }),
            __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].project.count({
                where: {
                    companyId: query.companyId,
                    status: {
                        not: "completed"
                    }
                }
            }),
            __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].client.findMany({
                where: {
                    companyId: query.companyId
                },
                orderBy: {
                    score: "desc"
                },
                take: 5,
                select: {
                    id: true,
                    name: true,
                    score: true
                }
            })
        ]);
        return {
            totalClients,
            activeProjects,
            monthlyRevenue: 0,
            clientHealthAvg: clients.reduce((s, c)=>s + (c.score || 0), 0) / (clients.length || 1),
            topClients: clients,
            recentActivity: []
        };
    }
}
const dashboardDirectorHandler = new DashboardDirectorHandler();
}),
"[project]/apps/web/src/core/services/ClientHealthService.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "ClientHealthService",
    ()=>ClientHealthService,
    "clientHealthService",
    ()=>clientHealthService
]);
class ClientHealthService {
    calculateHealth(client) {
        const alerts = [];
        const engagement = Math.max(0, 100 - client.daysSinceLastInteraction * 2);
        if (client.daysSinceLastInteraction > 30) alerts.push("Cliente sin interacción en más de 30 días");
        const docRatio = client.documentsUploaded / (client.documentsUploaded + client.documentsPending + 1);
        const documentation = Math.round(docRatio * 100);
        if (client.documentsPending > 5) alerts.push(`${client.documentsPending} documentos pendientes`);
        const taskRatio = client.activeProjects > 0 ? 1 - client.overdueTasks / (client.activeProjects * 5 + 1) : 1;
        const operational = Math.round(Math.max(0, taskRatio * 100));
        if (client.overdueTasks > 3) alerts.push(`${client.overdueTasks} tareas vencidas`);
        const financialMap = {
            current: 100,
            late: 40,
            critical: 0
        };
        const financial = financialMap[client.paymentStatus];
        if (client.paymentStatus !== "current") alerts.push("Cliente con pagos atrasados");
        const overall = Math.round(engagement * 0.25 + documentation * 0.25 + operational * 0.25 + financial * 0.25);
        const status = overall >= 80 ? "healthy" : overall >= 60 ? "attention" : overall >= 40 ? "risk" : "churn";
        return {
            overall,
            status,
            dimensions: {
                engagement,
                documentation,
                operational,
                financial
            },
            alerts
        };
    }
}
const clientHealthService = new ClientHealthService();
}),
"[project]/apps/web/src/core/queries/ClientHealthQuery.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "ClientHealthHandler",
    ()=>ClientHealthHandler,
    "clientHealthHandler",
    ()=>clientHealthHandler
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/lib/db/prisma.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$services$2f$ClientHealthService$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/services/ClientHealthService.ts [app-rsc] (ecmascript)");
;
;
class ClientHealthHandler {
    async handle(query) {
        const client = await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].client.findFirst({
            where: {
                id: query.clientId,
                companyId: query.companyId
            }
        });
        if (!client) throw new Error("Client not found");
        const docs = await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].document.findMany({
            where: {
                clientId: query.clientId
            }
        });
        const tickets = await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].ticket.findMany({
            where: {
                clientId: query.clientId
            }
        });
        const projects = await __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$lib$2f$db$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].project.findMany({
            where: {
                clientId: query.clientId
            }
        });
        return __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$services$2f$ClientHealthService$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["clientHealthService"].calculateHealth({
            id: client.id,
            score: client.score || 0,
            daysSinceLastInteraction: 0,
            documentsUploaded: docs.filter((d)=>d.status === "processed").length,
            documentsPending: docs.filter((d)=>d.status === "pending").length,
            activeProjects: projects.filter((p)=>p.status !== "completed").length,
            overdueTasks: 0,
            openTickets: tickets.filter((t)=>t.status === "open").length,
            paymentStatus: "current"
        });
    }
}
const clientHealthHandler = new ClientHealthHandler();
}),
"[project]/apps/web/src/core/register.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "registerCore",
    ()=>registerCore
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$CommandBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/bus/CommandBus.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$QueryBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/bus/QueryBus.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$outbox$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/outbox/index.ts [app-rsc] (ecmascript)");
// Use Cases
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$use$2d$cases$2f$identity$2f$RegisterCompanyUseCase$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/use-cases/identity/RegisterCompanyUseCase.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$use$2d$cases$2f$identity$2f$InviteUserUseCase$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/use-cases/identity/InviteUserUseCase.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$use$2d$cases$2f$identity$2f$CreateRoleUseCase$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/use-cases/identity/CreateRoleUseCase.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$use$2d$cases$2f$crm$2f$CreateClientUseCase$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/use-cases/crm/CreateClientUseCase.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$use$2d$cases$2f$crm$2f$ConvertLeadToClientUseCase$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/use-cases/crm/ConvertLeadToClientUseCase.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$use$2d$cases$2f$crm$2f$OnboardClientUseCase$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/use-cases/crm/OnboardClientUseCase.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$use$2d$cases$2f$consulting$2f$AnalyzeFinancialStatementsUseCase$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/use-cases/consulting/AnalyzeFinancialStatementsUseCase.ts [app-rsc] (ecmascript)");
// Queries
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$queries$2f$DashboardDirectorQuery$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/queries/DashboardDirectorQuery.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$queries$2f$ClientHealthQuery$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/queries/ClientHealthQuery.ts [app-rsc] (ecmascript)");
;
;
;
;
;
;
;
;
;
;
;
;
function registerCore() {
    // Commands
    __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$CommandBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["commandBus"].register("identity.registerCompany", __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$use$2d$cases$2f$identity$2f$RegisterCompanyUseCase$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerCompanyUseCase"]);
    __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$CommandBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["commandBus"].register("identity.inviteUser", __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$use$2d$cases$2f$identity$2f$InviteUserUseCase$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["inviteUserUseCase"]);
    __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$CommandBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["commandBus"].register("identity.createRole", __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$use$2d$cases$2f$identity$2f$CreateRoleUseCase$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createRoleUseCase"]);
    __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$CommandBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["commandBus"].register("crm.createClient", __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$use$2d$cases$2f$crm$2f$CreateClientUseCase$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createClientUseCase"]);
    __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$CommandBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["commandBus"].register("crm.convertLeadToClient", __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$use$2d$cases$2f$crm$2f$ConvertLeadToClientUseCase$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["convertLeadToClientUseCase"]);
    __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$CommandBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["commandBus"].register("crm.onboardClient", __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$use$2d$cases$2f$crm$2f$OnboardClientUseCase$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["onboardClientUseCase"]);
    __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$CommandBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["commandBus"].register("consulting.analyzeFinancialStatements", __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$use$2d$cases$2f$consulting$2f$AnalyzeFinancialStatementsUseCase$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["analyzeFinancialStatementsUseCase"]);
    // Queries
    __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$QueryBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["queryBus"].register("dashboard.director", __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$queries$2f$DashboardDirectorQuery$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["dashboardDirectorHandler"]);
    __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$bus$2f$QueryBus$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["queryBus"].register("client.clientHealth", __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$queries$2f$ClientHealthQuery$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["clientHealthHandler"]);
    // Start outbox worker
    __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$outbox$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["outboxWorker"].start(5000);
}
}),
"[project]/apps/web/src/core/init.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([]);
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$register$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/register.ts [app-rsc] (ecmascript)");
;
(0, __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$register$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerCore"])();
}),
"[project]/apps/web/src/app/layout.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>RootLayout,
    "metadata",
    ()=>metadata
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$next$5d2f$internal$2f$font$2f$google$2f$inter_c90aabcd$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[next]/internal/font/google/inter_c90aabcd.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$next$5d2f$internal$2f$font$2f$google$2f$jetbrains_mono_e6129a51$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[next]/internal/font/google/jetbrains_mono_e6129a51.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$app$2f$providers$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/app/providers.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$core$2f$init$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/apps/web/src/core/init.ts [app-rsc] (ecmascript)");
;
;
;
;
;
;
const metadata = {
    title: "Infinity Command Center",
    description: "Plataforma de inteligencia financiera y consultoría estratégica — Toma de decisiones basada en datos en tiempo real.",
    icons: {
        icon: "/favicon.ico"
    }
};
function RootLayout({ children }) {
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("html", {
        lang: "es",
        className: `${__TURBOPACK__imported__module__$5b$next$5d2f$internal$2f$font$2f$google$2f$inter_c90aabcd$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"].variable} ${__TURBOPACK__imported__module__$5b$next$5d2f$internal$2f$font$2f$google$2f$jetbrains_mono_e6129a51$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"].variable} h-full antialiased`,
        children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("body", {
            className: "min-h-full bg-surface-900 text-surface-100 font-sans",
            children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$apps$2f$web$2f$src$2f$app$2f$providers$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["Providers"], {
                children: children
            }, void 0, false, {
                fileName: "[project]/apps/web/src/app/layout.tsx",
                lineNumber: 37,
                columnNumber: 9
            }, this)
        }, void 0, false, {
            fileName: "[project]/apps/web/src/app/layout.tsx",
            lineNumber: 36,
            columnNumber: 7
        }, this)
    }, void 0, false, {
        fileName: "[project]/apps/web/src/app/layout.tsx",
        lineNumber: 32,
        columnNumber: 5
    }, this);
}
}),
"[project]/apps/web/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/apps/web/src/app/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/apps/web/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)", ((__turbopack_context__, module, exports) => {
"use strict";

module.exports = __turbopack_context__.r("[project]/apps/web/node_modules/next/dist/server/route-modules/app-page/module.compiled.js [app-rsc] (ecmascript)").vendored['react-rsc'].ReactJsxDevRuntime;
}),
"[externals]/pino [external] (pino, cjs, [project]/node_modules/pino)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("pino-28069d5257187539", () => require("pino-28069d5257187539"));

module.exports = mod;
}),
"[externals]/@prisma/client [external] (@prisma/client, cjs, [project]/node_modules/@prisma/client)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("@prisma/client-2c3a283f134fdcb6", () => require("@prisma/client-2c3a283f134fdcb6"));

module.exports = mod;
}),
];

//# sourceMappingURL=%5Broot-of-the-server%5D__1ehh633._.js.map